//! Lua bindings for `crate::api::buffer`, part 1 of 2.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

pub unsafe extern "C-unwind" fn nlua_api_nvim__buf_stats(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim__buf_stats".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim__buf_stats(arg_1, &raw mut arena, &raw mut err);
            nlua_push_Dict(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_attach(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 3 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 3 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_attach".as_ptr(),
                );
            }
            let mut arg_3: KeyDict_buf_attach = core::mem::zeroed();
            'free_arg_3: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_3).cast(),
                    Some(KeyDict_buf_attach_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_3;
                }
                let arg_2 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"send_buffer".as_ptr().cast_mut();
                    break 'free_arg_3;
                }
                let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"buf".as_ptr().cast_mut();
                    break 'free_arg_3;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                let ret = nvim_buf_attach(
                    LUA_INTERNAL_CALL,
                    arg_1,
                    arg_2,
                    &raw mut arg_3,
                    &raw mut err,
                );
                nlua_push_Boolean(lstate, ret, PUSH_SPECIAL);
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_3).cast(), buf_attach_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_call(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_call".as_ptr(),
                );
            }
            let arg_2: LuaRef;
            'free_arg_2: {
                arg_2 = nlua_pop_LuaRef(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"fun".as_ptr().cast_mut();
                    break 'done;
                }
                let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"buf".as_ptr().cast_mut();
                    break 'free_arg_2;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                let mut ret = nvim_buf_call(arg_1, arg_2, &raw mut err);
                nlua_push_Object(lstate, &raw mut ret, PUSH_SPECIAL);
                active_lstate.set(saved_lstate);
            }
            api_free_luaref(arg_2);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_del_keymap(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 3 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 3 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_del_keymap".as_ptr(),
                );
            }
            let arg_3 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"lhs".as_ptr().cast_mut();
                break 'done;
            }
            let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"mode".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_buf_del_keymap(LUA_INTERNAL_CALL, arg_1, arg_2, arg_3, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_del_mark(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_del_mark".as_ptr(),
                );
            }
            let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"name".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_del_mark(arg_1, arg_2, &raw mut err);
            nlua_push_Boolean(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_del_var(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_del_var".as_ptr(),
                );
            }
            let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"name".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_buf_del_var(arg_1, arg_2, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_delete(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_delete".as_ptr(),
                );
            }
            if text_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    get_text_locked_msg(),
                );
                break 'done;
            }
            let mut arg_2: KeyDict_buf_delete = core::mem::zeroed();
            'free_arg_2: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_2).cast(),
                    Some(KeyDict_buf_delete_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_2;
                }
                let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"buf".as_ptr().cast_mut();
                    break 'free_arg_2;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                nvim_buf_delete(arg_1, &raw mut arg_2, &raw mut err);
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_2).cast(), buf_delete_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_changedtick(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_changedtick".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_get_changedtick(arg_1, &raw mut err);
            nlua_push_Integer(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_keymap(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_keymap".as_ptr(),
                );
            }
            let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"mode".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_get_keymap(arg_1, arg_2, &raw mut arena, &raw mut err);
            nlua_push_Array(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_lines(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 4 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 4 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_lines".as_ptr(),
                );
            }
            let arg_4 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"strict_indexing".as_ptr().cast_mut();
                break 'done;
            }
            let arg_3 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"end".as_ptr().cast_mut();
                break 'done;
            }
            let arg_2 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"start".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_get_lines(
                LUA_INTERNAL_CALL,
                arg_1,
                arg_2,
                arg_3,
                arg_4,
                &raw mut arena,
                lstate,
                &raw mut err,
            );
            if lua_gettop(lstate) == 0 {
                nlua_push_Array(lstate, ret, PUSH_SPECIAL);
            }
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_mark(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_mark".as_ptr(),
                );
            }
            let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"name".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_get_mark(arg_1, arg_2, &raw mut arena, &raw mut err);
            nlua_push_Array(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_name(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_name".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_get_name(arg_1, &raw mut err);
            nlua_push_String(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_offset(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_offset".as_ptr(),
                );
            }
            let arg_2 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"index".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_get_offset(arg_1, arg_2, &raw mut err);
            nlua_push_Integer(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_text(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 6 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 6 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_text".as_ptr(),
                );
            }
            let mut arg_6: KeyDict_empty = core::mem::zeroed();
            'free_arg_6: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_6).cast(),
                    Some(KeyDict_empty_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_6;
                }
                let arg_5 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"end_col".as_ptr().cast_mut();
                    break 'free_arg_6;
                }
                let arg_4 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"end_row".as_ptr().cast_mut();
                    break 'free_arg_6;
                }
                let arg_3 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"start_col".as_ptr().cast_mut();
                    break 'free_arg_6;
                }
                let arg_2 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"start_row".as_ptr().cast_mut();
                    break 'free_arg_6;
                }
                let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"buf".as_ptr().cast_mut();
                    break 'free_arg_6;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                let ret = nvim_buf_get_text(
                    LUA_INTERNAL_CALL,
                    arg_1,
                    arg_2,
                    arg_3,
                    arg_4,
                    arg_5,
                    &raw mut arg_6,
                    &raw mut arena,
                    lstate,
                    &raw mut err,
                );
                if lua_gettop(lstate) == 0 {
                    nlua_push_Array(lstate, ret, PUSH_SPECIAL);
                }
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_6).cast(), empty_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_get_var(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_get_var".as_ptr(),
                );
            }
            let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"name".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let mut ret = nvim_buf_get_var(arg_1, arg_2, &raw mut arena, &raw mut err);
            nlua_push_Object(lstate, &raw mut ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_is_loaded(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_is_loaded".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_is_loaded(arg_1);
            nlua_push_Boolean(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_is_valid(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_is_valid".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_is_valid(arg_1);
            nlua_push_Boolean(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_line_count(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_line_count".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_buf_line_count(arg_1, &raw mut err);
            nlua_push_Integer(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_buf_set_keymap(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 5 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 5 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_buf_set_keymap".as_ptr(),
                );
            }
            let mut arg_5: KeyDict_keymap = core::mem::zeroed();
            'free_arg_5: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_5).cast(),
                    Some(KeyDict_keymap_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_5;
                }
                let arg_4 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"rhs".as_ptr().cast_mut();
                    break 'free_arg_5;
                }
                let arg_3 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"lhs".as_ptr().cast_mut();
                    break 'free_arg_5;
                }
                let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"mode".as_ptr().cast_mut();
                    break 'free_arg_5;
                }
                let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"buf".as_ptr().cast_mut();
                    break 'free_arg_5;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                nvim_buf_set_keymap(
                    LUA_INTERNAL_CALL,
                    arg_1,
                    arg_2,
                    arg_3,
                    arg_4,
                    &raw mut arg_5,
                    &raw mut err,
                );
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_5).cast(), keymap_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}
