//! The `vim.api` Lua binding.
//!
//! GENERATED by tools/apigen from the `nvim_*` signatures under
//! `crate::api` plus `tools/apigen/functions.txt`. Do not edit;
//! run `just apigen` (`just apigen --check` fails on drift).
//!
//! One `lua_CFunction` per API function, plus [`nlua_add_api_functions`],
//! which builds the table they hang off. A binding checks that it was handed
//! exactly the arguments the API function declares, pops each one off the Lua
//! stack and converts it, calls the function, and converts the result back.
//!
//! Everything that fails — the wrong number of arguments, a value Lua cannot
//! convert, the API function itself — leaves its reason in one `Error`, and
//! the binding raises it as a Lua error on the way out. Getting there means
//! releasing whatever was already converted, and only that: each converted
//! argument arms a guard, so returning from a failed conversion drops the
//! guards armed before it and no others, in declaration order. Upstream's
//! generator wrote that order out by hand as a chain of `goto exit_N`
//! (src/gen/gen_api_dispatch.lua at tag v0.12.4).
//!
//! This module holds the shared support code and the imports; the bindings
//! themselves live in one child module per API source file, re-exported here
//! so callers see one flat namespace. A source file whose bindings would
//! overflow the tree's 1,000-line file cap is split into numbered parts.

#![deny(unsafe_op_in_unsafe_fn)]
// Unsafe perimeter: the `lua/` row in docs/perimeter.md.
#![allow(unsafe_code)]
#![deny(
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::ptr_as_ptr
)]

mod autocmd;
mod buffer;
mod command;
mod deprecated;
mod extmark;
mod options;
mod register;
mod tabpage;
mod ui;
mod vim;
mod vim_2;
mod vim_3;
mod vimscript;
mod win_config;
mod window;

pub use self::autocmd::*;
pub use self::buffer::*;
pub use self::command::*;
pub use self::deprecated::*;
pub use self::extmark::*;
pub use self::options::*;
pub use self::register::*;
pub use self::tabpage::*;
pub use self::ui::*;
pub use self::vim::*;
pub use self::vim_2::*;
pub use self::vim_3::*;
pub use self::vimscript::*;
pub use self::win_config::*;
pub use self::window::*;

use crate::api::autocmd::{
    nvim_clear_autocmds, nvim_create_augroup, nvim_create_autocmd, nvim_del_augroup_by_id,
    nvim_del_augroup_by_name, nvim_del_autocmd, nvim_exec_autocmds, nvim_get_autocmds,
};
use crate::api::buffer::{
    nvim__buf_stats, nvim_buf_attach, nvim_buf_call, nvim_buf_del_keymap, nvim_buf_del_mark,
    nvim_buf_del_var, nvim_buf_delete, nvim_buf_get_changedtick, nvim_buf_get_keymap,
    nvim_buf_get_lines, nvim_buf_get_mark, nvim_buf_get_name, nvim_buf_get_offset,
    nvim_buf_get_text, nvim_buf_get_var, nvim_buf_is_loaded, nvim_buf_is_valid,
    nvim_buf_line_count, nvim_buf_set_keymap, nvim_buf_set_lines, nvim_buf_set_mark,
    nvim_buf_set_name, nvim_buf_set_text, nvim_buf_set_var,
};
use crate::api::command::{
    nvim_buf_create_user_command, nvim_buf_del_user_command, nvim_buf_get_commands, nvim_cmd,
    nvim_create_user_command, nvim_del_user_command, nvim_get_commands, nvim_parse_cmd,
};
use crate::api::deprecated::{
    nvim_buf_add_highlight, nvim_buf_clear_highlight, nvim_buf_get_number, nvim_buf_get_option,
    nvim_buf_set_option, nvim_buf_set_virtual_text, nvim_command_output, nvim_err_write,
    nvim_err_writeln, nvim_exec, nvim_get_hl_by_id, nvim_get_hl_by_name, nvim_get_option,
    nvim_get_option_info, nvim_notify, nvim_out_write, nvim_set_option, nvim_win_get_option,
    nvim_win_set_option,
};
use crate::api::extmark::{
    nvim__buf_debug_extmarks, nvim__ns_get, nvim__ns_set, nvim_buf_clear_namespace,
    nvim_buf_del_extmark, nvim_buf_get_extmark_by_id, nvim_buf_get_extmarks, nvim_buf_set_extmark,
    nvim_create_namespace, nvim_get_namespaces, nvim_set_decoration_provider,
};
use crate::api::options::{
    nvim_get_all_options_info, nvim_get_option_info2, nvim_get_option_value, nvim_set_option_value,
};
use crate::api::private::dispatch::{
    buf_attach_table, buf_delete_table, clear_autocmds_table, cmd_opts_table, cmd_table,
    complete_set_table, context_table, create_augroup_table, create_autocmd_table, echo_opts_table,
    empty_table, eval_statusline_table, exec_autocmds_table, exec_opts_table, get_autocmds_table,
    get_commands_table, get_extmark_table, get_extmarks_table, get_highlight_table, get_ns_table,
    highlight_table, key_dict_buf_attach_get_field, key_dict_buf_delete_get_field,
    key_dict_clear_autocmds_get_field, key_dict_cmd_get_field, key_dict_cmd_opts_get_field,
    key_dict_complete_set_get_field, key_dict_context_get_field, key_dict_create_augroup_get_field,
    key_dict_create_autocmd_get_field, key_dict_echo_opts_get_field, key_dict_empty_get_field,
    key_dict_eval_statusline_get_field, key_dict_exec_autocmds_get_field,
    key_dict_exec_opts_get_field, key_dict_get_autocmds_get_field, key_dict_get_commands_get_field,
    key_dict_get_extmark_get_field, key_dict_get_extmarks_get_field,
    key_dict_get_highlight_get_field, key_dict_get_ns_get_field, key_dict_highlight_get_field,
    key_dict_keymap_get_field, key_dict_ns_opts_get_field, key_dict_open_term_get_field,
    key_dict_option_get_field, key_dict_redraw_get_field, key_dict_runtime_get_field,
    key_dict_set_decoration_provider_get_field, key_dict_set_extmark_get_field,
    key_dict_tabpage_config_get_field, key_dict_user_command_get_field,
    key_dict_win_config_get_field, key_dict_win_text_height_get_field, keymap_table, ns_opts_table,
    open_term_table, option_table, redraw_table, runtime_table, set_decoration_provider_table,
    set_extmark_table, tabpage_config_table, user_command_table, win_config_table,
    win_text_height_table,
};
use crate::api::private::helpers::{
    api_free_dict, api_free_object, api_free_string, api_luarefs_free_keydict,
    api_luarefs_free_object,
};
use crate::api::tabpage::{
    nvim_open_tabpage, nvim_tabpage_del_var, nvim_tabpage_get_number, nvim_tabpage_get_var,
    nvim_tabpage_get_win, nvim_tabpage_is_valid, nvim_tabpage_list_wins, nvim_tabpage_set_var,
    nvim_tabpage_set_win,
};
use crate::api::ui::nvim_ui_send;
use crate::api::vim::{
    nvim__complete_set, nvim__get_lib_dir, nvim__get_runtime, nvim__id, nvim__id_array,
    nvim__id_dict, nvim__id_float, nvim__inspect_cell, nvim__invalidate_glyph_cache, nvim__redraw,
    nvim__runtime_inspect, nvim__screenshot, nvim__stats, nvim__unpack, nvim_chan_send,
    nvim_create_buf, nvim_del_current_line, nvim_del_keymap, nvim_del_mark, nvim_del_var,
    nvim_echo, nvim_eval_statusline, nvim_feedkeys, nvim_get_chan_info, nvim_get_color_by_name,
    nvim_get_color_map, nvim_get_context, nvim_get_current_buf, nvim_get_current_line,
    nvim_get_current_tabpage, nvim_get_current_win, nvim_get_hl, nvim_get_hl_id_by_name,
    nvim_get_hl_ns, nvim_get_keymap, nvim_get_mark, nvim_get_mode, nvim_get_proc,
    nvim_get_proc_children, nvim_get_runtime_file, nvim_get_var, nvim_get_vvar, nvim_input,
    nvim_input_mouse, nvim_list_bufs, nvim_list_chans, nvim_list_runtime_paths, nvim_list_tabpages,
    nvim_list_uis, nvim_list_wins, nvim_load_context, nvim_open_term, nvim_paste, nvim_put,
    nvim_replace_termcodes, nvim_select_popupmenu_item, nvim_set_current_buf, nvim_set_current_dir,
    nvim_set_current_line, nvim_set_current_tabpage, nvim_set_current_win, nvim_set_hl,
    nvim_set_hl_ns, nvim_set_hl_ns_fast, nvim_set_keymap, nvim_set_var, nvim_set_vvar,
    nvim_strwidth,
};
use crate::api::vimscript::{
    nvim_call_dict_function, nvim_call_function, nvim_command, nvim_eval, nvim_exec2,
    nvim_parse_expression,
};
use crate::api::win_config::{nvim_open_win, nvim_win_get_config, nvim_win_set_config};
use crate::api::window::{
    nvim_win_call, nvim_win_close, nvim_win_del_var, nvim_win_get_buf, nvim_win_get_cursor,
    nvim_win_get_height, nvim_win_get_number, nvim_win_get_position, nvim_win_get_tabpage,
    nvim_win_get_var, nvim_win_get_width, nvim_win_hide, nvim_win_is_valid, nvim_win_set_buf,
    nvim_win_set_cursor, nvim_win_set_height, nvim_win_set_hl_ns, nvim_win_set_var,
    nvim_win_set_width, nvim_win_text_height,
};
use crate::api_error;
use crate::ex_docmd::expr_map_locked;
use crate::ex_getln::{get_text_locked_msg, text_locked};
use crate::global_cell::ConstTable;
use crate::guard::Restore;
use crate::guard::textlock;
use crate::lua::converter::{
    kNluaPushFreeRefs, kNluaPushSpecial, nlua_pop_array, nlua_pop_boolean, nlua_pop_dict,
    nlua_pop_float, nlua_pop_handle, nlua_pop_integer, nlua_pop_keydict, nlua_pop_luaref,
    nlua_pop_object, nlua_pop_string, nlua_push_array, nlua_push_boolean, nlua_push_dict,
    nlua_push_float, nlua_push_handle, nlua_push_integer, nlua_push_keydict, nlua_push_object,
    nlua_push_string,
};
use crate::lua::executor::{
    LUA_INTERNAL_CALL, active_lstate, api_free_luaref, nlua_is_deferred_safe,
};
use crate::lua::ffi::{
    lua_concat, lua_createtable, lua_error, lua_gettop, lua_pushcclosure, lua_pushstring,
    lua_setfield, luaL_error, luaL_where,
};
use crate::memory::{ARENA_EMPTY, arena_finish, arena_mem_free};
use crate::message::{e_fast_api_disabled, e_textlock};
use crate::types::{
    Arena, Error, FieldHashfn, KeyDict_buf_attach, KeyDict_buf_delete, KeyDict_clear_autocmds,
    KeyDict_cmd, KeyDict_cmd_opts, KeyDict_complete_set, KeyDict_context, KeyDict_create_augroup,
    KeyDict_create_autocmd, KeyDict_echo_opts, KeyDict_empty, KeyDict_eval_statusline,
    KeyDict_exec_autocmds, KeyDict_exec_opts, KeyDict_get_autocmds, KeyDict_get_commands,
    KeyDict_get_extmark, KeyDict_get_extmarks, KeyDict_get_highlight, KeyDict_get_ns,
    KeyDict_highlight, KeyDict_keymap, KeyDict_ns_opts, KeyDict_open_term, KeyDict_option,
    KeyDict_redraw, KeyDict_runtime, KeyDict_set_decoration_provider, KeyDict_set_extmark,
    KeyDict_tabpage_config, KeyDict_user_command, KeyDict_win_config, KeyDict_win_text_height,
    KeySetLink, LuaRef, Object, lua_State,
};
use core::ffi::{CStr, c_char, c_int};
use core::ptr;

/// Values that belong to other modules; nested so they stay out of the flat
/// namespace the unit-test header generator collects constants into.
/// `pub(crate)`, not `pub`: `known` is private, so a `pub` item in it is
/// unreachable from outside the crate and `unreachable_pub` says so.
mod known {
    pub(crate) use crate::types::{kErrorTypeException, kErrorTypeValidation};
}

use known::*;

/// Flags for handing a result back to Lua.
///
/// `kNluaPushFreeRefs` always applies: the binding owns the value and
/// releases the Lua references it holds as it converts. `kNluaPushSpecial`
/// additionally converts `nil` and the other special values the pre-0.11
/// way, which is what clients of methods older than API level 11 expect.
const PUSH: c_int = kNluaPushFreeRefs;
const PUSH_SPECIAL: c_int = kNluaPushSpecial | kNluaPushFreeRefs;

/// What one binding carries from its first conversion to its last release.
struct Call {
    /// Where the conversions and the API function allocate. Released once
    /// every argument has been, since the values the releases walk live in
    /// it.
    arena: Arena,
    /// The parameter a failed conversion blamed, named in the message.
    err_param: *mut c_char,
}

impl Call {
    const fn new() -> Self {
        Call {
            arena: ARENA_EMPTY,
            err_param: ptr::null_mut(),
        }
    }
}

/// A binding's own half: pop each argument off the Lua stack, call the API
/// function, hand the result back. Returning — off the end or out of a failed
/// conversion — releases exactly the arguments that were converted, in
/// declaration order, because each one's release is a guard dropped on the
/// way out.
type Convert = unsafe fn(*mut lua_State, &mut Call) -> Result<(), Error>;

// -- keysets ---------------------------------------------------------------

/// A generated keyset, tied to the two generated items that describe it.
///
/// # Safety
/// `GET_FIELD` must be `Self`'s own field lookup and [`table`](Self::table)
/// answer `Self`'s own key table: the decoder writes through the offsets the
/// first hands back and the release walks the second, so either one belonging
/// to a different keyset would read and write outside `Self`.
unsafe trait KeySet: Sized + Default {
    const GET_FIELD: FieldHashfn;

    fn table() -> *const KeySetLink;
}

/// A keyset's generated table, as the code that walks one takes it.
fn keyset_table<const N: usize>(table: &ConstTable<[KeySetLink; N]>) -> *const KeySetLink {
    table.as_ptr()
}

/// A keyset argument, with its release armed from the moment it exists: the
/// decoder fills it field by field, and a fill that stops halfway still holds
/// whatever references it took before it stopped.
struct KeyDictArg<K: KeySet> {
    dict: K,
}

impl<K: KeySet> KeyDictArg<K> {
    /// Every key absent, which is where a keyset argument starts out.
    fn unset() -> Self {
        KeyDictArg { dict: K::default() }
    }
}

impl<K: KeySet> Drop for KeyDictArg<K> {
    fn drop(&mut self) {
        // SAFETY: `K::table()` describes `K`'s fields, per `KeySet`'s
        // contract, and the binding owns the references they name.
        unsafe { api_luarefs_free_keydict((&raw mut self.dict).cast(), K::table()) };
    }
}

/// Fill a keyset argument from the Lua value on top of the stack. On refusal
/// `*err_param` names the key that failed.
///
/// # Safety
/// `lstate` is the running Lua state with the argument on top; `arena` and
/// `err_param` are the binding's own.
unsafe fn pop_keydict<K: KeySet>(
    lstate: *mut lua_State,
    arg: &mut KeyDictArg<K>,
    arena: &mut Arena,
    err_param: &mut *mut c_char,
) -> Result<(), Error> {
    // SAFETY: the caller's stack, and `K::GET_FIELD` is `K`'s own lookup per
    // `KeySet`'s contract, which is what the decoder needs of it.
    unsafe {
        nlua_pop_keydict(
            lstate,
            (&raw mut arg.dict).cast(),
            K::GET_FIELD,
            err_param,
            arena,
        )
    }
}

/// Hand a keyset result back as a Lua table.
///
/// # Safety
/// `lstate` is the running Lua state and `value` points at the binding's own
/// result.
unsafe fn push_keydict<K: KeySet>(lstate: *mut lua_State, value: *mut K) {
    // SAFETY: the caller's stack, and `K::table()` describes `K`'s fields per
    // `KeySet`'s contract.
    unsafe { nlua_push_keydict(lstate, value.cast(), K::table()) };
}

// -- argument guards -------------------------------------------------------

/// An `Object` argument, which puts the Lua references the conversion took
/// out of the registry back when the binding leaves.
struct ObjectArg {
    value: Object,
}

impl ObjectArg {
    /// # Safety
    /// The binding owns the references `value` names and nothing else
    /// releases them.
    unsafe fn new(value: Object) -> Self {
        ObjectArg { value }
    }
}

impl Drop for ObjectArg {
    fn drop(&mut self) {
        // SAFETY: `new`'s contract.
        unsafe { api_luarefs_free_object(self.value) };
    }
}

/// A `LuaRef` argument, released the same way.
struct LuaRefArg {
    value: LuaRef,
}

impl LuaRefArg {
    /// # Safety
    /// As [`ObjectArg::new`].
    unsafe fn new(value: LuaRef) -> Self {
        LuaRefArg { value }
    }
}

impl Drop for LuaRefArg {
    fn drop(&mut self) {
        // SAFETY: `new`'s contract.
        unsafe { api_free_luaref(self.value) };
    }
}

// -- refusals --------------------------------------------------------------

/// Refuses a call that arrived with a different number of arguments than the
/// API function declares.
fn wrong_arity(argc: c_int) -> Error {
    if argc == 1 {
        api_error!(kErrorTypeValidation, "Expected {argc} argument")
    } else {
        api_error!(kErrorTypeValidation, "Expected {argc} arguments")
    }
}

// -- the shared half of every binding --------------------------------------

/// Everything a binding does around its own conversions: check that Lua
/// handed it the arguments the API function declares, hand over to `convert`,
/// release the request arena, and raise whatever error the call left behind.
/// Answers the number of results `convert` left on the stack.
///
/// `deferred` names the binding when its API function is not `fast` and so
/// may not run from a context where deferring is unsafe; it is `None` for one
/// that may run anywhere.
///
/// The error is raised from here rather than from `convert`, because by the
/// time `convert` has returned every argument guard has been dropped and the
/// arena is gone — and `lua_error` does not come back.
///
/// # Safety
/// `lstate` is the running Lua state with the binding's arguments on top;
/// `deferred`, when set, outlives the call; `convert` reads `argc` arguments
/// and leaves `nret` results.
unsafe fn run(
    lstate: *mut lua_State,
    deferred: Option<&CStr>,
    argc: c_int,
    nret: c_int,
    convert: Convert,
) -> c_int {
    let mut call = Call::new();
    // SAFETY: the caller's stack.
    let outcome = if unsafe { lua_gettop(lstate) } != argc {
        Err(wrong_arity(argc))
    } else {
        let refused = deferred.filter(|_| !nlua_is_deferred_safe());
        if let Some(name) = refused {
            let (fmt, name) = (e_fast_api_disabled.as_ptr(), name.as_ptr());
            // SAFETY: as above; both strings are static and NUL-terminated,
            // and nothing is left to release.
            return unsafe { luaL_error(lstate, fmt, name) };
        }
        // SAFETY: as above; `call` is this frame's own.
        unsafe { convert(lstate, &mut call) }
    };
    // SAFETY: the arena is this frame's own, and every argument that borrowed
    // from it has been released.
    unsafe { arena_mem_free(arena_finish(&raw mut call.arena)) };
    let Err(err) = outcome else {
        return nret;
    };
    // SAFETY: as above; `err` carries a message.
    unsafe { stage_error(lstate, &call, &err) };
    // SAFETY: the message is on the stack, and `lua_error` does not return.
    unsafe { lua_error(lstate) }
}

/// [`run`] for a binding whose API function is not `fast`.
///
/// # Safety
/// As [`run`].
unsafe fn dispatch(
    lstate: *mut lua_State,
    name: &CStr,
    argc: c_int,
    nret: c_int,
    convert: Convert,
) -> c_int {
    // SAFETY: the caller's.
    unsafe { run(lstate, Some(name), argc, nret, convert) }
}

/// [`run`] for a binding whose API function is `fast`, and so has no context
/// to refuse.
///
/// # Safety
/// As [`run`].
unsafe fn dispatch_fast(
    lstate: *mut lua_State,
    argc: c_int,
    nret: c_int,
    convert: Convert,
) -> c_int {
    // SAFETY: the caller's.
    unsafe { run(lstate, None, argc, nret, convert) }
}

/// Leave the failed call's message on the Lua stack as one string: the source
/// position, the parameter a failed conversion blamed, and the message
/// itself, ready for `lua_error` to raise.
///
/// # Safety
/// `lstate` is the running Lua state, `call` is the binding's own and `err`
/// the failure it answered with.
unsafe fn stage_error(lstate: *mut lua_State, call: &Call, err: &Error) {
    let message = err.message_or_empty().as_ptr();
    // SAFETY: the caller's stack; `message` is the binding's own error text,
    // live for this call, and `err_param`, when set, points at a static
    // NUL-terminated name.
    unsafe {
        luaL_where(lstate, 1);
        if !call.err_param.is_null() {
            lua_pushstring(lstate, c"Invalid '".as_ptr());
            lua_pushstring(lstate, call.err_param);
            lua_pushstring(lstate, c"': ".as_ptr());
            lua_pushstring(lstate, message);
            lua_concat(lstate, 5);
        } else {
            lua_pushstring(lstate, message);
            lua_concat(lstate, 2);
        }
    }
}

/// One entry of the `vim.api` table.
///
/// # Safety
/// `lstate` has the table under construction on top of its stack.
unsafe fn bind(
    lstate: *mut lua_State,
    f: unsafe extern "C-unwind" fn(*mut lua_State) -> c_int,
    name: &CStr,
) {
    unsafe {
        lua_pushcclosure(lstate, Some(f), 0);
        lua_setfield(lstate, -2, name.as_ptr());
    }
}

/// Refuses a call made while the text is locked.
fn text_locked_error() -> Error {
    Error::from_message(kErrorTypeException, get_text_locked_msg())
}

/// Refuses a call made from an expression mapping, which the cmdline window
/// alone would have allowed.
fn expr_map_locked_error() -> Error {
    Error::from_message(kErrorTypeException, e_textlock)
}

// The keysets the bindings name, each tied to its own generated table
// and lookup.

// SAFETY: `buf_attach_table` and `key_dict_buf_attach_get_field` are the
// generated table and lookup for `KeyDict_buf_attach`.
unsafe impl KeySet for KeyDict_buf_attach {
    const GET_FIELD: FieldHashfn = Some(key_dict_buf_attach_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&buf_attach_table)
    }
}

// SAFETY: `buf_delete_table` and `key_dict_buf_delete_get_field` are the
// generated table and lookup for `KeyDict_buf_delete`.
unsafe impl KeySet for KeyDict_buf_delete {
    const GET_FIELD: FieldHashfn = Some(key_dict_buf_delete_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&buf_delete_table)
    }
}

// SAFETY: `clear_autocmds_table` and `key_dict_clear_autocmds_get_field` are the
// generated table and lookup for `KeyDict_clear_autocmds`.
unsafe impl KeySet for KeyDict_clear_autocmds {
    const GET_FIELD: FieldHashfn = Some(key_dict_clear_autocmds_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&clear_autocmds_table)
    }
}

// SAFETY: `cmd_table` and `key_dict_cmd_get_field` are the
// generated table and lookup for `KeyDict_cmd`.
unsafe impl KeySet for KeyDict_cmd {
    const GET_FIELD: FieldHashfn = Some(key_dict_cmd_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&cmd_table)
    }
}

// SAFETY: `cmd_opts_table` and `key_dict_cmd_opts_get_field` are the
// generated table and lookup for `KeyDict_cmd_opts`.
unsafe impl KeySet for KeyDict_cmd_opts {
    const GET_FIELD: FieldHashfn = Some(key_dict_cmd_opts_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&cmd_opts_table)
    }
}

// SAFETY: `complete_set_table` and `key_dict_complete_set_get_field` are the
// generated table and lookup for `KeyDict_complete_set`.
unsafe impl KeySet for KeyDict_complete_set {
    const GET_FIELD: FieldHashfn = Some(key_dict_complete_set_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&complete_set_table)
    }
}

// SAFETY: `context_table` and `key_dict_context_get_field` are the
// generated table and lookup for `KeyDict_context`.
unsafe impl KeySet for KeyDict_context {
    const GET_FIELD: FieldHashfn = Some(key_dict_context_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&context_table)
    }
}

// SAFETY: `create_augroup_table` and `key_dict_create_augroup_get_field` are the
// generated table and lookup for `KeyDict_create_augroup`.
unsafe impl KeySet for KeyDict_create_augroup {
    const GET_FIELD: FieldHashfn = Some(key_dict_create_augroup_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&create_augroup_table)
    }
}

// SAFETY: `create_autocmd_table` and `key_dict_create_autocmd_get_field` are the
// generated table and lookup for `KeyDict_create_autocmd`.
unsafe impl KeySet for KeyDict_create_autocmd {
    const GET_FIELD: FieldHashfn = Some(key_dict_create_autocmd_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&create_autocmd_table)
    }
}

// SAFETY: `echo_opts_table` and `key_dict_echo_opts_get_field` are the
// generated table and lookup for `KeyDict_echo_opts`.
unsafe impl KeySet for KeyDict_echo_opts {
    const GET_FIELD: FieldHashfn = Some(key_dict_echo_opts_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&echo_opts_table)
    }
}

// SAFETY: `empty_table` and `key_dict_empty_get_field` are the
// generated table and lookup for `KeyDict_empty`.
unsafe impl KeySet for KeyDict_empty {
    const GET_FIELD: FieldHashfn = Some(key_dict_empty_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&empty_table)
    }
}

// SAFETY: `eval_statusline_table` and `key_dict_eval_statusline_get_field` are the
// generated table and lookup for `KeyDict_eval_statusline`.
unsafe impl KeySet for KeyDict_eval_statusline {
    const GET_FIELD: FieldHashfn = Some(key_dict_eval_statusline_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&eval_statusline_table)
    }
}

// SAFETY: `exec_autocmds_table` and `key_dict_exec_autocmds_get_field` are the
// generated table and lookup for `KeyDict_exec_autocmds`.
unsafe impl KeySet for KeyDict_exec_autocmds {
    const GET_FIELD: FieldHashfn = Some(key_dict_exec_autocmds_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&exec_autocmds_table)
    }
}

// SAFETY: `exec_opts_table` and `key_dict_exec_opts_get_field` are the
// generated table and lookup for `KeyDict_exec_opts`.
unsafe impl KeySet for KeyDict_exec_opts {
    const GET_FIELD: FieldHashfn = Some(key_dict_exec_opts_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&exec_opts_table)
    }
}

// SAFETY: `get_autocmds_table` and `key_dict_get_autocmds_get_field` are the
// generated table and lookup for `KeyDict_get_autocmds`.
unsafe impl KeySet for KeyDict_get_autocmds {
    const GET_FIELD: FieldHashfn = Some(key_dict_get_autocmds_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&get_autocmds_table)
    }
}

// SAFETY: `get_commands_table` and `key_dict_get_commands_get_field` are the
// generated table and lookup for `KeyDict_get_commands`.
unsafe impl KeySet for KeyDict_get_commands {
    const GET_FIELD: FieldHashfn = Some(key_dict_get_commands_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&get_commands_table)
    }
}

// SAFETY: `get_extmark_table` and `key_dict_get_extmark_get_field` are the
// generated table and lookup for `KeyDict_get_extmark`.
unsafe impl KeySet for KeyDict_get_extmark {
    const GET_FIELD: FieldHashfn = Some(key_dict_get_extmark_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&get_extmark_table)
    }
}

// SAFETY: `get_extmarks_table` and `key_dict_get_extmarks_get_field` are the
// generated table and lookup for `KeyDict_get_extmarks`.
unsafe impl KeySet for KeyDict_get_extmarks {
    const GET_FIELD: FieldHashfn = Some(key_dict_get_extmarks_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&get_extmarks_table)
    }
}

// SAFETY: `get_highlight_table` and `key_dict_get_highlight_get_field` are the
// generated table and lookup for `KeyDict_get_highlight`.
unsafe impl KeySet for KeyDict_get_highlight {
    const GET_FIELD: FieldHashfn = Some(key_dict_get_highlight_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&get_highlight_table)
    }
}

// SAFETY: `get_ns_table` and `key_dict_get_ns_get_field` are the
// generated table and lookup for `KeyDict_get_ns`.
unsafe impl KeySet for KeyDict_get_ns {
    const GET_FIELD: FieldHashfn = Some(key_dict_get_ns_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&get_ns_table)
    }
}

// SAFETY: `highlight_table` and `key_dict_highlight_get_field` are the
// generated table and lookup for `KeyDict_highlight`.
unsafe impl KeySet for KeyDict_highlight {
    const GET_FIELD: FieldHashfn = Some(key_dict_highlight_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&highlight_table)
    }
}

// SAFETY: `keymap_table` and `key_dict_keymap_get_field` are the
// generated table and lookup for `KeyDict_keymap`.
unsafe impl KeySet for KeyDict_keymap {
    const GET_FIELD: FieldHashfn = Some(key_dict_keymap_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&keymap_table)
    }
}

// SAFETY: `ns_opts_table` and `key_dict_ns_opts_get_field` are the
// generated table and lookup for `KeyDict_ns_opts`.
unsafe impl KeySet for KeyDict_ns_opts {
    const GET_FIELD: FieldHashfn = Some(key_dict_ns_opts_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&ns_opts_table)
    }
}

// SAFETY: `open_term_table` and `key_dict_open_term_get_field` are the
// generated table and lookup for `KeyDict_open_term`.
unsafe impl KeySet for KeyDict_open_term {
    const GET_FIELD: FieldHashfn = Some(key_dict_open_term_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&open_term_table)
    }
}

// SAFETY: `option_table` and `key_dict_option_get_field` are the
// generated table and lookup for `KeyDict_option`.
unsafe impl KeySet for KeyDict_option {
    const GET_FIELD: FieldHashfn = Some(key_dict_option_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&option_table)
    }
}

// SAFETY: `redraw_table` and `key_dict_redraw_get_field` are the
// generated table and lookup for `KeyDict_redraw`.
unsafe impl KeySet for KeyDict_redraw {
    const GET_FIELD: FieldHashfn = Some(key_dict_redraw_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&redraw_table)
    }
}

// SAFETY: `runtime_table` and `key_dict_runtime_get_field` are the
// generated table and lookup for `KeyDict_runtime`.
unsafe impl KeySet for KeyDict_runtime {
    const GET_FIELD: FieldHashfn = Some(key_dict_runtime_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&runtime_table)
    }
}

// SAFETY: `set_decoration_provider_table` and `key_dict_set_decoration_provider_get_field` are the
// generated table and lookup for `KeyDict_set_decoration_provider`.
unsafe impl KeySet for KeyDict_set_decoration_provider {
    const GET_FIELD: FieldHashfn = Some(key_dict_set_decoration_provider_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&set_decoration_provider_table)
    }
}

// SAFETY: `set_extmark_table` and `key_dict_set_extmark_get_field` are the
// generated table and lookup for `KeyDict_set_extmark`.
unsafe impl KeySet for KeyDict_set_extmark {
    const GET_FIELD: FieldHashfn = Some(key_dict_set_extmark_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&set_extmark_table)
    }
}

// SAFETY: `tabpage_config_table` and `key_dict_tabpage_config_get_field` are the
// generated table and lookup for `KeyDict_tabpage_config`.
unsafe impl KeySet for KeyDict_tabpage_config {
    const GET_FIELD: FieldHashfn = Some(key_dict_tabpage_config_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&tabpage_config_table)
    }
}

// SAFETY: `user_command_table` and `key_dict_user_command_get_field` are the
// generated table and lookup for `KeyDict_user_command`.
unsafe impl KeySet for KeyDict_user_command {
    const GET_FIELD: FieldHashfn = Some(key_dict_user_command_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&user_command_table)
    }
}

// SAFETY: `win_config_table` and `key_dict_win_config_get_field` are the
// generated table and lookup for `KeyDict_win_config`.
unsafe impl KeySet for KeyDict_win_config {
    const GET_FIELD: FieldHashfn = Some(key_dict_win_config_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&win_config_table)
    }
}

// SAFETY: `win_text_height_table` and `key_dict_win_text_height_get_field` are the
// generated table and lookup for `KeyDict_win_text_height`.
unsafe impl KeySet for KeyDict_win_text_height {
    const GET_FIELD: FieldHashfn = Some(key_dict_win_text_height_get_field);

    fn table() -> *const KeySetLink {
        keyset_table(&win_text_height_table)
    }
}
