//! Lua bindings for `crate::api::vim`, part 2 of 3.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

/// The Lua binding for `nvim_get_chan_info`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_chan_info(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_integer(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"chan".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_chan_info(LUA_INTERNAL_CALL, arg_1, arena) };
        // SAFETY: as above.
        unsafe { nlua_push_dict(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_chan_info", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_color_by_name`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_color_by_name(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"name".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_color_by_name(arg_1) };
        // SAFETY: as above.
        unsafe { nlua_push_integer(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_color_by_name", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_color_map`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_color_map(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call { arena, .. } = call;
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_color_map(arena) };
        // SAFETY: as above.
        unsafe { nlua_push_dict(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_color_map", 0, 1, convert) }
}

/// The Lua binding for `nvim_get_context`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_context(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        let mut arg_1 = KeyDictArg::<KeyDict_context>::zeroed();
        // SAFETY: as above.
        unsafe { pop_keydict(lstate, &mut arg_1, arena, err, err_param) };
        if err.is_set() {
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_get_context(&raw mut arg_1.dict, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_dict(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_context", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_current_buf`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_current_buf(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, _call: &mut Call) {
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_current_buf() };
        // SAFETY: as above.
        unsafe { nlua_push_handle(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_current_buf", 0, 1, convert) }
}

/// The Lua binding for `nvim_get_current_line`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_current_line(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call { arena, err, .. } = call;
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_get_current_line(arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_string(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_current_line", 0, 1, convert) }
}

/// The Lua binding for `nvim_get_current_tabpage`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_current_tabpage(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, _call: &mut Call) {
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_current_tabpage() };
        // SAFETY: as above.
        unsafe { nlua_push_handle(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_current_tabpage", 0, 1, convert) }
}

/// The Lua binding for `nvim_get_current_win`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_current_win(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, _call: &mut Call) {
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_current_win() };
        // SAFETY: as above.
        unsafe { nlua_push_handle(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_current_win", 0, 1, convert) }
}

/// The Lua binding for `nvim_get_hl`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_hl(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        let mut arg_2 = KeyDictArg::<KeyDict_get_highlight>::zeroed();
        // SAFETY: as above.
        unsafe { pop_keydict(lstate, &mut arg_2, arena, err, err_param) };
        if err.is_set() {
            return;
        }
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_integer(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"ns_id".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_get_hl(arg_1, &raw mut arg_2.dict, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_dict(lstate, ret, PUSH) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_hl", 2, 1, convert) }
}

/// The Lua binding for `nvim_get_hl_id_by_name`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_hl_id_by_name(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"name".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_hl_id_by_name(arg_1) };
        // SAFETY: as above.
        unsafe { nlua_push_integer(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_hl_id_by_name", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_hl_ns`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_hl_ns(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        let mut arg_1 = KeyDictArg::<KeyDict_get_ns>::zeroed();
        // SAFETY: as above.
        unsafe { pop_keydict(lstate, &mut arg_1, arena, err, err_param) };
        if err.is_set() {
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_get_hl_ns(&raw mut arg_1.dict) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_integer(lstate, ret, PUSH) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_hl_ns", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_keymap`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_keymap(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"mode".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_keymap(arg_1, arena) };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_keymap", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_mark`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_mark(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        let mut arg_2 = KeyDictArg::<KeyDict_empty>::zeroed();
        // SAFETY: as above.
        unsafe { pop_keydict(lstate, &mut arg_2, arena, err, err_param) };
        if err.is_set() {
            return;
        }
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"name".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_get_mark(arg_1, &raw mut arg_2.dict, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_mark", 2, 1, convert) }
}

/// The Lua binding for `nvim_get_mode`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_mode(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call { arena, .. } = call;
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_get_mode(arena) };
        // SAFETY: as above.
        unsafe { nlua_push_dict(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch_fast(lstate, 0, 1, convert) }
}

/// The Lua binding for `nvim_get_proc`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_proc(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_integer(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"pid".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let mut ret = match unsafe { nvim_get_proc(arg_1, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_object(lstate, &raw mut ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_proc", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_proc_children`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_proc_children(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_integer(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"pid".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_get_proc_children(arg_1, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_proc_children", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_runtime_file`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_runtime_file(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_2 = unsafe { nlua_pop_boolean(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"all".as_ptr().cast_mut();
            return;
        }
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"name".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_get_runtime_file(arg_1, arg_2, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch_fast(lstate, 2, 1, convert) }
}

/// The Lua binding for `nvim_get_var`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_var(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"name".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let mut ret = match unsafe { nvim_get_var(arg_1, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_object(lstate, &raw mut ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_var", 1, 1, convert) }
}

/// The Lua binding for `nvim_get_vvar`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_get_vvar(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"name".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let mut ret = match unsafe { nvim_get_vvar(arg_1, arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_object(lstate, &raw mut ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_get_vvar", 1, 1, convert) }
}

/// The Lua binding for `nvim_input`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_input(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"keys".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_input(LUA_INTERNAL_CALL, arg_1) };
        // SAFETY: as above.
        unsafe { nlua_push_integer(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch_fast(lstate, 1, 1, convert) }
}

/// The Lua binding for `nvim_input_mouse`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_input_mouse(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call {
            arena,
            err,
            err_param,
        } = call;
        // SAFETY: as above.
        let arg_6 = unsafe { nlua_pop_integer(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"col".as_ptr().cast_mut();
            return;
        }
        // SAFETY: as above.
        let arg_5 = unsafe { nlua_pop_integer(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"row".as_ptr().cast_mut();
            return;
        }
        // SAFETY: as above.
        let arg_4 = unsafe { nlua_pop_integer(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"grid".as_ptr().cast_mut();
            return;
        }
        // SAFETY: as above.
        let arg_3 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"modifier".as_ptr().cast_mut();
            return;
        }
        // SAFETY: as above.
        let arg_2 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"action".as_ptr().cast_mut();
            return;
        }
        // SAFETY: as above.
        let arg_1 = unsafe { nlua_pop_string(lstate, arena, err) };
        if err.is_set() {
            *err_param = c"button".as_ptr().cast_mut();
            return;
        }
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        if let Err(e) = unsafe { nvim_input_mouse(arg_1, arg_2, arg_3, arg_4, arg_5, arg_6) } {
            *err = e;
        }
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch_fast(lstate, 6, 0, convert) }
}

/// The Lua binding for `nvim_list_bufs`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_list_bufs(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call { arena, .. } = call;
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_list_bufs(arena) };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_list_bufs", 0, 1, convert) }
}

/// The Lua binding for `nvim_list_chans`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_list_chans(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call { arena, .. } = call;
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_list_chans(arena) };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_list_chans", 0, 1, convert) }
}

/// The Lua binding for `nvim_list_runtime_paths`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_list_runtime_paths(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call { arena, err, .. } = call;
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = match unsafe { nvim_list_runtime_paths(arena) } {
            Ok(ret) => ret,
            Err(e) => {
                *err = e;
                return;
            }
        };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_list_runtime_paths", 0, 1, convert) }
}

/// The Lua binding for `nvim_list_tabpages`, as a `lua_CFunction`.
///
/// # Safety
/// LuaJIT's contract: `lstate` is the running Lua state, with this
/// binding's arguments on top of its stack and nothing of this frame's
/// below them. The ABI is `C-unwind` because a refused argument ends in
/// `lua_error`, which unwinds through this frame rather than returning.
pub unsafe extern "C-unwind" fn nlua_api_nvim_list_tabpages(lstate: *mut lua_State) -> c_int {
    /// Pop the arguments, call the API function, hand the result back.
    /// Each argument that owns Lua references arms a guard, so every way
    /// out releases exactly what was converted, in declaration order.
    ///
    /// # Safety
    /// The dispatcher's contract, which is what every `unsafe` below rests
    /// on: `lstate` is the running Lua state with this binding's arguments
    /// on top, and `call` is the binding's own.
    unsafe fn convert(lstate: *mut lua_State, call: &mut Call) {
        let Call { arena, .. } = call;
        let _lstate = Restore::of(&active_lstate, lstate);
        // SAFETY: as above; the arguments are this binding's own.
        let ret = unsafe { nvim_list_tabpages(arena) };
        // SAFETY: as above.
        unsafe { nlua_push_array(lstate, ret, PUSH_SPECIAL) };
    }
    // SAFETY: `lstate` is the state Lua called this binding on.
    unsafe { dispatch(lstate, c"nvim_list_tabpages", 0, 1, convert) }
}
