//! `:terminal` and `:lsp`, which both hand a buffer to a
//! process.

#[allow(unused_imports)]
use super::*;

pub(crate) unsafe extern "C" fn ex_terminal(mut eap: *mut exarg_T) {
    let mut ex_cmd: [c_char; 1024] = [0; 1024];
    let mut len: size_t = 0 as size_t;
    if (*cmdmod.ptr()).cmod_tab > 0 as c_int || (*cmdmod.ptr()).cmod_split != 0 as c_int {
        let mut multi_mods: bool = false_0 != 0;
        ex_cmd[0 as c_int as usize] = NUL as c_char;
        len = add_win_cmd_modifiers(
            &raw mut ex_cmd as *mut c_char,
            cmdmod.ptr(),
            &raw mut multi_mods,
        );
        '_c2rust_label: {
            if len < ::core::mem::size_of::<[c_char; 1024]>() {
            } else {
                __assert_fail(
                    b"len < sizeof(ex_cmd)\0".as_ptr() as *const c_char,
                    b"src/nvim/ex_docmd.rs\0".as_ptr() as *const c_char,
                    8298 as c_uint,
                    b"void ex_terminal(exarg_T *)\0".as_ptr() as *const c_char,
                );
            }
        };
        let mut result: c_int = snprintf(
            (&raw mut ex_cmd as *mut c_char).offset(len as isize),
            ::core::mem::size_of::<[c_char; 1024]>().wrapping_sub(len),
            b" new\0".as_ptr() as *const c_char,
        );
        '_c2rust_label_0: {
            if result > 0 as c_int {
            } else {
                __assert_fail(
                    b"result > 0\0".as_ptr() as *const c_char,
                    b"src/nvim/ex_docmd.rs\0".as_ptr() as *const c_char,
                    8300 as c_uint,
                    b"void ex_terminal(exarg_T *)\0".as_ptr() as *const c_char,
                );
            }
        };
        len = len.wrapping_add(result as size_t);
    } else {
        let mut result_0: c_int = snprintf(
            &raw mut ex_cmd as *mut c_char,
            ::core::mem::size_of::<[c_char; 1024]>(),
            b"enew%s\0".as_ptr() as *const c_char,
            if (*eap).forceit != 0 {
                b"!\0".as_ptr() as *const c_char
            } else {
                b"\0".as_ptr() as *const c_char
            },
        );
        '_c2rust_label_1: {
            if result_0 > 0 as c_int {
            } else {
                __assert_fail(
                    b"result > 0\0".as_ptr() as *const c_char,
                    b"src/nvim/ex_docmd.rs\0".as_ptr() as *const c_char,
                    8304 as c_uint,
                    b"void ex_terminal(exarg_T *)\0".as_ptr() as *const c_char,
                );
            }
        };
        len = len.wrapping_add(result_0 as size_t);
    }
    '_c2rust_label_2: {
        if len < ::core::mem::size_of::<[c_char; 1024]>() {
        } else {
            __assert_fail(
                b"len < sizeof(ex_cmd)\0".as_ptr() as *const c_char,
                b"src/nvim/ex_docmd.rs\0".as_ptr() as *const c_char,
                8308 as c_uint,
                b"void ex_terminal(exarg_T *)\0".as_ptr() as *const c_char,
            );
        }
    };
    if *(*eap).arg as c_int != NUL {
        let mut name: *mut c_char =
            vim_strsave_escaped((*eap).arg, b"\"\\\0".as_ptr() as *const c_char);
        snprintf(
            (&raw mut ex_cmd as *mut c_char).offset(len as isize),
            ::core::mem::size_of::<[c_char; 1024]>().wrapping_sub(len),
            b" | call jobstart(\"%s\",{'term':v:true})\0".as_ptr() as *const c_char,
            name,
        );
        xfree(name as *mut c_void);
    } else {
        if *p_sh.get() as c_int == NUL {
            emsg(gettext(&raw const e_shellempty as *const c_char));
            return;
        }
        let mut argv: *mut *mut c_char =
            shell_build_argv(::core::ptr::null::<c_char>(), ::core::ptr::null::<c_char>());
        let mut p: *mut *mut c_char = argv;
        let mut tempstring: [c_char; 512] = [0; 512];
        let mut shell_argv: [c_char; 512] = [
            0 as c_char,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];
        while !(*p).is_null() {
            let mut escaped: *mut c_char =
                vim_strsave_escaped(*p, b"\"\\\0".as_ptr() as *const c_char);
            snprintf(
                &raw mut tempstring as *mut c_char,
                ::core::mem::size_of::<[c_char; 512]>(),
                b",\"%s\"\0".as_ptr() as *const c_char,
                escaped,
            );
            xfree(escaped as *mut c_void);
            xstrlcat(
                &raw mut shell_argv as *mut c_char,
                &raw mut tempstring as *mut c_char,
                ::core::mem::size_of::<[c_char; 512]>(),
            );
            p = p.offset(1);
        }
        shell_free_argv(argv);
        snprintf(
            (&raw mut ex_cmd as *mut c_char).offset(len as isize),
            ::core::mem::size_of::<[c_char; 1024]>().wrapping_sub(len),
            b" | call jobstart([%s], {'term':v:true})\0".as_ptr() as *const c_char,
            (&raw mut shell_argv as *mut c_char).offset(1 as c_int as isize),
        );
    }
    do_cmdline_cmd(&raw mut ex_cmd as *mut c_char);
}

pub(crate) unsafe extern "C" fn ex_lsp(mut eap: *mut exarg_T) {
    let mut err: Error = Error {
        type_0: kErrorTypeNone,
        msg: ::core::ptr::null_mut::<c_char>(),
    };
    let mut args: Array = Array {
        size: 0 as size_t,
        capacity: 0 as size_t,
        items: ::core::ptr::null_mut::<Object>(),
    };
    let mut args__items: [Object; 1] = [Object {
        type_0: kObjectTypeNil,
        data: C2Rust_Unnamed_14 { boolean: false },
    }; 1];
    args.capacity = 1 as size_t;
    args.items = &raw mut args__items as *mut Object;
    let c2rust_fresh22 = args.size;
    args.size = args.size.wrapping_add(1);
    *args.items.offset(c2rust_fresh22 as isize) = object {
        type_0: kObjectTypeString,
        data: C2Rust_Unnamed_14 {
            string: cstr_as_string((*eap).arg),
        },
    };
    nlua_exec(
        String_0 {
            data: b"require'vim._core.ex_cmd'.ex_lsp(...)\0".as_ptr() as *const c_char
                as *mut c_char,
            size: ::core::mem::size_of::<[c_char; 38]>().wrapping_sub(1 as size_t),
        },
        ::core::ptr::null::<c_char>(),
        args,
        kRetNilBool,
        ::core::ptr::null_mut::<Arena>(),
        &raw mut err,
    );
    if err.type_0 as c_int != kErrorTypeNone as c_int {
        emsg_multiline(
            err.msg,
            b"lua_error\0".as_ptr() as *const c_char,
            HLF_E as c_int,
            true_0 != 0,
        );
    }
    api_clear_error(&raw mut err);
}
