//! Lua bindings for `crate::src::nvim::api::ui`.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

pub unsafe extern "C-unwind" fn nlua_api_nvim_ui_send(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_ui_send".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"content".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_ui_send(LUA_INTERNAL_CALL, arg_1, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}
