//! Lua bindings for `crate::src::nvim::api::vim`, part 3 of 3.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

pub unsafe extern "C-unwind" fn nlua_api_nvim_list_uis(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 0 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 0 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_list_uis".as_ptr(),
                );
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_list_uis(&raw mut arena);
            nlua_push_Array(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_list_wins(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 0 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 0 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_list_wins".as_ptr(),
                );
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_list_wins(&raw mut arena);
            nlua_push_Array(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_load_context(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_load_context".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_Dict(lstate, false, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"dict".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let mut ret = nvim_load_context(arg_1, &raw mut err);
            nlua_push_Object(lstate, &raw mut ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_open_term(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_open_term".as_ptr(),
                );
            }
            if textlock.get() != 0 || expr_map_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    &raw const e_textlock,
                );
                break 'done;
            }
            let mut arg_2: KeyDict_open_term = core::mem::zeroed();
            'free_arg_2: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_2).cast(),
                    Some(KeyDict_open_term_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_2;
                }
                let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"buf".as_ptr().cast_mut();
                    break 'free_arg_2;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                let ret = nvim_open_term(arg_1, &raw mut arg_2, &raw mut err);
                nlua_push_Integer(lstate, ret, PUSH_SPECIAL);
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_2).cast(), open_term_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_paste(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 3 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 3 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_paste".as_ptr(),
                );
            }
            if textlock.get() != 0 || expr_map_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    &raw const e_textlock,
                );
                break 'done;
            }
            let arg_3 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"phase".as_ptr().cast_mut();
                break 'done;
            }
            let arg_2 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"crlf".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"data".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_paste(
                LUA_INTERNAL_CALL,
                arg_1,
                arg_2,
                arg_3,
                &raw mut arena,
                &raw mut err,
            );
            nlua_push_Boolean(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_put(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 4 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 4 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_put".as_ptr(),
                );
            }
            if textlock.get() != 0 || expr_map_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    &raw const e_textlock,
                );
                break 'done;
            }
            let arg_4 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"follow".as_ptr().cast_mut();
                break 'done;
            }
            let arg_3 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"after".as_ptr().cast_mut();
                break 'done;
            }
            let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"type".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_Array(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"lines".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_put(arg_1, arg_2, arg_3, arg_4, &raw mut arena, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_replace_termcodes(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 4 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 4 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_replace_termcodes".as_ptr(),
                );
            }
            let arg_4 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"special".as_ptr().cast_mut();
                break 'done;
            }
            let arg_3 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"do_lt".as_ptr().cast_mut();
                break 'done;
            }
            let arg_2 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"from_part".as_ptr().cast_mut();
                break 'done;
            }
            let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"str".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_replace_termcodes(arg_1, arg_2, arg_3, arg_4);
            nlua_push_String(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
            api_free_string(ret);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_select_popupmenu_item(
    lstate: *mut lua_State,
) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 4 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 4 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_select_popupmenu_item".as_ptr(),
                );
            }
            let mut arg_4: KeyDict_empty = core::mem::zeroed();
            'free_arg_4: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_4).cast(),
                    Some(KeyDict_empty_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_4;
                }
                let arg_3 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"finish".as_ptr().cast_mut();
                    break 'free_arg_4;
                }
                let arg_2 = nlua_pop_Boolean(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"insert".as_ptr().cast_mut();
                    break 'free_arg_4;
                }
                let arg_1 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"item".as_ptr().cast_mut();
                    break 'free_arg_4;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                nvim_select_popupmenu_item(arg_1, arg_2, arg_3, &raw mut arg_4, &raw mut err);
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_4).cast(), empty_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_current_buf(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_current_buf".as_ptr(),
                );
            }
            if text_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    get_text_locked_msg(),
                );
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"buf".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_set_current_buf(arg_1, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_current_dir(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_current_dir".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"dir".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_set_current_dir(arg_1, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_current_line(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_current_line".as_ptr(),
                );
            }
            if textlock.get() != 0 || expr_map_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    &raw const e_textlock,
                );
                break 'done;
            }
            let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"line".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_set_current_line(arg_1, &raw mut arena, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_current_tabpage(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_current_tabpage".as_ptr(),
                );
            }
            if text_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    get_text_locked_msg(),
                );
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"tabpage".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_set_current_tabpage(arg_1, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_current_win(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_current_win".as_ptr(),
                );
            }
            if text_locked() {
                api_set_error(
                    &raw mut err,
                    kErrorTypeException,
                    c"%s".as_ptr(),
                    get_text_locked_msg(),
                );
                break 'done;
            }
            let arg_1 = nlua_pop_handle(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"win".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_set_current_win(arg_1, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_hl(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 3 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 3 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_hl".as_ptr(),
                );
            }
            let mut arg_3: KeyDict_highlight = core::mem::zeroed();
            'free_arg_3: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_3).cast(),
                    Some(KeyDict_highlight_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_3;
                }
                let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"name".as_ptr().cast_mut();
                    break 'free_arg_3;
                }
                let arg_1 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"ns_id".as_ptr().cast_mut();
                    break 'free_arg_3;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                nvim_set_hl(
                    LUA_INTERNAL_CALL,
                    arg_1,
                    arg_2,
                    &raw mut arg_3,
                    &raw mut err,
                );
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_3).cast(), highlight_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_hl_ns(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_hl_ns".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"ns_id".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_set_hl_ns(arg_1, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_hl_ns_fast(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            let arg_1 = nlua_pop_Integer(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"ns_id".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            nvim_set_hl_ns_fast(arg_1, &raw mut err);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_keymap(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 4 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 4 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_keymap".as_ptr(),
                );
            }
            let mut arg_4: KeyDict_keymap = core::mem::zeroed();
            'free_arg_4: {
                nlua_pop_keydict(
                    lstate,
                    (&raw mut arg_4).cast(),
                    Some(KeyDict_keymap_get_field),
                    &raw mut err_param,
                    &raw mut arena,
                    &raw mut err,
                );
                if err.type_0 != kErrorTypeNone {
                    break 'free_arg_4;
                }
                let arg_3 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"rhs".as_ptr().cast_mut();
                    break 'free_arg_4;
                }
                let arg_2 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"lhs".as_ptr().cast_mut();
                    break 'free_arg_4;
                }
                let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"mode".as_ptr().cast_mut();
                    break 'free_arg_4;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                nvim_set_keymap(
                    LUA_INTERNAL_CALL,
                    arg_1,
                    arg_2,
                    arg_3,
                    &raw mut arg_4,
                    &raw mut err,
                );
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_keydict((&raw mut arg_4).cast(), keymap_table.ptr().cast());
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_var(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_var".as_ptr(),
                );
            }
            let arg_2: Object;
            'free_arg_2: {
                arg_2 = nlua_pop_Object(lstate, true, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"value".as_ptr().cast_mut();
                    break 'done;
                }
                let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"name".as_ptr().cast_mut();
                    break 'free_arg_2;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                nvim_set_var(arg_1, arg_2, &raw mut err);
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_object(arg_2);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_set_vvar(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 2 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 2 arguments".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_set_vvar".as_ptr(),
                );
            }
            let arg_2: Object;
            'free_arg_2: {
                arg_2 = nlua_pop_Object(lstate, true, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"value".as_ptr().cast_mut();
                    break 'done;
                }
                let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
                if err.type_0 != kErrorTypeNone {
                    err_param = c"name".as_ptr().cast_mut();
                    break 'free_arg_2;
                }
                let saved_lstate = active_lstate.get();
                active_lstate.set(lstate);
                nvim_set_vvar(arg_1, arg_2, &raw mut err);
                active_lstate.set(saved_lstate);
            }
            api_luarefs_free_object(arg_2);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        0
    }
}

pub unsafe extern "C-unwind" fn nlua_api_nvim_strwidth(lstate: *mut lua_State) -> c_int {
    unsafe {
        let mut err = ERROR_INIT;
        let mut arena = ARENA_EMPTY;
        let mut err_param: *mut c_char = ptr::null_mut();
        'done: {
            if lua_gettop(lstate) != 1 {
                api_set_error(
                    &raw mut err,
                    kErrorTypeValidation,
                    c"Expected 1 argument".as_ptr(),
                );
                break 'done;
            }
            if !nlua_is_deferred_safe() {
                return luaL_error(
                    lstate,
                    (&raw const e_fast_api_disabled).cast(),
                    c"nvim_strwidth".as_ptr(),
                );
            }
            let arg_1 = nlua_pop_String(lstate, &raw mut arena, &raw mut err);
            if err.type_0 != kErrorTypeNone {
                err_param = c"text".as_ptr().cast_mut();
                break 'done;
            }
            let saved_lstate = active_lstate.get();
            active_lstate.set(lstate);
            let ret = nvim_strwidth(arg_1, &raw mut err);
            nlua_push_Integer(lstate, ret, PUSH_SPECIAL);
            active_lstate.set(saved_lstate);
        }
        if finish(lstate, &raw mut arena, &raw mut err, err_param) {
            return lua_error(lstate);
        }
        1
    }
}
