//! The option table.
//!
//! GENERATED by tools/apigen from `crate::src::nvim::options.lua` — the same
//! metadata upstream's `src/gen/gen_options.lua` consumed. Do not edit; run
//! `just apigen` (`just apigen --check` fails on drift).
//!
//! Everything an option *is* lives here: its name and abbreviation, its type
//! and scopes, the flags that drive redraws and parsing, the variable holding
//! its value, the callbacks that validate a change, and its default.
//! `crate::src::nvim::option` keeps everything an option *does*.
//!
//! Two orderings are load-bearing. The table is in `:set all` order, and a
//! row's position is its `OptIndex` — the handle every caller passes around.
//! Within each scope, a row's position is its `GlobalOptIndex` /
//! `WinOptIndex` / `BufOptIndex`, which is how a window or buffer finds its
//! own copy of the value.

#![forbid(unsafe_code)]

mod flags;
mod index;
mod lookup;
mod table_1;
mod table_2;
mod table_3;
mod table_4;
mod table_5;
mod values;

pub use self::flags::*;
pub use self::index::*;
pub use self::lookup::*;
pub use self::values::*;

use core::ffi::{CStr, c_char, c_int, c_uint, c_void};
use core::mem::offset_of;
use core::ptr;

use crate::src::nvim::ex_docmd::did_set_findfunc;
use crate::src::nvim::ex_getln::did_set_cedit;
use crate::src::nvim::global_cell::GlobalCell;
use crate::src::nvim::insexpand::{did_set_completefunc, did_set_omnifunc, did_set_thesaurusfunc};
use crate::src::nvim::main::{
    bkc_flags, bo_flags, cb_flags, cmp_flags, cot_flags, dy_flags, fdo_flags, jop_flags, p_ac,
    p_acd, p_acl, p_act, p_ai, p_ambw, p_ar, p_ari, p_arshape, p_aw, p_awa, p_bdir, p_bex, p_bg,
    p_bh, p_bin, p_bk, p_bkc, p_bl, p_bo, p_bomb, p_breakat, p_bs, p_bsk, p_bt, p_busy, p_cb,
    p_ccv, p_cdh, p_cdpath, p_cedit, p_cfu, p_ch, p_channel, p_chi, p_ci, p_cia, p_cin, p_cink,
    p_cino, p_cinsd, p_cinw, p_cmp, p_cms, p_columns, p_com, p_confirm, p_cot, p_cpo, p_cpt, p_cto,
    p_cwh, p_debug, p_deco, p_def, p_dex, p_dg, p_dia, p_dict, p_dip, p_dir, p_dy, p_ea, p_ead,
    p_eb, p_ef, p_efm, p_ei, p_emoji, p_enc, p_eof, p_eol, p_ep, p_et, p_exrc, p_fcl, p_fcs,
    p_fdls, p_fdo, p_fenc, p_fencs, p_fex, p_ff, p_ffs, p_ffu, p_fic, p_fixeol, p_flp, p_fo, p_fp,
    p_fs, p_ft, p_gd, p_gefm, p_gp, p_guicursor, p_guifont, p_guifontwide, p_hf, p_hh, p_hi, p_hid,
    p_hl, p_hlg, p_hls, p_ic, p_icm, p_icon, p_iconstring, p_iminsert, p_imsearch, p_inc, p_inde,
    p_indk, p_inex, p_inf, p_is, p_isf, p_isi, p_isk, p_isp, p_jop, p_js, p_keymap, p_km, p_kp,
    p_langmap, p_lcs, p_lines, p_linespace, p_lisp, p_lispwords, p_lm, p_lnr, p_lop, p_lpl, p_lrm,
    p_ls, p_lz, p_ma, p_magic, p_mat, p_mco, p_mef, p_menc, p_mfd, p_mh, p_mis, p_ml, p_mle, p_mls,
    p_mmd, p_mmp, p_mod, p_mopt, p_more, p_mouse, p_mousef, p_mousem, p_mousemev, p_mousescroll,
    p_mouset, p_mp, p_mps, p_msc, p_msm, p_nf, p_ofu, p_opfunc, p_para, p_paste, p_path, p_pb,
    p_pex, p_ph, p_pi, p_pm, p_pmw, p_pp, p_pumborder, p_pvh, p_pw, p_pyx, p_qe, p_qftf, p_rdb,
    p_rdt, p_re, p_report, p_ri, p_ro, p_rtp, p_ru, p_ruf, p_sb, p_sbo, p_sbr, p_sc, p_scbk, p_scs,
    p_sections, p_secure, p_sel, p_sft, p_sh, p_shada, p_shadafile, p_shcf, p_shm, p_shq, p_si,
    p_siso, p_sj, p_slm, p_sloc, p_sm, p_smc, p_smd, p_so, p_sol, p_sp, p_spc, p_spf, p_spk, p_spl,
    p_spo, p_spr, p_sps, p_sr, p_srr, p_ss, p_ssop, p_sta, p_stal, p_stl, p_stmp, p_sts, p_su,
    p_sua, p_sw, p_swb, p_swf, p_sxe, p_sxq, p_syn, p_tags, p_tal, p_tbidi, p_tbs, p_tc, p_tcl,
    p_termsync, p_tf, p_tfu, p_tgc, p_tgst, p_timeout, p_title, p_titlelen, p_titleold,
    p_titlestring, p_tl, p_tm, p_to, p_tpf, p_tpm, p_tr, p_ts, p_tsr, p_tsrfu, p_ttimeout, p_ttm,
    p_tw, p_uc, p_udf, p_udir, p_ul, p_ur, p_ut, p_vb, p_vdir, p_ve, p_verbose, p_vop, p_vsts,
    p_vts, p_wa, p_wak, p_warn, p_wb, p_wbr, p_wc, p_wcm, p_wd, p_wh, p_wic, p_wig, p_wim,
    p_winborder, p_window, p_wiw, p_wm, p_wmh, p_wmnu, p_wmw, p_wop, p_write, p_ws, p_ww,
    rdb_flags, ssop_flags, swb_flags, tc_flags, tcl_flags, tpf_flags, ve_flags, vop_flags,
    wop_flags,
};
use crate::src::nvim::mapping::did_set_langmap;
use crate::src::nvim::ops::did_set_operatorfunc;
use crate::src::nvim::option::{
    B_IMODE_NONE, B_IMODE_USE_INSERT, CPO_VIM, CTRL_F_STR, DFLT_COLS, DFLT_EFM, DFLT_ERRORFILE,
    DFLT_FO_VIM, DFLT_GFN, DFLT_GREPFORMAT, DFLT_HELPFILE, DFLT_ROWS, ENC_DFLT, HIGHLIGHT_INIT,
    LISPWORD_VALUE, MAX_MCO, TAB, did_set_arabic, did_set_autochdir, did_set_binary,
    did_set_buflisted, did_set_cmdheight, did_set_diff, did_set_eof_eol_fixeol_bomb,
    did_set_equalalways, did_set_foldlevel, did_set_foldminlines, did_set_foldnestmax,
    did_set_helpheight, did_set_hlsearch, did_set_ignorecase, did_set_iminsert,
    did_set_langnoremap, did_set_langremap, did_set_laststatus, did_set_lines_or_columns,
    did_set_lisp, did_set_modifiable, did_set_modified, did_set_number_relativenumber,
    did_set_numberwidth, did_set_paste, did_set_previewwindow, did_set_pumblend, did_set_readonly,
    did_set_scrollback, did_set_scrollbind, did_set_shiftwidth_tabstop, did_set_showtabline,
    did_set_smoothscroll, did_set_spell, did_set_swapfile, did_set_textwidth, did_set_title_icon,
    did_set_titlelen, did_set_undofile, did_set_undolevels, did_set_updatecount, did_set_wildchar,
    did_set_winblend, did_set_window, did_set_winheight, did_set_winwidth, did_set_wrap,
    did_set_xhistory, kOptFlagColon, kOptFlagComma, kOptFlagCurswant, kOptFlagExpand,
    kOptFlagFlagList, kOptFlagFunc, kOptFlagHLOnly, kOptFlagMLE, kOptFlagNDname, kOptFlagNFname,
    kOptFlagNoDefExp, kOptFlagNoDefault, kOptFlagNoDup, kOptFlagNoGlob, kOptFlagNoMkrc,
    kOptFlagOneComma, kOptFlagPriMkrc, kOptFlagRedrAll, kOptFlagRedrBuf, kOptFlagRedrStat,
    kOptFlagRedrTabl, kOptFlagRedrWin, kOptFlagSecure, kOptFlagUIOption, kOptScopeBuf,
    kOptScopeGlobal, kOptScopeWin, kOptValTypeBoolean, kOptValTypeNumber, kOptValTypeString,
    p_vfile,
};
use crate::src::nvim::optionstr::{
    did_set_ambiwidth, did_set_background, did_set_backspace, did_set_backupcopy,
    did_set_backupext_or_patchmode, did_set_breakat, did_set_breakindentopt, did_set_bufhidden,
    did_set_buftype, did_set_chars_option, did_set_cinoptions, did_set_colorcolumn,
    did_set_comments, did_set_commentstring, did_set_complete, did_set_completeitemalign,
    did_set_completeopt, did_set_concealcursor, did_set_cpoptions, did_set_cursorlineopt,
    did_set_diffanchors, did_set_diffopt, did_set_display, did_set_emoji, did_set_encoding,
    did_set_eventignore, did_set_fileformat, did_set_filetype_or_syntax, did_set_foldexpr,
    did_set_foldignore, did_set_foldmarker, did_set_foldmethod, did_set_formatoptions,
    did_set_guicursor, did_set_helpfile, did_set_helplang, did_set_highlight, did_set_iconstring,
    did_set_inccommand, did_set_iskeyword, did_set_isopt, did_set_keymap, did_set_keymodel,
    did_set_lispoptions, did_set_matchpairs, did_set_messagesopt, did_set_mkspellmem,
    did_set_mouse, did_set_mousescroll, did_set_optexpr, did_set_pumborder, did_set_rulerformat,
    did_set_selection, did_set_sessionoptions, did_set_shada, did_set_shellpipe_redir,
    did_set_shortmess, did_set_showbreak, did_set_showcmdloc, did_set_signcolumn,
    did_set_spellcapcheck, did_set_spellfile, did_set_spelllang, did_set_spelloptions,
    did_set_spellsuggest, did_set_statuscolumn, did_set_statusline, did_set_str_generic,
    did_set_tabline, did_set_tagcase, did_set_titlestring, did_set_varsofttabstop,
    did_set_vartabstop, did_set_verbosefile, did_set_virtualedit, did_set_whichwrap,
    did_set_wildmode, did_set_winbar, did_set_winborder, did_set_winhighlight,
    expand_set_chars_option, expand_set_concealcursor, expand_set_cpoptions, expand_set_diffopt,
    expand_set_encoding, expand_set_eventignore, expand_set_formatoptions, expand_set_mouse,
    expand_set_shortmess, expand_set_str_generic, expand_set_whichwrap, expand_set_winhighlight,
};
use crate::src::nvim::quickfix::did_set_quickfixtextfunc;
use crate::src::nvim::runtime::did_set_runtimepackpath;
use crate::src::nvim::tag::did_set_tagfunc;
use crate::src::nvim::types::types::{kFalse, kTrue};
use crate::src::nvim::types::{
    OptIndex, OptInt, OptScopeFlags, OptVal, OptValData, String_0, sctx_T, ssize_t, vimoption_T,
};
use crate::src::nvim::window::{did_set_winminheight, did_set_winminwidth};

/// `scope_flags` bits.
const GLOBAL: OptScopeFlags = 1 << kOptScopeGlobal;
const WIN: OptScopeFlags = 1 << kOptScopeWin;
const BUF: OptScopeFlags = 1 << kOptScopeBuf;

/// A row with every field at rest: a global-scoped, mutable, flagless
/// boolean that defaults to false and belongs to no scope. Each row below
/// fills in what it needs and takes the rest from here.
const BLANK: vimoption_T = vimoption_T {
    fullname: ptr::null_mut(),
    shortname: ptr::null_mut(),
    flags: 0,
    type_0: kOptValTypeBoolean,
    scope_flags: 0,
    var: ptr::null_mut(),
    flags_var: ptr::null_mut(),
    scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptInvalid),
    immutable: false,
    values: ptr::null_mut(),
    values_len: 0,
    opt_did_set_cb: None,
    opt_expand_cb: None,
    def_val: boolean(false),
    script_ctx: sctx_T {
        sc_sid: 0,
        sc_seq: 0,
        sc_lnum: 0,
        sc_chan: 0,
    },
};

const fn name(s: &'static CStr) -> *mut c_char {
    s.as_ptr().cast_mut()
}

const fn scope_idx(global: GlobalOptIndex, win: WinOptIndex, buf: BufOptIndex) -> [ssize_t; 3] {
    [global as ssize_t, win as ssize_t, buf as ssize_t]
}

const fn boolean(value: bool) -> OptVal {
    OptVal {
        type_0: kOptValTypeBoolean,
        data: OptValData {
            boolean: if value { kTrue } else { kFalse },
        },
    }
}

const fn number(value: OptInt) -> OptVal {
    OptVal {
        type_0: kOptValTypeNumber,
        data: OptValData { number: value },
    }
}

const fn string(value: &'static CStr) -> OptVal {
    OptVal {
        type_0: kOptValTypeString,
        data: OptValData {
            string: String_0 {
                data: value.as_ptr().cast_mut(),
                size: value.count_bytes(),
            },
        },
    }
}

/// A default that a C constant supplies — `macros(...)` in options.lua. The
/// constant is a NUL-terminated `char[]`, so its length counts the NUL.
const fn macro_string(value: &'static [c_char]) -> OptVal {
    OptVal {
        type_0: kOptValTypeString,
        data: OptValData {
            string: String_0 {
                data: value.as_ptr().cast_mut(),
                size: value.len() - 1,
            },
        },
    }
}

/// An immutable option has nowhere to keep a value, so it reads its own
/// default in place. Nothing writes through the pointer: `set_option`
/// refuses the option before it gets that far.
///
/// This is the address of `options[index].def_val.data`, computed rather
/// than projected: the table is still being built when the rows call this,
/// and pointer arithmetic needs only the static's address, not its contents.
const fn own_default(index: usize) -> *mut c_void {
    options
        .as_raw()
        .cast::<vimoption_T>()
        .wrapping_add(index)
        .wrapping_byte_add(offset_of!(vimoption_T, def_val) + offset_of!(OptVal, data))
        .cast()
}

/// Copy one generated part into the table under construction.
const fn fill(table: &mut [vimoption_T], base: usize, part: &[vimoption_T]) -> usize {
    let mut i = 0;
    while i < part.len() {
        table[base + i] = part[i];
        i += 1;
    }
    base + part.len()
}

/// Every option there is. A row's position is its `OptIndex`.
pub static options: GlobalCell<[vimoption_T; kOptCount as usize]> = GlobalCell::new(table());

/// The table, spliced together from the generated parts.
const fn table() -> [vimoption_T; kOptCount as usize] {
    let mut table = [BLANK; kOptCount as usize];
    let mut base = 0;
    base = fill(&mut table, base, &table_1::PART);
    base = fill(&mut table, base, &table_2::PART);
    base = fill(&mut table, base, &table_3::PART);
    base = fill(&mut table, base, &table_4::PART);
    base = fill(&mut table, base, &table_5::PART);
    assert!(base == kOptCount as usize);
    table
}
