//! A run of the option table's rows.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![forbid(unsafe_code)]

// A chunk may hold nothing that needs the parent's support code.
#[allow(unused_imports)]
use super::*;

/// This file's run of the option table, spliced in by the parent.
pub(super) const PART: [vimoption_T; 81] = [
    // 'jumpoptions'
    vimoption_T {
        fullname: name(c"jumpoptions"),
        shortname: name(c"jop"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptJumpoptions, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_jop),
        flags_var: Some(&jop_flags),
        values: accepted(&opt_jop_values),
        values_len: 3,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"clean"),
        ..BLANK
    },
    // 'keymap'
    vimoption_T {
        fullname: name(c"keymap"),
        shortname: name(c"kmp"),
        flags: kOptFlagRedrStat | kOptFlagRedrBuf | kOptFlagNFname | kOptFlagPriMkrc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptKeymap),
        var: OptVar::String(&p_keymap),
        opt_did_set_cb: Some(did_set_keymap),
        def_val: string(c""),
        ..BLANK
    },
    // 'keymodel'
    vimoption_T {
        fullname: name(c"keymodel"),
        shortname: name(c"km"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptKeymodel, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_km),
        values: accepted(&opt_km_values),
        values_len: 2,
        opt_did_set_cb: Some(did_set_keymodel),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'keywordprg'
    vimoption_T {
        fullname: name(c"keywordprg"),
        shortname: name(c"kp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptKeywordprg, kWinOptInvalid, kBufOptKeywordprg),
        var: OptVar::String(&p_kp),
        def_val: string(c":Man"),
        ..BLANK
    },
    // 'langmap'
    vimoption_T {
        fullname: name(c"langmap"),
        shortname: name(c"lmap"),
        flags: kOptFlagOneComma | kOptFlagSecure | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangmap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_langmap),
        opt_did_set_cb: Some(did_set_langmap),
        def_val: string(c""),
        ..BLANK
    },
    // 'langmenu'
    vimoption_T {
        fullname: name(c"langmenu"),
        shortname: name(c"lm"),
        flags: kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangmenu, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_lm),
        def_val: string(c""),
        ..BLANK
    },
    // 'langnoremap'
    vimoption_T {
        fullname: name(c"langnoremap"),
        shortname: name(c"lnr"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangnoremap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_lnr),
        opt_did_set_cb: Some(did_set_langnoremap),
        def_val: boolean(true),
        ..BLANK
    },
    // 'langremap'
    vimoption_T {
        fullname: name(c"langremap"),
        shortname: name(c"lrm"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangremap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_lrm),
        opt_did_set_cb: Some(did_set_langremap),
        ..BLANK
    },
    // 'laststatus'
    vimoption_T {
        fullname: name(c"laststatus"),
        shortname: name(c"ls"),
        flags: kOptFlagRedrAll,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLaststatus, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_ls),
        opt_did_set_cb: Some(did_set_laststatus),
        def_val: number(2),
        ..BLANK
    },
    // 'lazyredraw'
    vimoption_T {
        fullname: name(c"lazyredraw"),
        shortname: name(c"lz"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLazyredraw, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_lz),
        ..BLANK
    },
    // 'lhistory'
    vimoption_T {
        fullname: name(c"lhistory"),
        shortname: name(c"lhi"),
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptLhistory, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_xhistory),
        def_val: number(10),
        ..BLANK
    },
    // 'linebreak'
    vimoption_T {
        fullname: name(c"linebreak"),
        shortname: name(c"lbr"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptLinebreak, kBufOptInvalid),
        ..BLANK
    },
    // 'lines'
    vimoption_T {
        fullname: name(c"lines"),
        flags: kOptFlagNoMkrc,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLines, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_lines),
        opt_did_set_cb: Some(did_set_lines_or_columns),
        def_val: number(DFLT_ROWS as OptInt),
        ..BLANK
    },
    // 'linespace'
    vimoption_T {
        fullname: name(c"linespace"),
        shortname: name(c"lsp"),
        flags: kOptFlagUIOption,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLinespace, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_linespace),
        def_val: number(0),
        ..BLANK
    },
    // 'lisp'
    vimoption_T {
        fullname: name(c"lisp"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptLisp),
        var: OptVar::Boolean(&p_lisp),
        opt_did_set_cb: Some(did_set_lisp),
        ..BLANK
    },
    // 'lispoptions'
    vimoption_T {
        fullname: name(c"lispoptions"),
        shortname: name(c"lop"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptLispoptions),
        var: OptVar::String(&p_lop),
        values: accepted(&opt_lop_values),
        values_len: 2,
        opt_did_set_cb: Some(did_set_lispoptions),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'lispwords'
    vimoption_T {
        fullname: name(c"lispwords"),
        shortname: name(c"lw"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptLispwords, kWinOptInvalid, kBufOptLispwords),
        var: OptVar::String(&p_lispwords),
        def_val: macro_string(&LISPWORD_VALUE),
        ..BLANK
    },
    // 'list'
    vimoption_T {
        fullname: name(c"list"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptList, kBufOptInvalid),
        ..BLANK
    },
    // 'listchars'
    vimoption_T {
        fullname: name(c"listchars"),
        shortname: name(c"lcs"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagRedrWin | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | WIN,
        scope_idx: scope_idx(kGlobalOptListchars, kWinOptListchars, kBufOptInvalid),
        var: OptVar::String(&p_lcs),
        opt_did_set_cb: Some(did_set_chars_option),
        opt_expand_cb: Some(expand_set_chars_option),
        def_val: string(c"tab:> ,trail:-,nbsp:+"),
        ..BLANK
    },
    // 'loadplugins'
    vimoption_T {
        fullname: name(c"loadplugins"),
        shortname: name(c"lpl"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLoadplugins, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_lpl),
        def_val: boolean(true),
        ..BLANK
    },
    // 'magic'
    vimoption_T {
        fullname: name(c"magic"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMagic, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_magic),
        def_val: boolean(true),
        ..BLANK
    },
    // 'makeef'
    vimoption_T {
        fullname: name(c"makeef"),
        shortname: name(c"mef"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMakeef, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_mef),
        def_val: string(c""),
        ..BLANK
    },
    // 'makeencoding'
    vimoption_T {
        fullname: name(c"makeencoding"),
        shortname: name(c"menc"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptMakeencoding, kWinOptInvalid, kBufOptMakeencoding),
        var: OptVar::String(&p_menc),
        opt_did_set_cb: Some(did_set_encoding),
        opt_expand_cb: Some(expand_set_encoding),
        def_val: string(c""),
        ..BLANK
    },
    // 'makeprg'
    vimoption_T {
        fullname: name(c"makeprg"),
        shortname: name(c"mp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptMakeprg, kWinOptInvalid, kBufOptMakeprg),
        var: OptVar::String(&p_mp),
        def_val: string(c"make"),
        ..BLANK
    },
    // 'matchpairs'
    vimoption_T {
        fullname: name(c"matchpairs"),
        shortname: name(c"mps"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptMatchpairs),
        var: OptVar::String(&p_mps),
        opt_did_set_cb: Some(did_set_matchpairs),
        def_val: string(c"(:),{:},[:]"),
        ..BLANK
    },
    // 'matchtime'
    vimoption_T {
        fullname: name(c"matchtime"),
        shortname: name(c"mat"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMatchtime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mat),
        def_val: number(5),
        ..BLANK
    },
    // 'maxcombine'
    vimoption_T {
        fullname: name(c"maxcombine"),
        shortname: name(c"mco"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxcombine, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mco),
        def_val: number(MAX_MCO as OptInt),
        ..BLANK
    },
    // 'maxfuncdepth'
    vimoption_T {
        fullname: name(c"maxfuncdepth"),
        shortname: name(c"mfd"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxfuncdepth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mfd),
        def_val: number(100),
        ..BLANK
    },
    // 'maxmapdepth'
    vimoption_T {
        fullname: name(c"maxmapdepth"),
        shortname: name(c"mmd"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxmapdepth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mmd),
        def_val: number(1000),
        ..BLANK
    },
    // 'maxmempattern'
    vimoption_T {
        fullname: name(c"maxmempattern"),
        shortname: name(c"mmp"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxmempattern, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mmp),
        def_val: number(1000),
        ..BLANK
    },
    // 'maxsearchcount'
    vimoption_T {
        fullname: name(c"maxsearchcount"),
        shortname: name(c"msc"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxsearchcount, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_msc),
        def_val: number(999),
        ..BLANK
    },
    // 'menuitems'
    vimoption_T {
        fullname: name(c"menuitems"),
        shortname: name(c"mis"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMenuitems, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mis),
        def_val: number(25),
        ..BLANK
    },
    // 'messagesopt'
    vimoption_T {
        fullname: name(c"messagesopt"),
        shortname: name(c"mopt"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMessagesopt, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_mopt),
        values: accepted(&opt_mopt_values),
        values_len: 4,
        opt_did_set_cb: Some(did_set_messagesopt),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"hit-enter,history:500,progress:c"),
        ..BLANK
    },
    // 'mkspellmem'
    vimoption_T {
        fullname: name(c"mkspellmem"),
        shortname: name(c"msm"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMkspellmem, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_msm),
        opt_did_set_cb: Some(did_set_mkspellmem),
        def_val: string(c"460000,2000,500"),
        ..BLANK
    },
    // 'modeline'
    vimoption_T {
        fullname: name(c"modeline"),
        shortname: name(c"ml"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModeline),
        var: OptVar::Boolean(&p_ml),
        def_val: boolean(true),
        ..BLANK
    },
    // 'modelineexpr'
    vimoption_T {
        fullname: name(c"modelineexpr"),
        shortname: name(c"mle"),
        flags: kOptFlagSecure,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptModelineexpr, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_mle),
        ..BLANK
    },
    // 'modelines'
    vimoption_T {
        fullname: name(c"modelines"),
        shortname: name(c"mls"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptModelines, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mls),
        def_val: number(5),
        ..BLANK
    },
    // 'modifiable'
    vimoption_T {
        fullname: name(c"modifiable"),
        shortname: name(c"ma"),
        flags: kOptFlagNoGlob,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModifiable),
        var: OptVar::Boolean(&p_ma),
        opt_did_set_cb: Some(did_set_modifiable),
        def_val: boolean(true),
        ..BLANK
    },
    // 'modified'
    vimoption_T {
        fullname: name(c"modified"),
        shortname: name(c"mod"),
        flags: kOptFlagRedrStat | kOptFlagNoMkrc,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModified),
        var: OptVar::Boolean(&p_mod),
        opt_did_set_cb: Some(did_set_modified),
        ..BLANK
    },
    // 'more'
    vimoption_T {
        fullname: name(c"more"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMore, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_more),
        def_val: boolean(true),
        ..BLANK
    },
    // 'mouse'
    vimoption_T {
        fullname: name(c"mouse"),
        flags: kOptFlagFlagList,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMouse, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_mouse),
        opt_did_set_cb: Some(did_set_mouse),
        opt_expand_cb: Some(expand_set_mouse),
        def_val: string(c"nvi"),
        ..BLANK
    },
    // 'mousefocus'
    vimoption_T {
        fullname: name(c"mousefocus"),
        shortname: name(c"mousef"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousefocus, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_mousef),
        ..BLANK
    },
    // 'mousehide'
    vimoption_T {
        fullname: name(c"mousehide"),
        shortname: name(c"mh"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousehide, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_mh),
        def_val: boolean(true),
        ..BLANK
    },
    // 'mousemodel'
    vimoption_T {
        fullname: name(c"mousemodel"),
        shortname: name(c"mousem"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousemodel, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_mousem),
        values: accepted(&opt_mousem_values),
        values_len: 3,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"popup_setpos"),
        ..BLANK
    },
    // 'mousemoveevent'
    vimoption_T {
        fullname: name(c"mousemoveevent"),
        shortname: name(c"mousemev"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousemoveevent, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_mousemev),
        ..BLANK
    },
    // 'mousescroll'
    vimoption_T {
        fullname: name(c"mousescroll"),
        flags: kOptFlagComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousescroll, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_mousescroll),
        values: accepted(&opt_mousescroll_values),
        values_len: 2,
        opt_did_set_cb: Some(did_set_mousescroll),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"ver:3,hor:6"),
        ..BLANK
    },
    // 'mouseshape'
    vimoption_T {
        fullname: name(c"mouseshape"),
        shortname: name(c"mouses"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMouseshape, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'mousetime'
    vimoption_T {
        fullname: name(c"mousetime"),
        shortname: name(c"mouset"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousetime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_mouset),
        def_val: number(500),
        ..BLANK
    },
    // 'nrformats'
    vimoption_T {
        fullname: name(c"nrformats"),
        shortname: name(c"nf"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptNrformats),
        var: OptVar::String(&p_nf),
        values: accepted(&opt_nf_values),
        values_len: 6,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"bin,hex"),
        ..BLANK
    },
    // 'number'
    vimoption_T {
        fullname: name(c"number"),
        shortname: name(c"nu"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptNumber, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_number_relativenumber),
        ..BLANK
    },
    // 'numberwidth'
    vimoption_T {
        fullname: name(c"numberwidth"),
        shortname: name(c"nuw"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptNumberwidth, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_numberwidth),
        def_val: number(4),
        ..BLANK
    },
    // 'omnifunc'
    vimoption_T {
        fullname: name(c"omnifunc"),
        shortname: name(c"ofu"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptOmnifunc),
        var: OptVar::String(&p_ofu),
        opt_did_set_cb: Some(did_set_omnifunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'opendevice'
    vimoption_T {
        fullname: name(c"opendevice"),
        shortname: name(c"odev"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptOpendevice, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'operatorfunc'
    vimoption_T {
        fullname: name(c"operatorfunc"),
        shortname: name(c"opfunc"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptOperatorfunc, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_opfunc),
        opt_did_set_cb: Some(did_set_operatorfunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'packpath'
    vimoption_T {
        fullname: name(c"packpath"),
        shortname: name(c"pp"),
        flags: kOptFlagOneComma | kOptFlagExpand | kOptFlagSecure | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPackpath, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_pp),
        opt_did_set_cb: Some(did_set_runtimepackpath),
        def_val: string(c""),
        ..BLANK
    },
    // 'paragraphs'
    vimoption_T {
        fullname: name(c"paragraphs"),
        shortname: name(c"para"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptParagraphs, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_para),
        def_val: string(c"IPLPPPQPP TPHPLIPpLpItpplpipbp"),
        ..BLANK
    },
    // 'paste'
    vimoption_T {
        fullname: name(c"paste"),
        flags: kOptFlagPriMkrc,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPaste, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_paste),
        opt_did_set_cb: Some(did_set_paste),
        ..BLANK
    },
    // 'pastetoggle'
    vimoption_T {
        fullname: name(c"pastetoggle"),
        shortname: name(c"pt"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPastetoggle, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'patchexpr'
    vimoption_T {
        fullname: name(c"patchexpr"),
        shortname: name(c"pex"),
        flags: kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPatchexpr, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_pex),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'patchmode'
    vimoption_T {
        fullname: name(c"patchmode"),
        shortname: name(c"pm"),
        flags: kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPatchmode, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_pm),
        opt_did_set_cb: Some(did_set_backupext_or_patchmode),
        def_val: string(c""),
        ..BLANK
    },
    // 'path'
    vimoption_T {
        fullname: name(c"path"),
        shortname: name(c"pa"),
        flags: kOptFlagComma | kOptFlagExpand | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptPath, kWinOptInvalid, kBufOptPath),
        var: OptVar::String(&p_path),
        def_val: string(c".,,"),
        ..BLANK
    },
    // 'preserveindent'
    vimoption_T {
        fullname: name(c"preserveindent"),
        shortname: name(c"pi"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptPreserveindent),
        var: OptVar::Boolean(&p_pi),
        ..BLANK
    },
    // 'previewheight'
    vimoption_T {
        fullname: name(c"previewheight"),
        shortname: name(c"pvh"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPreviewheight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_pvh),
        def_val: number(12),
        ..BLANK
    },
    // 'previewwindow'
    vimoption_T {
        fullname: name(c"previewwindow"),
        shortname: name(c"pvw"),
        flags: kOptFlagRedrStat | kOptFlagNoGlob,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptPreviewwindow, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_previewwindow),
        ..BLANK
    },
    // 'prompt'
    vimoption_T {
        fullname: name(c"prompt"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPrompt, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: boolean(true),
        ..BLANK
    },
    // 'pumblend'
    vimoption_T {
        fullname: name(c"pumblend"),
        shortname: name(c"pb"),
        flags: kOptFlagUIOption,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumblend, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_pb),
        opt_did_set_cb: Some(did_set_pumblend),
        def_val: number(0),
        ..BLANK
    },
    // 'pumborder'
    vimoption_T {
        fullname: name(c"pumborder"),
        flags: kOptFlagOneComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumborder, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_pumborder),
        values: accepted(&opt_pumborder_values),
        values_len: 8,
        opt_did_set_cb: Some(did_set_pumborder),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'pumheight'
    vimoption_T {
        fullname: name(c"pumheight"),
        shortname: name(c"ph"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumheight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_ph),
        def_val: number(0),
        ..BLANK
    },
    // 'pummaxwidth'
    vimoption_T {
        fullname: name(c"pummaxwidth"),
        shortname: name(c"pmw"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPummaxwidth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_pmw),
        def_val: number(0),
        ..BLANK
    },
    // 'pumwidth'
    vimoption_T {
        fullname: name(c"pumwidth"),
        shortname: name(c"pw"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumwidth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_pw),
        def_val: number(15),
        ..BLANK
    },
    // 'pyxversion'
    vimoption_T {
        fullname: name(c"pyxversion"),
        shortname: name(c"pyx"),
        flags: kOptFlagSecure,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPyxversion, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_pyx),
        def_val: number(3),
        ..BLANK
    },
    // 'quickfixtextfunc'
    vimoption_T {
        fullname: name(c"quickfixtextfunc"),
        shortname: name(c"qftf"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptQuickfixtextfunc, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_qftf),
        opt_did_set_cb: Some(did_set_quickfixtextfunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'quoteescape'
    vimoption_T {
        fullname: name(c"quoteescape"),
        shortname: name(c"qe"),
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptQuoteescape),
        var: OptVar::String(&p_qe),
        def_val: string(c"\\"),
        ..BLANK
    },
    // 'readonly'
    vimoption_T {
        fullname: name(c"readonly"),
        shortname: name(c"ro"),
        flags: kOptFlagRedrStat | kOptFlagNoGlob,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptReadonly),
        var: OptVar::Boolean(&p_ro),
        opt_did_set_cb: Some(did_set_readonly),
        ..BLANK
    },
    // 'redrawdebug'
    vimoption_T {
        fullname: name(c"redrawdebug"),
        shortname: name(c"rdb"),
        flags: kOptFlagOneComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRedrawdebug, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(&p_rdb),
        flags_var: Some(&rdb_flags),
        values: accepted(&opt_rdb_values),
        values_len: 6,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'redrawtime'
    vimoption_T {
        fullname: name(c"redrawtime"),
        shortname: name(c"rdt"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRedrawtime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_rdt),
        def_val: number(2000),
        ..BLANK
    },
    // 'regexpengine'
    vimoption_T {
        fullname: name(c"regexpengine"),
        shortname: name(c"re"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRegexpengine, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_re),
        def_val: number(0),
        ..BLANK
    },
    // 'relativenumber'
    vimoption_T {
        fullname: name(c"relativenumber"),
        shortname: name(c"rnu"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptRelativenumber, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_number_relativenumber),
        ..BLANK
    },
    // 'remap'
    vimoption_T {
        fullname: name(c"remap"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRemap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: boolean(true),
        ..BLANK
    },
    // 'report'
    vimoption_T {
        fullname: name(c"report"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptReport, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(&p_report),
        def_val: number(2),
        ..BLANK
    },
    // 'revins'
    vimoption_T {
        fullname: name(c"revins"),
        shortname: name(c"ri"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRevins, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(&p_ri),
        ..BLANK
    },
];
