//! A run of the option table's rows.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![forbid(unsafe_code)]

// A chunk may hold nothing that needs the parent's support code.
#[allow(unused_imports)]
use super::*;

/// This file's run of the option table, spliced in by the parent.
pub(super) const PART: [vimoption_T; 78] = [
    // 'aleph'
    vimoption_T {
        fullname: name(c"aleph"),
        shortname: name(c"al"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptAleph, kWinOptInvalid, kBufOptInvalid),
        var: own_default(0),
        immutable: true,
        def_val: number(224),
        ..BLANK
    },
    // 'allowrevins'
    vimoption_T {
        fullname: name(c"allowrevins"),
        shortname: name(c"ari"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptAllowrevins, kWinOptInvalid, kBufOptInvalid),
        var: p_ari.as_raw().cast(),
        ..BLANK
    },
    // 'ambiwidth'
    vimoption_T {
        fullname: name(c"ambiwidth"),
        shortname: name(c"ambw"),
        flags: kOptFlagRedrAll | kOptFlagUIOption,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptAmbiwidth, kWinOptInvalid, kBufOptInvalid),
        var: p_ambw.as_raw().cast(),
        values: opt_ambw_values.as_raw().cast(),
        values_len: 2,
        opt_did_set_cb: Some(did_set_ambiwidth),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"single"),
        ..BLANK
    },
    // 'arabic'
    vimoption_T {
        fullname: name(c"arabic"),
        shortname: name(c"arab"),
        flags: kOptFlagCurswant,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptArabic, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_arabic),
        ..BLANK
    },
    // 'arabicshape'
    vimoption_T {
        fullname: name(c"arabicshape"),
        shortname: name(c"arshape"),
        flags: kOptFlagRedrAll | kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptArabicshape, kWinOptInvalid, kBufOptInvalid),
        var: p_arshape.as_raw().cast(),
        def_val: boolean(true),
        ..BLANK
    },
    // 'autochdir'
    vimoption_T {
        fullname: name(c"autochdir"),
        shortname: name(c"acd"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptAutochdir, kWinOptInvalid, kBufOptInvalid),
        var: p_acd.as_raw().cast(),
        opt_did_set_cb: Some(did_set_autochdir),
        ..BLANK
    },
    // 'autocomplete'
    vimoption_T {
        fullname: name(c"autocomplete"),
        shortname: name(c"ac"),
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptAutocomplete, kWinOptInvalid, kBufOptAutocomplete),
        var: p_ac.as_raw().cast(),
        ..BLANK
    },
    // 'autocompletedelay'
    vimoption_T {
        fullname: name(c"autocompletedelay"),
        shortname: name(c"acl"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptAutocompletedelay, kWinOptInvalid, kBufOptInvalid),
        var: p_acl.as_raw().cast(),
        def_val: number(0),
        ..BLANK
    },
    // 'autocompletetimeout'
    vimoption_T {
        fullname: name(c"autocompletetimeout"),
        shortname: name(c"act"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(
            kGlobalOptAutocompletetimeout,
            kWinOptInvalid,
            kBufOptInvalid,
        ),
        var: p_act.as_raw().cast(),
        def_val: number(80),
        ..BLANK
    },
    // 'autoindent'
    vimoption_T {
        fullname: name(c"autoindent"),
        shortname: name(c"ai"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptAutoindent),
        var: p_ai.as_raw().cast(),
        def_val: boolean(true),
        ..BLANK
    },
    // 'autoread'
    vimoption_T {
        fullname: name(c"autoread"),
        shortname: name(c"ar"),
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptAutoread, kWinOptInvalid, kBufOptAutoread),
        var: p_ar.as_raw().cast(),
        def_val: boolean(true),
        ..BLANK
    },
    // 'autowrite'
    vimoption_T {
        fullname: name(c"autowrite"),
        shortname: name(c"aw"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptAutowrite, kWinOptInvalid, kBufOptInvalid),
        var: p_aw.as_raw().cast(),
        ..BLANK
    },
    // 'autowriteall'
    vimoption_T {
        fullname: name(c"autowriteall"),
        shortname: name(c"awa"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptAutowriteall, kWinOptInvalid, kBufOptInvalid),
        var: p_awa.as_raw().cast(),
        ..BLANK
    },
    // 'background'
    vimoption_T {
        fullname: name(c"background"),
        shortname: name(c"bg"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBackground, kWinOptInvalid, kBufOptInvalid),
        var: p_bg.as_raw().cast(),
        values: opt_bg_values.as_raw().cast(),
        values_len: 2,
        opt_did_set_cb: Some(did_set_background),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"dark"),
        ..BLANK
    },
    // 'backspace'
    vimoption_T {
        fullname: name(c"backspace"),
        shortname: name(c"bs"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBackspace, kWinOptInvalid, kBufOptInvalid),
        var: p_bs.as_raw().cast(),
        values: opt_bs_values.as_raw().cast(),
        values_len: 4,
        opt_did_set_cb: Some(did_set_backspace),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"indent,eol,start"),
        ..BLANK
    },
    // 'backup'
    vimoption_T {
        fullname: name(c"backup"),
        shortname: name(c"bk"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBackup, kWinOptInvalid, kBufOptInvalid),
        var: p_bk.as_raw().cast(),
        ..BLANK
    },
    // 'backupcopy'
    vimoption_T {
        fullname: name(c"backupcopy"),
        shortname: name(c"bkc"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptBackupcopy, kWinOptInvalid, kBufOptBackupcopy),
        var: p_bkc.as_raw().cast(),
        flags_var: bkc_flags.as_raw(),
        values: opt_bkc_values.as_raw().cast(),
        values_len: 5,
        opt_did_set_cb: Some(did_set_backupcopy),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"auto"),
        ..BLANK
    },
    // 'backupdir'
    vimoption_T {
        fullname: name(c"backupdir"),
        shortname: name(c"bdir"),
        flags: kOptFlagOneComma
            | kOptFlagExpand
            | kOptFlagNoDefExp
            | kOptFlagSecure
            | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBackupdir, kWinOptInvalid, kBufOptInvalid),
        var: p_bdir.as_raw().cast(),
        def_val: string(c""),
        ..BLANK
    },
    // 'backupext'
    vimoption_T {
        fullname: name(c"backupext"),
        shortname: name(c"bex"),
        flags: kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBackupext, kWinOptInvalid, kBufOptInvalid),
        var: p_bex.as_raw().cast(),
        opt_did_set_cb: Some(did_set_backupext_or_patchmode),
        def_val: string(c"~"),
        ..BLANK
    },
    // 'backupskip'
    vimoption_T {
        fullname: name(c"backupskip"),
        shortname: name(c"bsk"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBackupskip, kWinOptInvalid, kBufOptInvalid),
        var: p_bsk.as_raw().cast(),
        def_val: string(c""),
        ..BLANK
    },
    // 'belloff'
    vimoption_T {
        fullname: name(c"belloff"),
        shortname: name(c"bo"),
        flags: kOptFlagComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBelloff, kWinOptInvalid, kBufOptInvalid),
        var: p_bo.as_raw().cast(),
        flags_var: bo_flags.as_raw(),
        values: opt_bo_values.as_raw().cast(),
        values_len: 20,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"all"),
        ..BLANK
    },
    // 'binary'
    vimoption_T {
        fullname: name(c"binary"),
        shortname: name(c"bin"),
        flags: kOptFlagRedrStat,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptBinary),
        var: p_bin.as_raw().cast(),
        opt_did_set_cb: Some(did_set_binary),
        ..BLANK
    },
    // 'bomb'
    vimoption_T {
        fullname: name(c"bomb"),
        flags: kOptFlagRedrStat | kOptFlagNoMkrc,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptBomb),
        var: p_bomb.as_raw().cast(),
        opt_did_set_cb: Some(did_set_eof_eol_fixeol_bomb),
        ..BLANK
    },
    // 'breakat'
    vimoption_T {
        fullname: name(c"breakat"),
        shortname: name(c"brk"),
        flags: kOptFlagFlagList | kOptFlagRedrAll,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBreakat, kWinOptInvalid, kBufOptInvalid),
        var: p_breakat.as_raw().cast(),
        opt_did_set_cb: Some(did_set_breakat),
        def_val: string(c" \t!@*-+;:,./?"),
        ..BLANK
    },
    // 'breakindent'
    vimoption_T {
        fullname: name(c"breakindent"),
        shortname: name(c"bri"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptBreakindent, kBufOptInvalid),
        ..BLANK
    },
    // 'breakindentopt'
    vimoption_T {
        fullname: name(c"breakindentopt"),
        shortname: name(c"briopt"),
        flags: kOptFlagOneComma | kOptFlagRedrBuf | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptBreakindentopt, kBufOptInvalid),
        values: opt_briopt_values.as_raw().cast(),
        values_len: 5,
        opt_did_set_cb: Some(did_set_breakindentopt),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'browsedir'
    vimoption_T {
        fullname: name(c"browsedir"),
        shortname: name(c"bsdir"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptBrowsedir, kWinOptInvalid, kBufOptInvalid),
        var: own_default(26),
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'bufhidden'
    vimoption_T {
        fullname: name(c"bufhidden"),
        shortname: name(c"bh"),
        flags: kOptFlagNoGlob,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptBufhidden),
        var: p_bh.as_raw().cast(),
        values: opt_bh_values.as_raw().cast(),
        values_len: 5,
        opt_did_set_cb: Some(did_set_bufhidden),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'buflisted'
    vimoption_T {
        fullname: name(c"buflisted"),
        shortname: name(c"bl"),
        flags: kOptFlagNoGlob,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptBuflisted),
        var: p_bl.as_raw().cast(),
        opt_did_set_cb: Some(did_set_buflisted),
        def_val: boolean(true),
        ..BLANK
    },
    // 'buftype'
    vimoption_T {
        fullname: name(c"buftype"),
        shortname: name(c"bt"),
        flags: kOptFlagNoGlob,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptBuftype),
        var: p_bt.as_raw().cast(),
        values: opt_bt_values.as_raw().cast(),
        values_len: 8,
        opt_did_set_cb: Some(did_set_buftype),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'busy'
    vimoption_T {
        fullname: name(c"busy"),
        flags: kOptFlagRedrStat | kOptFlagNoGlob,
        type_0: kOptValTypeNumber,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptBusy),
        var: p_busy.as_raw().cast(),
        def_val: number(0),
        ..BLANK
    },
    // 'casemap'
    vimoption_T {
        fullname: name(c"casemap"),
        shortname: name(c"cmp"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCasemap, kWinOptInvalid, kBufOptInvalid),
        var: p_cmp.as_raw().cast(),
        flags_var: cmp_flags.as_raw(),
        values: opt_cmp_values.as_raw().cast(),
        values_len: 2,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"internal,keepascii"),
        ..BLANK
    },
    // 'cdhome'
    vimoption_T {
        fullname: name(c"cdhome"),
        shortname: name(c"cdh"),
        flags: kOptFlagSecure,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCdhome, kWinOptInvalid, kBufOptInvalid),
        var: p_cdh.as_raw().cast(),
        def_val: boolean(true),
        ..BLANK
    },
    // 'cdpath'
    vimoption_T {
        fullname: name(c"cdpath"),
        shortname: name(c"cd"),
        flags: kOptFlagComma | kOptFlagExpand | kOptFlagSecure | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCdpath, kWinOptInvalid, kBufOptInvalid),
        var: p_cdpath.as_raw().cast(),
        def_val: string(c",,"),
        ..BLANK
    },
    // 'cedit'
    vimoption_T {
        fullname: name(c"cedit"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCedit, kWinOptInvalid, kBufOptInvalid),
        var: p_cedit.as_raw().cast(),
        opt_did_set_cb: Some(did_set_cedit),
        def_val: macro_string(&CTRL_F_STR),
        ..BLANK
    },
    // 'channel'
    vimoption_T {
        fullname: name(c"channel"),
        flags: kOptFlagNoDefault | kOptFlagNoMkrc,
        type_0: kOptValTypeNumber,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptChannel),
        var: p_channel.as_raw().cast(),
        def_val: number(0),
        ..BLANK
    },
    // 'charconvert'
    vimoption_T {
        fullname: name(c"charconvert"),
        shortname: name(c"ccv"),
        flags: kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCharconvert, kWinOptInvalid, kBufOptInvalid),
        var: p_ccv.as_raw().cast(),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'chistory'
    vimoption_T {
        fullname: name(c"chistory"),
        shortname: name(c"chi"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptChistory, kWinOptInvalid, kBufOptInvalid),
        var: p_chi.as_raw().cast(),
        opt_did_set_cb: Some(did_set_xhistory),
        def_val: number(10),
        ..BLANK
    },
    // 'cindent'
    vimoption_T {
        fullname: name(c"cindent"),
        shortname: name(c"cin"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCindent),
        var: p_cin.as_raw().cast(),
        ..BLANK
    },
    // 'cinkeys'
    vimoption_T {
        fullname: name(c"cinkeys"),
        shortname: name(c"cink"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCinkeys),
        var: p_cink.as_raw().cast(),
        def_val: string(c"0{,0},0),0],:,0#,!^F,o,O,e"),
        ..BLANK
    },
    // 'cinoptions'
    vimoption_T {
        fullname: name(c"cinoptions"),
        shortname: name(c"cino"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCinoptions),
        var: p_cino.as_raw().cast(),
        opt_did_set_cb: Some(did_set_cinoptions),
        def_val: string(c""),
        ..BLANK
    },
    // 'cinscopedecls'
    vimoption_T {
        fullname: name(c"cinscopedecls"),
        shortname: name(c"cinsd"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCinscopedecls),
        var: p_cinsd.as_raw().cast(),
        def_val: string(c"public,protected,private"),
        ..BLANK
    },
    // 'cinwords'
    vimoption_T {
        fullname: name(c"cinwords"),
        shortname: name(c"cinw"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCinwords),
        var: p_cinw.as_raw().cast(),
        def_val: string(c"if,else,while,do,for,switch"),
        ..BLANK
    },
    // 'clipboard'
    vimoption_T {
        fullname: name(c"clipboard"),
        shortname: name(c"cb"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptClipboard, kWinOptInvalid, kBufOptInvalid),
        var: p_cb.as_raw().cast(),
        flags_var: cb_flags.as_raw(),
        values: opt_cb_values.as_raw().cast(),
        values_len: 2,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'cmdheight'
    vimoption_T {
        fullname: name(c"cmdheight"),
        shortname: name(c"ch"),
        flags: kOptFlagRedrAll,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCmdheight, kWinOptInvalid, kBufOptInvalid),
        var: p_ch.as_raw().cast(),
        opt_did_set_cb: Some(did_set_cmdheight),
        def_val: number(1),
        ..BLANK
    },
    // 'cmdwinheight'
    vimoption_T {
        fullname: name(c"cmdwinheight"),
        shortname: name(c"cwh"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCmdwinheight, kWinOptInvalid, kBufOptInvalid),
        var: p_cwh.as_raw().cast(),
        def_val: number(7),
        ..BLANK
    },
    // 'colorcolumn'
    vimoption_T {
        fullname: name(c"colorcolumn"),
        shortname: name(c"cc"),
        flags: kOptFlagOneComma | kOptFlagRedrWin | kOptFlagHLOnly | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptColorcolumn, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_colorcolumn),
        def_val: string(c""),
        ..BLANK
    },
    // 'columns'
    vimoption_T {
        fullname: name(c"columns"),
        shortname: name(c"co"),
        flags: kOptFlagNoMkrc,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptColumns, kWinOptInvalid, kBufOptInvalid),
        var: p_columns.as_raw().cast(),
        opt_did_set_cb: Some(did_set_lines_or_columns),
        def_val: number(DFLT_COLS as OptInt),
        ..BLANK
    },
    // 'comments'
    vimoption_T {
        fullname: name(c"comments"),
        shortname: name(c"com"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptComments),
        var: p_com.as_raw().cast(),
        opt_did_set_cb: Some(did_set_comments),
        def_val: string(c"s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-,fb:•"),
        ..BLANK
    },
    // 'commentstring'
    vimoption_T {
        fullname: name(c"commentstring"),
        shortname: name(c"cms"),
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCommentstring),
        var: p_cms.as_raw().cast(),
        opt_did_set_cb: Some(did_set_commentstring),
        def_val: string(c""),
        ..BLANK
    },
    // 'compatible'
    vimoption_T {
        fullname: name(c"compatible"),
        shortname: name(c"cp"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCompatible, kWinOptInvalid, kBufOptInvalid),
        var: own_default(50),
        immutable: true,
        ..BLANK
    },
    // 'complete'
    vimoption_T {
        fullname: name(c"complete"),
        shortname: name(c"cpt"),
        flags: kOptFlagOneComma | kOptFlagNoDup | kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptComplete),
        var: p_cpt.as_raw().cast(),
        values: opt_cpt_values.as_raw().cast(),
        values_len: 15,
        opt_did_set_cb: Some(did_set_complete),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c".,w,b,u,t"),
        ..BLANK
    },
    // 'completefunc'
    vimoption_T {
        fullname: name(c"completefunc"),
        shortname: name(c"cfu"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCompletefunc),
        var: p_cfu.as_raw().cast(),
        opt_did_set_cb: Some(did_set_completefunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'completeitemalign'
    vimoption_T {
        fullname: name(c"completeitemalign"),
        shortname: name(c"cia"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCompleteitemalign, kWinOptInvalid, kBufOptInvalid),
        var: p_cia.as_raw().cast(),
        opt_did_set_cb: Some(did_set_completeitemalign),
        def_val: string(c"abbr,kind,menu"),
        ..BLANK
    },
    // 'completeopt'
    vimoption_T {
        fullname: name(c"completeopt"),
        shortname: name(c"cot"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptCompleteopt, kWinOptInvalid, kBufOptCompleteopt),
        var: p_cot.as_raw().cast(),
        flags_var: cot_flags.as_raw(),
        values: opt_cot_values.as_raw().cast(),
        values_len: 11,
        opt_did_set_cb: Some(did_set_completeopt),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"menu,popup"),
        ..BLANK
    },
    // 'completeslash'
    vimoption_T {
        fullname: name(c"completeslash"),
        shortname: name(c"csl"),
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCompleteslash),
        var: own_default(55),
        immutable: true,
        values: opt_csl_values.as_raw().cast(),
        values_len: 3,
        def_val: string(c""),
        ..BLANK
    },
    // 'completetimeout'
    vimoption_T {
        fullname: name(c"completetimeout"),
        shortname: name(c"cto"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCompletetimeout, kWinOptInvalid, kBufOptInvalid),
        var: p_cto.as_raw().cast(),
        def_val: number(0),
        ..BLANK
    },
    // 'concealcursor'
    vimoption_T {
        fullname: name(c"concealcursor"),
        shortname: name(c"cocu"),
        flags: kOptFlagFlagList | kOptFlagRedrWin,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptConcealcursor, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_concealcursor),
        opt_expand_cb: Some(expand_set_concealcursor),
        def_val: string(c""),
        ..BLANK
    },
    // 'conceallevel'
    vimoption_T {
        fullname: name(c"conceallevel"),
        shortname: name(c"cole"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptConceallevel, kBufOptInvalid),
        def_val: number(0),
        ..BLANK
    },
    // 'confirm'
    vimoption_T {
        fullname: name(c"confirm"),
        shortname: name(c"cf"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptConfirm, kWinOptInvalid, kBufOptInvalid),
        var: p_confirm.as_raw().cast(),
        ..BLANK
    },
    // 'copyindent'
    vimoption_T {
        fullname: name(c"copyindent"),
        shortname: name(c"ci"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptCopyindent),
        var: p_ci.as_raw().cast(),
        ..BLANK
    },
    // 'cpoptions'
    vimoption_T {
        fullname: name(c"cpoptions"),
        shortname: name(c"cpo"),
        flags: kOptFlagFlagList | kOptFlagRedrAll,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptCpoptions, kWinOptInvalid, kBufOptInvalid),
        var: p_cpo.as_raw().cast(),
        opt_did_set_cb: Some(did_set_cpoptions),
        opt_expand_cb: Some(expand_set_cpoptions),
        def_val: macro_string(&CPO_VIM),
        ..BLANK
    },
    // 'cursorbind'
    vimoption_T {
        fullname: name(c"cursorbind"),
        shortname: name(c"crb"),
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptCursorbind, kBufOptInvalid),
        ..BLANK
    },
    // 'cursorcolumn'
    vimoption_T {
        fullname: name(c"cursorcolumn"),
        shortname: name(c"cuc"),
        flags: kOptFlagRedrWin | kOptFlagHLOnly,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptCursorcolumn, kBufOptInvalid),
        ..BLANK
    },
    // 'cursorline'
    vimoption_T {
        fullname: name(c"cursorline"),
        shortname: name(c"cul"),
        flags: kOptFlagRedrWin | kOptFlagHLOnly,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptCursorline, kBufOptInvalid),
        ..BLANK
    },
    // 'cursorlineopt'
    vimoption_T {
        fullname: name(c"cursorlineopt"),
        shortname: name(c"culopt"),
        flags: kOptFlagOneComma | kOptFlagRedrWin | kOptFlagHLOnly | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptCursorlineopt, kBufOptInvalid),
        values: opt_culopt_values.as_raw().cast(),
        values_len: 4,
        opt_did_set_cb: Some(did_set_cursorlineopt),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"both"),
        ..BLANK
    },
    // 'debug'
    vimoption_T {
        fullname: name(c"debug"),
        flags: kOptFlagComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptDebug, kWinOptInvalid, kBufOptInvalid),
        var: p_debug.as_raw().cast(),
        values: opt_debug_values.as_raw().cast(),
        values_len: 3,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'define'
    vimoption_T {
        fullname: name(c"define"),
        shortname: name(c"def"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptDefine, kWinOptInvalid, kBufOptDefine),
        var: p_def.as_raw().cast(),
        def_val: string(c""),
        ..BLANK
    },
    // 'delcombine'
    vimoption_T {
        fullname: name(c"delcombine"),
        shortname: name(c"deco"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptDelcombine, kWinOptInvalid, kBufOptInvalid),
        var: p_deco.as_raw().cast(),
        ..BLANK
    },
    // 'dictionary'
    vimoption_T {
        fullname: name(c"dictionary"),
        shortname: name(c"dict"),
        flags: kOptFlagOneComma | kOptFlagExpand | kOptFlagNDname | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptDictionary, kWinOptInvalid, kBufOptDictionary),
        var: p_dict.as_raw().cast(),
        def_val: string(c""),
        ..BLANK
    },
    // 'diff'
    vimoption_T {
        fullname: name(c"diff"),
        flags: kOptFlagRedrWin | kOptFlagNoGlob,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptDiff, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_diff),
        ..BLANK
    },
    // 'diffanchors'
    vimoption_T {
        fullname: name(c"diffanchors"),
        shortname: name(c"dia"),
        flags: kOptFlagOneComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptDiffanchors, kWinOptInvalid, kBufOptDiffanchors),
        var: p_dia.as_raw().cast(),
        opt_did_set_cb: Some(did_set_diffanchors),
        def_val: string(c""),
        ..BLANK
    },
    // 'diffexpr'
    vimoption_T {
        fullname: name(c"diffexpr"),
        shortname: name(c"dex"),
        flags: kOptFlagCurswant | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptDiffexpr, kWinOptInvalid, kBufOptInvalid),
        var: p_dex.as_raw().cast(),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'diffopt'
    vimoption_T {
        fullname: name(c"diffopt"),
        shortname: name(c"dip"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagRedrWin | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptDiffopt, kWinOptInvalid, kBufOptInvalid),
        var: p_dip.as_raw().cast(),
        values: opt_dip_values.as_raw().cast(),
        values_len: 19,
        opt_did_set_cb: Some(did_set_diffopt),
        opt_expand_cb: Some(expand_set_diffopt),
        def_val: string(c"internal,filler,closeoff,indent-heuristic,inline:char,linematch:40"),
        ..BLANK
    },
    // 'digraph'
    vimoption_T {
        fullname: name(c"digraph"),
        shortname: name(c"dg"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptDigraph, kWinOptInvalid, kBufOptInvalid),
        var: p_dg.as_raw().cast(),
        ..BLANK
    },
    // 'directory'
    vimoption_T {
        fullname: name(c"directory"),
        shortname: name(c"dir"),
        flags: kOptFlagOneComma
            | kOptFlagExpand
            | kOptFlagNoDefExp
            | kOptFlagSecure
            | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptDirectory, kWinOptInvalid, kBufOptInvalid),
        var: p_dir.as_raw().cast(),
        def_val: string(c""),
        ..BLANK
    },
    // 'display'
    vimoption_T {
        fullname: name(c"display"),
        shortname: name(c"dy"),
        flags: kOptFlagOneComma | kOptFlagRedrAll | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptDisplay, kWinOptInvalid, kBufOptInvalid),
        var: p_dy.as_raw().cast(),
        flags_var: dy_flags.as_raw(),
        values: opt_dy_values.as_raw().cast(),
        values_len: 4,
        opt_did_set_cb: Some(did_set_display),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"lastline"),
        ..BLANK
    },
    // 'eadirection'
    vimoption_T {
        fullname: name(c"eadirection"),
        shortname: name(c"ead"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptEadirection, kWinOptInvalid, kBufOptInvalid),
        var: p_ead.as_raw().cast(),
        values: opt_ead_values.as_raw().cast(),
        values_len: 3,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"both"),
        ..BLANK
    },
];
