//! Dispatch wrappers for `crate::api::buffer`, part 2 of 2.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]
#![allow(unsafe_code)]

use super::*;

/// The msgpack-RPC dispatch wrapper for `nvim_buf_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `arena` is the caller's own and live for the call. The argument
/// array is this wrapper's: each value it uses is taken out of its slot
/// and whatever is left drops with the array.
pub unsafe fn handle_nvim_buf_set_var(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_buf_set_var",
        c"nvim_buf_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeBuffer) else {
        return Err(wrong_type(1, c"nvim_buf_set_var", c"Buffer"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"nvim_buf_set_var", c"String"));
    };
    let arg_3 = args[2].take();
    nvim_buf_set_var(arg_1, arg_2, arg_3)?;
    Ok(Object::Nil)
}
