//! Dispatch wrappers for `crate::api::deprecated`, part 2 of 2.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

/// The msgpack-RPC dispatch wrapper for `tabpage_del_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_tabpage_del_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_tabpage_del_var",
        c"tabpage_del_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"tabpage_del_var", c"Tabpage"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"tabpage_del_var", c"String"));
    };
    tabpage_del_var(arg_1, arg_2)
}

/// The msgpack-RPC dispatch wrapper for `tabpage_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_tabpage_set_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_tabpage_set_var",
        c"tabpage_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"tabpage_set_var", c"Tabpage"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"tabpage_set_var", c"String"));
    };
    let arg_3 = args[2].take();
    tabpage_set_var(arg_1, arg_2, arg_3)
}

/// The msgpack-RPC dispatch wrapper for `vim_del_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_vim_del_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_vim_del_var",
        c"vim_del_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_string(args[0].take()) else {
        return Err(wrong_type(1, c"vim_del_var", c"String"));
    };
    vim_del_var(arg_1)
}

/// The msgpack-RPC dispatch wrapper for `vim_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_vim_set_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_vim_set_var",
        c"vim_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_string(args[0].take()) else {
        return Err(wrong_type(1, c"vim_set_var", c"String"));
    };
    let arg_2 = args[1].take();
    vim_set_var(arg_1, arg_2)
}

/// The msgpack-RPC dispatch wrapper for `window_del_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_window_del_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_window_del_var",
        c"window_del_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeWindow) else {
        return Err(wrong_type(1, c"window_del_var", c"Window"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"window_del_var", c"String"));
    };
    window_del_var(arg_1, arg_2)
}

/// The msgpack-RPC dispatch wrapper for `window_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_window_set_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_window_set_var",
        c"window_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeWindow) else {
        return Err(wrong_type(1, c"window_set_var", c"Window"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"window_set_var", c"String"));
    };
    let arg_3 = args[2].take();
    window_set_var(arg_1, arg_2, arg_3)
}
