//! Dispatch wrappers for `crate::api::deprecated`, part 2 of 2.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]
#![allow(unsafe_code)]

use super::*;

/// The msgpack-RPC dispatch wrapper for `nvim_get_option_info`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_get_option_info(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_get_option_info",
        c"nvim_get_option_info",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"nvim_get_option_info", c"String"));
    };
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    let rv = unsafe { nvim_get_option_info(arg_1, arena) }?;
    Ok(Object::Dict(rv))
}

/// The msgpack-RPC dispatch wrapper for `nvim_notify`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_notify(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_notify",
        c"nvim_notify",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"nvim_notify", c"String"));
    };
    let Some(arg_2) = as_integer(args[1]) else {
        return Err(wrong_type(2, c"nvim_notify", c"Integer"));
    };
    let Some(arg_3) = as_dict(args[2]) else {
        return Err(wrong_type(3, c"nvim_notify", c"Dict"));
    };
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { nvim_notify(arg_1, arg_2, arg_3, arena) }
}

/// The msgpack-RPC dispatch wrapper for `nvim_out_write`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_out_write(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_out_write",
        c"nvim_out_write",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"nvim_out_write", c"String"));
    };
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { nvim_out_write(arg_1) };
    Ok(Object::Nil)
}

/// The msgpack-RPC dispatch wrapper for `nvim_set_option`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_set_option(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_set_option",
        c"nvim_set_option",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"nvim_set_option", c"String"));
    };
    let arg_2 = args[1];
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { nvim_set_option(channel_id, arg_1, arg_2) }?;
    Ok(Object::Nil)
}

/// The msgpack-RPC dispatch wrapper for `nvim_subscribe`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_subscribe(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_subscribe",
        c"nvim_subscribe",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"nvim_subscribe", c"String"));
    };
    nvim_subscribe(channel_id, arg_1);
    Ok(Object::Nil)
}

/// The msgpack-RPC dispatch wrapper for `nvim_unsubscribe`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_unsubscribe(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_unsubscribe",
        c"nvim_unsubscribe",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"nvim_unsubscribe", c"String"));
    };
    nvim_unsubscribe(channel_id, arg_1);
    Ok(Object::Nil)
}

/// The msgpack-RPC dispatch wrapper for `nvim_win_get_option`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_win_get_option(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_win_get_option",
        c"nvim_win_get_option",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0], kObjectTypeWindow) else {
        return Err(wrong_type(1, c"nvim_win_get_option", c"Window"));
    };
    let Some(arg_2) = as_string(args[1]) else {
        return Err(wrong_type(2, c"nvim_win_get_option", c"String"));
    };
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { nvim_win_get_option(arg_1, arg_2) }
}

/// The msgpack-RPC dispatch wrapper for `nvim_win_set_option`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_win_set_option(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_win_set_option",
        c"nvim_win_set_option",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0], kObjectTypeWindow) else {
        return Err(wrong_type(1, c"nvim_win_set_option", c"Window"));
    };
    let Some(arg_2) = as_string(args[1]) else {
        return Err(wrong_type(2, c"nvim_win_set_option", c"String"));
    };
    let arg_3 = args[2];
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { nvim_win_set_option(channel_id, arg_1, arg_2, arg_3) }?;
    Ok(Object::Nil)
}

/// The msgpack-RPC dispatch wrapper for `tabpage_del_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_tabpage_del_var(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_tabpage_del_var",
        c"tabpage_del_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0], kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"tabpage_del_var", c"Tabpage"));
    };
    let Some(arg_2) = as_string(args[1]) else {
        return Err(wrong_type(2, c"tabpage_del_var", c"String"));
    };
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { tabpage_del_var(arg_1, arg_2, arena) }
}

/// The msgpack-RPC dispatch wrapper for `tabpage_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_tabpage_set_var(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_tabpage_set_var",
        c"tabpage_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0], kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"tabpage_set_var", c"Tabpage"));
    };
    let Some(arg_2) = as_string(args[1]) else {
        return Err(wrong_type(2, c"tabpage_set_var", c"String"));
    };
    let arg_3 = args[2];
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { tabpage_set_var(arg_1, arg_2, arg_3, arena) }
}

/// The msgpack-RPC dispatch wrapper for `vim_del_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_vim_del_var(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_vim_del_var",
        c"vim_del_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"vim_del_var", c"String"));
    };
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { vim_del_var(arg_1, arena) }
}

/// The msgpack-RPC dispatch wrapper for `vim_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_vim_set_var(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_vim_set_var",
        c"vim_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_string(args[0]) else {
        return Err(wrong_type(1, c"vim_set_var", c"String"));
    };
    let arg_2 = args[1];
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { vim_set_var(arg_1, arg_2, arena) }
}

/// The msgpack-RPC dispatch wrapper for `window_del_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_window_del_var(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_window_del_var",
        c"window_del_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0], kObjectTypeWindow) else {
        return Err(wrong_type(1, c"window_del_var", c"Window"));
    };
    let Some(arg_2) = as_string(args[1]) else {
        return Err(wrong_type(2, c"window_del_var", c"String"));
    };
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { window_del_var(arg_1, arg_2, arena) }
}

/// The msgpack-RPC dispatch wrapper for `window_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_window_set_var(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
) -> Result<Object, Error> {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_window_set_var",
        c"window_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0], kObjectTypeWindow) else {
        return Err(wrong_type(1, c"window_set_var", c"Window"));
    };
    let Some(arg_2) = as_string(args[1]) else {
        return Err(wrong_type(2, c"window_set_var", c"String"));
    };
    let arg_3 = args[2];
    // SAFETY: each argument was checked against the type the signature declares,
    // and `arena` is the dispatcher's own.
    unsafe { window_set_var(arg_1, arg_2, arg_3, arena) }
}
