//! Dispatch wrappers for `crate::api::events`.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

/// The msgpack-RPC dispatch wrapper for `nvim_error_event`.
///
/// Decodes the argument array against the signature, refuses the call
/// through `error` if the arity or a type is wrong, and encodes the
/// answer as an `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_error_event(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: &mut Error,
) -> Object {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_error_event",
        c"nvim_error_event",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        wrong_arity(error, 2, args.len());
        return Object::Nil;
    }
    let Some(arg_1) = as_integer(args[0]) else {
        wrong_type(error, 1, c"nvim_error_event", c"Integer");
        return Object::Nil;
    };
    let Some(arg_2) = as_string(args[1]) else {
        wrong_type(error, 2, c"nvim_error_event", c"String");
        return Object::Nil;
    };
    // SAFETY: each argument was checked against the type the signature declares;
    // `arena` and `error` are the dispatcher's own.
    unsafe { nvim_error_event(channel_id, arg_1, arg_2) };
    Object::Nil
}

/// The msgpack-RPC dispatch wrapper for `nvim_ui_term_event`.
///
/// Decodes the argument array against the signature, refuses the call
/// through `error` if the arity or a type is wrong, and encodes the
/// answer as an `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_ui_term_event(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: &mut Error,
) -> Object {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_ui_term_event",
        c"nvim_ui_term_event",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        wrong_arity(error, 2, args.len());
        return Object::Nil;
    }
    let Some(arg_1) = as_string(args[0]) else {
        wrong_type(error, 1, c"nvim_ui_term_event", c"String");
        return Object::Nil;
    };
    let arg_2 = args[1];
    // SAFETY: each argument was checked against the type the signature declares;
    // `arena` and `error` are the dispatcher's own.
    if let Err(e) = unsafe { nvim_ui_term_event(channel_id, arg_1, arg_2) } {
        return failure(error, e);
    }
    Object::Nil
}
