//! Dispatch wrappers for `crate::api::options`.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

/// The msgpack-RPC dispatch wrapper for `nvim_get_all_options_info`.
///
/// Decodes the argument array against the signature, refuses the call
/// through `error` if the arity or a type is wrong, and encodes the
/// answer as an `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_get_all_options_info(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: &mut Error,
) -> Object {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_get_all_options_info",
        c"nvim_get_all_options_info",
        line!() as c_int,
        channel_id,
    );
    if !args.is_empty() {
        wrong_arity(error, 0, args.len());
        return Object::Nil;
    }
    // SAFETY: each argument was checked against the type the signature declares;
    // `arena` and `error` are the dispatcher's own.
    let rv = unsafe { nvim_get_all_options_info(arena) };
    Object::Dict(rv)
}

/// The msgpack-RPC dispatch wrapper for `nvim_get_option_info2`.
///
/// Decodes the argument array against the signature, refuses the call
/// through `error` if the arity or a type is wrong, and encodes the
/// answer as an `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_get_option_info2(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: &mut Error,
) -> Object {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_get_option_info2",
        c"nvim_get_option_info2",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        wrong_arity(error, 2, args.len());
        return Object::Nil;
    }
    let Some(arg_1) = as_string(args[0]) else {
        wrong_type(error, 1, c"nvim_get_option_info2", c"String");
        return Object::Nil;
    };
    let mut arg_2: KeyDict_option =
        match read_keydict(Some(key_dict_option_get_field), args[1], error) {
            KeySetArg::Read(v) => v,
            KeySetArg::Refused => return Object::Nil,
            KeySetArg::WrongType => {
                wrong_type(error, 2, c"nvim_get_option_info2", c"Dict(option) *");
                return Object::Nil;
            }
        };
    // SAFETY: each argument was checked against the type the signature declares;
    // `arena` and `error` are the dispatcher's own.
    let rv = match unsafe { nvim_get_option_info2(arg_1, &raw mut arg_2, arena) } {
        Ok(rv) => rv,
        Err(e) => return failure(error, e),
    };
    Object::Dict(rv)
}

/// The msgpack-RPC dispatch wrapper for `nvim_get_option_value`.
///
/// Decodes the argument array against the signature, refuses the call
/// through `error` if the arity or a type is wrong, and encodes the
/// answer as an `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_get_option_value(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: &mut Error,
) -> Object {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_get_option_value",
        c"nvim_get_option_value",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        wrong_arity(error, 2, args.len());
        return Object::Nil;
    }
    let Some(arg_1) = as_string(args[0]) else {
        wrong_type(error, 1, c"nvim_get_option_value", c"String");
        return Object::Nil;
    };
    let mut arg_2: KeyDict_option =
        match read_keydict(Some(key_dict_option_get_field), args[1], error) {
            KeySetArg::Read(v) => v,
            KeySetArg::Refused => return Object::Nil,
            KeySetArg::WrongType => {
                wrong_type(error, 2, c"nvim_get_option_value", c"Dict(option) *");
                return Object::Nil;
            }
        };
    // SAFETY: each argument was checked against the type the signature declares;
    // `arena` and `error` are the dispatcher's own.
    match unsafe { nvim_get_option_value(arg_1, &raw mut arg_2) } {
        Ok(rv) => rv,
        Err(e) => failure(error, e),
    }
}

/// The msgpack-RPC dispatch wrapper for `nvim_set_option_value`.
///
/// Decodes the argument array against the signature, refuses the call
/// through `error` if the arity or a type is wrong, and encodes the
/// answer as an `Object`.
///
/// # Safety
/// The dispatcher's contract, which is what every `unsafe` below rests
/// on: `args` is an `Array` of `size` initialized `Object`s that outlives
/// the call and stays the caller's to free, and `arena` is the caller's
/// own and live for the call.
pub unsafe fn handle_nvim_set_option_value(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: &mut Error,
) -> Object {
    // SAFETY: the dispatcher hands over an argument array of `size`
    // initialized objects that outlives the call.
    let args = unsafe { args_slice(&args) };
    log_invoke(
        c"handle_nvim_set_option_value",
        c"nvim_set_option_value",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        wrong_arity(error, 3, args.len());
        return Object::Nil;
    }
    let Some(arg_1) = as_string(args[0]) else {
        wrong_type(error, 1, c"nvim_set_option_value", c"String");
        return Object::Nil;
    };
    let arg_2 = args[1];
    let mut arg_3: KeyDict_option =
        match read_keydict(Some(key_dict_option_get_field), args[2], error) {
            KeySetArg::Read(v) => v,
            KeySetArg::Refused => return Object::Nil,
            KeySetArg::WrongType => {
                wrong_type(error, 3, c"nvim_set_option_value", c"Dict(option) *");
                return Object::Nil;
            }
        };
    // SAFETY: each argument was checked against the type the signature declares;
    // `arena` and `error` are the dispatcher's own.
    if let Err(e) = unsafe { nvim_set_option_value(channel_id, arg_1, arg_2, &raw mut arg_3) } {
        return failure(error, e);
    }
    Object::Nil
}
