//! Dispatch wrappers for `crate::api::tabpage`.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

/// The msgpack-RPC dispatch wrapper for `nvim_open_tabpage`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_open_tabpage(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_open_tabpage",
        c"nvim_open_tabpage",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeBuffer) else {
        return Err(wrong_type(1, c"nvim_open_tabpage", c"Buffer"));
    };
    let Some(arg_2) = as_boolean(args[1].take()) else {
        return Err(wrong_type(2, c"nvim_open_tabpage", c"Boolean"));
    };
    let mut arg_3: KeyDict_tabpage_config =
        match read_keydict(Some(key_dict_tabpage_config_get_field), args[2].take()) {
            KeySetArg::Read(v) => v,
            KeySetArg::Refused(e) => return Err(e),
            KeySetArg::WrongType => {
                return Err(wrong_type(
                    3,
                    c"nvim_open_tabpage",
                    c"Dict(tabpage_config) *",
                ));
            }
        };
    if textlock.get() != 0 || expr_map_locked() {
        return Err(expr_map_locked_error());
    }
    let rv = nvim_open_tabpage(arg_1, arg_2, &mut arg_3)?;
    Ok(Object::Tabpage(rv as Integer))
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_del_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_del_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_del_var",
        c"nvim_tabpage_del_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_del_var", c"Tabpage"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"nvim_tabpage_del_var", c"String"));
    };
    nvim_tabpage_del_var(arg_1, arg_2)?;
    Ok(Object::Nil)
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_get_number`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_get_number(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_get_number",
        c"nvim_tabpage_get_number",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_get_number", c"Tabpage"));
    };
    let rv = nvim_tabpage_get_number(arg_1)?;
    Ok(Object::Integer(rv))
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_get_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_get_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_get_var",
        c"nvim_tabpage_get_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_get_var", c"Tabpage"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"nvim_tabpage_get_var", c"String"));
    };
    nvim_tabpage_get_var(arg_1, arg_2)
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_get_win`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_get_win(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_get_win",
        c"nvim_tabpage_get_win",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_get_win", c"Tabpage"));
    };
    let rv = nvim_tabpage_get_win(arg_1)?;
    Ok(Object::Window(rv as Integer))
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_is_valid`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_is_valid(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_is_valid",
        c"nvim_tabpage_is_valid",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_is_valid", c"Tabpage"));
    };
    let rv = nvim_tabpage_is_valid(arg_1);
    Ok(Object::Boolean(rv))
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_list_wins`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_list_wins(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_list_wins",
        c"nvim_tabpage_list_wins",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 1 {
        return Err(wrong_arity(1, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_list_wins", c"Tabpage"));
    };
    let rv = nvim_tabpage_list_wins(arg_1)?;
    Ok(Object::array(rv))
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_set_var`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_set_var(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_set_var",
        c"nvim_tabpage_set_var",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 3 {
        return Err(wrong_arity(3, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_set_var", c"Tabpage"));
    };
    let Some(arg_2) = as_string(args[1].take()) else {
        return Err(wrong_type(2, c"nvim_tabpage_set_var", c"String"));
    };
    let arg_3 = args[2].take();
    nvim_tabpage_set_var(arg_1, arg_2, arg_3)?;
    Ok(Object::Nil)
}

/// The msgpack-RPC dispatch wrapper for `nvim_tabpage_set_win`.
///
/// Decodes the argument array against the signature, answers `Err` if
/// the arity or a type is wrong, and encodes the answer as an
/// `Object`.
pub fn handle_nvim_tabpage_set_win(
    channel_id: uint64_t,
    args: Array,
    _arena: &mut Arena,
) -> Result<Object, Error> {
    let mut args = args;
    log_invoke(
        c"handle_nvim_tabpage_set_win",
        c"nvim_tabpage_set_win",
        line!() as c_int,
        channel_id,
    );
    if args.len() != 2 {
        return Err(wrong_arity(2, args.len()));
    }
    let Some(arg_1) = as_handle(args[0].take(), kObjectTypeTabpage) else {
        return Err(wrong_type(1, c"nvim_tabpage_set_win", c"Tabpage"));
    };
    let Some(arg_2) = as_handle(args[1].take(), kObjectTypeWindow) else {
        return Err(wrong_type(2, c"nvim_tabpage_set_win", c"Window"));
    };
    nvim_tabpage_set_win(arg_1, arg_2)?;
    Ok(Object::Nil)
}
