//! Version checking utilities for Neovim
//!
//! Provides functions to check Neovim version compatibility.

#![allow(unsafe_code)]
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::cast_lossless)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::manual_let_else)]

mod patches;

// Include compile-time version constants generated by build.rs from CMakeLists.txt.
include!(concat!(env!("OUT_DIR"), "/version_constants.rs"));

use std::ffi::{c_char, c_int};

/// Get the current Neovim version as (major, minor, patch)
#[inline]
const fn get_nvim_version() -> (i32, i32, i32) {
    (NVIM_VERSION_MAJOR, NVIM_VERSION_MINOR, NVIM_VERSION_PATCH)
}

/// Parse a version string like "1.2.3" into (major, minor, patch)
///
/// Returns None if the string is invalid.
fn parse_version_string(s: &[u8]) -> Option<(i32, i32, i32)> {
    if s.is_empty() {
        return None;
    }

    let mut pos = 0;

    // Skip leading whitespace (shouldn't happen but be safe)
    while pos < s.len() && s[pos].is_ascii_whitespace() {
        pos += 1;
    }

    if pos >= s.len() || !s[pos].is_ascii_digit() {
        return None;
    }

    // Parse major version
    let major_start = pos;
    while pos < s.len() && s[pos].is_ascii_digit() {
        pos += 1;
    }
    let major = parse_int(&s[major_start..pos])?;

    // Check for minor version
    let minor = if pos < s.len() && s[pos] == b'.' {
        pos += 1; // skip dot
        if pos >= s.len() || !s[pos].is_ascii_digit() {
            return None;
        }
        let minor_start = pos;
        while pos < s.len() && s[pos].is_ascii_digit() {
            pos += 1;
        }
        parse_int(&s[minor_start..pos])?
    } else {
        0
    };

    // Check for patch version
    let patch = if pos < s.len() && s[pos] == b'.' {
        pos += 1; // skip dot
        if pos >= s.len() || !s[pos].is_ascii_digit() {
            return None;
        }
        let patch_start = pos;
        while pos < s.len() && s[pos].is_ascii_digit() {
            pos += 1;
        }
        parse_int(&s[patch_start..pos])?
    } else {
        0
    };

    Some((major, minor, patch))
}

/// Parse a slice of ASCII digits into an integer
fn parse_int(s: &[u8]) -> Option<i32> {
    if s.is_empty() {
        return None;
    }
    let mut result: i32 = 0;
    for &b in s {
        if !b.is_ascii_digit() {
            return None;
        }
        result = result.checked_mul(10)?.checked_add((b - b'0') as i32)?;
    }
    Some(result)
}

/// Check if the current Neovim version is at or above the given version.
///
/// # Arguments
/// * `version_str` - Version string like "1.2.3" or "0.10" or "1"
///
/// # Returns
/// `true` if Neovim is at or above the specified version
#[inline]
pub fn has_nvim_version(version_str: &[u8]) -> bool {
    // Find the null terminator if present
    let len = version_str
        .iter()
        .position(|&b| b == 0)
        .unwrap_or(version_str.len());
    let s = &version_str[..len];

    let (req_major, req_minor, req_patch) = match parse_version_string(s) {
        Some(v) => v,
        None => return false,
    };

    let (cur_major, cur_minor, cur_patch) = get_nvim_version();

    // Compare versions
    req_major < cur_major
        || (req_major == cur_major
            && (req_minor < cur_minor || (req_minor == cur_minor && req_patch <= cur_patch)))
}

/// FFI wrapper for `has_nvim_version`.
///
/// # Safety
/// - `version_str` must be a valid null-terminated C string
#[export_name = "has_nvim_version"]
pub unsafe extern "C" fn rs_has_nvim_version(version_str: *const c_char) -> bool {
    if version_str.is_null() {
        return false;
    }

    // Find string length (up to reasonable max)
    let mut len = 0;
    while len < 64 && *version_str.add(len) != 0 {
        len += 1;
    }

    let slice = std::slice::from_raw_parts(version_str.cast::<u8>(), len);
    has_nvim_version(slice)
}

/// Returns the minimum supported Vim version.
///
/// This is `VIM_VERSIONS[0]`, e.g., 801 for Vim 8.01.
#[export_name = "min_vim_version"]
pub extern "C" fn rs_min_vim_version() -> c_int {
    patches::VIM_VERSIONS[0]
}

/// C-compatible accessor for `min_vim_version` (called by buffer/modeline.rs).
#[no_mangle]
pub extern "C" fn nvim_get_min_vim_version() -> c_int {
    patches::VIM_VERSIONS[0]
}

/// Returns the highest patch number for the minimum Vim version.
///
/// This is `INCLUDED_PATCHSETS[0][0]`, the first entry in the patchset array.
#[export_name = "highest_patch"]
pub extern "C" fn rs_highest_patch() -> c_int {
    patches::INCLUDED_PATCHSETS[0][0]
}

/// Checks whether a Vim patch has been included.
///
/// Performs a binary search in the `INCLUDED_PATCHSETS` array for the given
/// patch number. The patches are sorted in descending order.
///
/// # Arguments
/// * `n` - Patch number to check
/// * `major_minor_version` - (major * 100 + minor) Vim version, or 0 for default
///
/// # Returns
/// `true` if patch `n` has been included
#[inline]
fn has_vim_patch_impl(n: c_int, major_minor_version: c_int) -> bool {
    let versions = patches::VIM_VERSIONS;
    let patchsets = patches::INCLUDED_PATCHSETS;

    // Handle the version index
    let v_i: usize = if major_minor_version > 0 {
        if major_minor_version < versions[0] {
            // Older than our minimum version - all patches included
            return true;
        }

        // Find the version index
        match versions.iter().position(|&v| v == major_minor_version) {
            Some(idx) => idx,
            None => return false, // Version not found
        }
    } else {
        0 // Use minimum version
    };

    // Perform binary search (patches are in descending order)
    let patchset = patchsets[v_i];
    if patchset.is_empty() {
        return false;
    }

    let mut l: usize = 0;
    let mut h: usize = patchset.len() - 1;
    // Patches are in descending order: patchset[0] > patchset[1] > ...
    // Binary search: narrow [l, h] until found or exhausted.
    loop {
        // m is always strictly less than h when l < h (floor division).
        let m = l + (h - l) / 2;
        let patch = patchset[m];
        if patch == n {
            return true;
        }
        if l == h {
            break;
        }
        // If current patch < n: n must be at a lower index (higher values), so h = m.
        // If current patch > n: n must be at a higher index (lower values), so l = m+1.
        if patch < n {
            h = m; // m < h guaranteed above, so this shrinks the range
        } else {
            l = m + 1;
        }
    }
    false
}

/// FFI wrapper for `has_vim_patch`.
#[export_name = "has_vim_patch"]
pub extern "C" fn rs_has_vim_patch(n: c_int, major_minor_version: c_int) -> bool {
    has_vim_patch_impl(n, major_minor_version)
}

// =============================================================================
// Phase 1: list_in_columns and version_msg helpers
// =============================================================================

extern "C" {
    static got_int: c_int;
    static Columns: c_int;
    static mut msg_col: c_int;

    fn msg_puts(s: *const c_char);
    fn msg_putchar(c: c_int);
    fn vim_strsize(s: *const c_char) -> c_int;
}

/// Output a string for the version message.  If it's going to wrap, output a
/// newline, unless the message is too long to fit on the screen anyway.
/// When `wrap` is true, wrap the string in `[]`.
///
/// # Safety
/// `s` must be a valid null-terminated C string pointer.
/// Calls C FFI functions (`msg_puts`, `msg_putchar`, `vim_strsize`).
/// Must be called from the main Neovim thread.
unsafe fn version_msg_wrap(s: *const c_char, wrap: bool) {
    let extra = if wrap { 2 } else { 0 };
    let len = vim_strsize(s) + extra;

    // 10 = b'\n'; use literal to avoid u8->i8 cast lint
    if got_int == 0 && len < Columns && msg_col + len >= Columns && *s != 10 {
        msg_putchar(b'\n' as c_int);
    }

    if got_int == 0 {
        if wrap {
            msg_puts(c"[".as_ptr());
        }
        msg_puts(s);
        if wrap {
            msg_puts(c"]".as_ptr());
        }
    }
}

/// Call `version_msg_wrap(s, false)`.
/// Exported as `version_msg` for C callers (`list_version` until it is migrated).
///
/// # Safety
/// `s` must be a valid null-terminated C string.
#[unsafe(export_name = "version_msg")]
pub unsafe extern "C" fn rs_version_msg(s: *const c_char) {
    version_msg_wrap(s, false);
}

/// List string items nicely aligned in columns.
///
/// When `size` is < 0 then the last entry is marked with NULL.
/// The entry with index `current` is enclosed in `[]`.
///
/// # Safety
/// `items` must be a valid pointer to `size` (or NULL-terminated if size < 0)
/// pointers to null-terminated C strings.
#[unsafe(export_name = "list_in_columns")]
pub unsafe extern "C" fn rs_list_in_columns(items: *mut *mut c_char, size: c_int, current: c_int) {
    let mut item_count: c_int = 0;
    let mut width: c_int = 0;

    // Find the length of the longest item; use that + 1 as the column width.
    let mut i: c_int = 0;
    loop {
        let done = if size < 0 {
            // Safety: caller guarantees NULL-terminated array when size < 0.
            #[allow(clippy::cast_sign_loss)]
            (*items.add(i as usize)).is_null()
        } else {
            i >= size
        };
        if done {
            break;
        }
        #[allow(clippy::cast_sign_loss)]
        let l = vim_strsize(*items.add(i as usize)) + if i == current { 2 } else { 0 };
        if l > width {
            width = l;
        }
        item_count += 1;
        i += 1;
    }
    width += 1;

    if Columns < width {
        // Not enough screen columns — show one per line.
        for idx in 0..item_count {
            #[allow(clippy::cast_sign_loss)]
            let item = *items.add(idx as usize);
            version_msg_wrap(item, idx == current);
            if msg_col > 0 && idx < item_count - 1 {
                msg_putchar(b'\n' as c_int);
            }
        }
        return;
    }

    // The rightmost column doesn't need a separator.
    // Sacrifice it to fit in one more column if possible.
    let ncol = (Columns + 1) / width;
    let nrow = item_count / ncol + i32::from(item_count % ncol != 0);
    let mut cur_row: c_int = 1;

    // `i` counts columns then rows; `idx` counts rows then columns.
    let mut i: c_int = 0;
    while got_int == 0 && i < nrow * ncol {
        let idx = (i / ncol) + (i % ncol) * nrow;
        if idx < item_count {
            let last_col = (i + 1) % ncol == 0;
            if idx == current {
                msg_putchar(b'[' as c_int);
            }
            #[allow(clippy::cast_sign_loss)]
            let item = *items.add(idx as usize);
            msg_puts(item);
            if idx == current {
                msg_putchar(b']' as c_int);
            }
            if last_col {
                if msg_col > 0 && cur_row < nrow {
                    msg_putchar(b'\n' as c_int);
                }
                cur_row += 1;
            } else {
                while msg_col % width != 0 {
                    msg_putchar(b' ' as c_int);
                }
            }
        } else {
            // This row is out of items — at the end of the row.
            if msg_col > 0 {
                if cur_row < nrow {
                    msg_putchar(b'\n' as c_int);
                }
                cur_row += 1;
            }
        }
        i += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_version_string() {
        assert_eq!(parse_version_string(b"1.2.3"), Some((1, 2, 3)));
        assert_eq!(parse_version_string(b"0.10.0"), Some((0, 10, 0)));
        assert_eq!(parse_version_string(b"1.0"), Some((1, 0, 0)));
        assert_eq!(parse_version_string(b"2"), Some((2, 0, 0)));
        assert_eq!(parse_version_string(b""), None);
        assert_eq!(parse_version_string(b"abc"), None);
        assert_eq!(parse_version_string(b"1."), None);
        assert_eq!(parse_version_string(b"1.2."), None);
    }

    #[test]
    fn test_parse_int() {
        assert_eq!(parse_int(b"0"), Some(0));
        assert_eq!(parse_int(b"123"), Some(123));
        assert_eq!(parse_int(b""), None);
        assert_eq!(parse_int(b"12a"), None);
    }

    #[test]
    fn test_parse_version_string_large_numbers() {
        // Test with larger version numbers
        assert_eq!(parse_version_string(b"10.20.30"), Some((10, 20, 30)));
        assert_eq!(parse_version_string(b"100.200.300"), Some((100, 200, 300)));
    }

    #[test]
    fn test_parse_version_string_edge_cases() {
        // Version with zeros
        assert_eq!(parse_version_string(b"0.0.0"), Some((0, 0, 0)));
        // Just zero
        assert_eq!(parse_version_string(b"0"), Some((0, 0, 0)));
        // Invalid: multiple dots
        assert_eq!(parse_version_string(b"1..2"), None);
        // Invalid: leading dot
        assert_eq!(parse_version_string(b".1.2"), None);
    }

    #[test]
    fn test_parse_int_edge_cases() {
        // Single digit
        assert_eq!(parse_int(b"5"), Some(5));
        // Leading zeros are allowed
        assert_eq!(parse_int(b"007"), Some(7));
        // All digits
        assert_eq!(parse_int(b"1234567890"), Some(1_234_567_890));
    }

    #[test]
    fn test_parse_int_overflow() {
        // Very large number that would overflow - should return None
        assert!(parse_int(b"99999999999999999999").is_none());
    }

    #[test]
    fn test_parse_version_with_null_terminator() {
        // Version string with null terminator (as from C)
        assert_eq!(parse_version_string(b"1.2.3\0"), Some((1, 2, 3)));
        // But the parsing stops at non-digits anyway
        assert_eq!(parse_version_string(b"1.2.3extra"), Some((1, 2, 3)));
    }

    #[test]
    fn test_parse_version_whitespace_handling() {
        // Leading whitespace is skipped
        assert_eq!(parse_version_string(b" 1.2.3"), Some((1, 2, 3)));
        assert_eq!(parse_version_string(b"\t1.2.3"), Some((1, 2, 3)));
        assert_eq!(parse_version_string(b"  1.2.3"), Some((1, 2, 3)));
        // Only whitespace returns None
        assert_eq!(parse_version_string(b"   "), None);
    }

    #[test]
    fn test_parse_int_single_digits() {
        // All single digits
        for i in 0..=9 {
            let s = [b'0' + i];
            assert_eq!(parse_int(&s), Some(i as i32));
        }
    }

    #[test]
    fn test_parse_version_boundary() {
        // i32::MAX is 2147483647
        // Check that large but valid versions work
        assert_eq!(
            parse_version_string(b"2147.483.647"),
            Some((2147, 483, 647))
        );
    }

    // Note: has_nvim_version tests require FFI linking.
    // Integration testing is done via the full Neovim build.
}
