//! Built-in descriptions for the graphical terminal emulators.
//!
//! Generated from Dickey's terminfo.src by way of ncurses; edited only by
//! regenerating. See [`Description`] for the shape.

#![forbid(unsafe_code)]

use super::Description;
use crate::src::nvim::tui::terminfo::caps::key_slot::*;
use crate::src::nvim::tui::terminfo::caps::*;

/// Ghostty. ncurses' description does not exactly match what Ghostty itself ships.
pub static GHOSTTY: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?12l\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h"),
        (kTerm_enter_dim_mode, c"\x1b[2m"),
        (kTerm_enter_italics_mode, c"\x1b[3m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_secure_mode, c"\x1b[8m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b(B\x1b[m"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l"),
        (kTerm_from_status_line, c"\x07"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_keypad_local, c"\x1b[?1l\x1b>"),
        (kTerm_keypad_xmit, c"\x1b[?1h\x1b="),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m"),
        (kTerm_set_a_foreground, c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m"),
        (kTerm_set_attributes, c"%?%p9%t\x1b(0%e\x1b(B%;\x1b[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p5%t;2%;%?%p7%t;8%;m"),
        (kTerm_set_lr_margin, c"\x1b[?69h\x1b[%i%p1%d;%p2%ds"),
        (kTerm_to_status_line, c"\x1b]2;"),
        (kTerm_reset_cursor_style, c"\x1b[2 q"),
        (kTerm_set_cursor_style, c"\x1b[%p1%d q"),
        (kTerm_enter_strikethrough_mode, c"\x1b[9m"),
        (kTerm_set_underline_style, c"\x1b[4:%p1%dm"),
    ],
    keys: &[
        (BACKSPACE, c"\x7f", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3;2~")),
        (END, c"\x1bOF", Some(c"\x1b[1;2F")),
        (HOME, c"\x1bOH", Some(c"\x1b[1;2H")),
        (IC, c"\x1b[2~", Some(c"\x1b[2;2~")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (LEFT, c"\x1bOD", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1bOC", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1bOP"), Some(c"\x1bOQ"), Some(c"\x1bOR"), Some(c"\x1bOS"), Some(c"\x1b[15~"),
        Some(c"\x1b[17~"), Some(c"\x1b[18~"), Some(c"\x1b[19~"), Some(c"\x1b[20~"),
        Some(c"\x1b[21~"), Some(c"\x1b[23~"), Some(c"\x1b[24~"), Some(c"\x1b[1;2P"),
        Some(c"\x1b[1;2Q"), Some(c"\x1b[1;2R"), Some(c"\x1b[1;2S"), Some(c"\x1b[15;2~"),
        Some(c"\x1b[17;2~"), Some(c"\x1b[18;2~"), Some(c"\x1b[19;2~"), Some(c"\x1b[20;2~"),
        Some(c"\x1b[21;2~"), Some(c"\x1b[23;2~"), Some(c"\x1b[24;2~"), Some(c"\x1b[1;5P"),
        Some(c"\x1b[1;5Q"), Some(c"\x1b[1;5R"), Some(c"\x1b[1;5S"), Some(c"\x1b[15;5~"),
        Some(c"\x1b[17;5~"), Some(c"\x1b[18;5~"), Some(c"\x1b[19;5~"), Some(c"\x1b[20;5~"),
        Some(c"\x1b[21;5~"), Some(c"\x1b[23;5~"), Some(c"\x1b[24;5~"), Some(c"\x1b[1;6P"),
        Some(c"\x1b[1;6Q"), Some(c"\x1b[1;6R"), Some(c"\x1b[1;6S"), Some(c"\x1b[15;6~"),
        Some(c"\x1b[17;6~"), Some(c"\x1b[18;6~"), Some(c"\x1b[19;6~"), Some(c"\x1b[20;6~"),
        Some(c"\x1b[21;6~"), Some(c"\x1b[23;6~"), Some(c"\x1b[24;6~"), Some(c"\x1b[1;3P"),
        Some(c"\x1b[1;3Q"), Some(c"\x1b[1;3R"), Some(c"\x1b[1;3S"), Some(c"\x1b[15;3~"),
        Some(c"\x1b[17;3~"), Some(c"\x1b[18;3~"), Some(c"\x1b[19;3~"), Some(c"\x1b[20;3~"),
        Some(c"\x1b[21;3~"), Some(c"\x1b[23;3~"), Some(c"\x1b[24;3~"), Some(c"\x1b[1;4P"),
        Some(c"\x1b[1;4Q"), Some(c"\x1b[1;4R"),
    ],
};

/// iTerm2.
pub static ITERM_256COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h\x1b[22;0;0t"),
        (kTerm_enter_dim_mode, c"\x1b[2m"),
        (kTerm_enter_italics_mode, c"\x1b[3m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_exit_attribute_mode, c"\x1b[m\x0f"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l\x1b[23;0;0t"),
        (kTerm_from_status_line, c"\x07"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_keypad_local, c"\x1b[?1l\x1b>"),
        (kTerm_keypad_xmit, c"\x1b[?1h\x1b="),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (
            kTerm_set_a_background,
            c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m",
        ),
        (
            kTerm_set_a_foreground,
            c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m",
        ),
        (
            kTerm_set_attributes,
            c"\x1b[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t^N%e\x0f%;",
        ),
        (kTerm_to_status_line, c"\x1b]2;"),
        (kTerm_enter_strikethrough_mode, c"\x1b[9m"),
        (kTerm_set_underline_style, c"\x1b[4:%p1%dm"),
    ],
    keys: &[
        (BACKSPACE, c"\x7f", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", None),
        (END, c"\x1bOF", Some(c"\x1b[1;2F")),
        (HOME, c"\x1bOH", Some(c"\x1b[1;2H")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (LEFT, c"\x1bOD", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1bOC", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1bOP"),
        Some(c"\x1bOQ"),
        Some(c"\x1bOR"),
        Some(c"\x1bOS"),
        Some(c"\x1b[15~"),
        Some(c"\x1b[17~"),
        Some(c"\x1b[18~"),
        Some(c"\x1b[19~"),
        Some(c"\x1b[20~"),
        Some(c"\x1b[21~"),
        Some(c"\x1b[23~"),
        Some(c"\x1b[24~"),
        Some(c"\x1b[1;2P"),
        Some(c"\x1b[1;2Q"),
        Some(c"\x1b[1;2R"),
        Some(c"\x1b[1;2S"),
        Some(c"\x1b[15;2~"),
        Some(c"\x1b[17;2~"),
        Some(c"\x1b[18;2~"),
        Some(c"\x1b[19;2~"),
        Some(c"\x1b[20;2~"),
        Some(c"\x1b[21;2~"),
        Some(c"\x1b[23;2~"),
        Some(c"\x1b[24;2~"),
    ],
};

/// PuTTY.
pub static PUTTY_256COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: -1,
    columns: -1,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\x1bD"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?25h"),
        (kTerm_cursor_up, c"\x1bM"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b[m\x0f"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l"),
        (kTerm_from_status_line, c"\x07"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_keypad_local, c"\x1b[?1l\x1b>"),
        (kTerm_keypad_xmit, c"\x1b[?1h\x1b="),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (
            kTerm_set_a_background,
            c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m",
        ),
        (
            kTerm_set_a_foreground,
            c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m",
        ),
        (
            kTerm_set_attributes,
            c"\x1b[0%?%p1%p6%|%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;m%?%p9%t^N%e\x0f%;",
        ),
        (kTerm_to_status_line, c"\x1b]0;"),
        (kTerm_enter_strikethrough_mode, c"\x1b[9m"),
    ],
    keys: &[
        (BACKSPACE, c"\x7f", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", None),
        (END, c"\x1b[4~", None),
        (HOME, c"\x1b[1~", None),
        (IC, c"\x1b[2~", None),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (SUSPEND, c"^Z", None),
        (LEFT, c"\x1bOD", None),
        (RIGHT, c"\x1bOC", None),
    ],
    f_keys: &[
        Some(c"\x1b[11~"),
        Some(c"\x1b[12~"),
        Some(c"\x1b[13~"),
        Some(c"\x1b[14~"),
        Some(c"\x1b[15~"),
        Some(c"\x1b[17~"),
        Some(c"\x1b[18~"),
        Some(c"\x1b[19~"),
        Some(c"\x1b[20~"),
        Some(c"\x1b[21~"),
        Some(c"\x1b[23~"),
        Some(c"\x1b[24~"),
        Some(c"\x1b[25~"),
        Some(c"\x1b[26~"),
        Some(c"\x1b[28~"),
        Some(c"\x1b[29~"),
        Some(c"\x1b[31~"),
        Some(c"\x1b[32~"),
        Some(c"\x1b[33~"),
        Some(c"\x1b[34~"),
    ],
};

/// rxvt.
pub static RXVT_256COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b7\x1b[?47h"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_exit_attribute_mode, c"\x1b[m\x0f"),
        (kTerm_exit_ca_mode, c"\x1b[2J\x1b[?47l\x1b8"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_keypad_local, c"\x1b>"),
        (kTerm_keypad_xmit, c"\x1b="),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (
            kTerm_set_a_background,
            c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m",
        ),
        (
            kTerm_set_a_foreground,
            c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m",
        ),
        (
            kTerm_set_attributes,
            c"\x1b[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;m%?%p9%t^N%e\x0f%;",
        ),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3$")),
        (END, c"\x1b[8~", Some(c"\x1b[8$")),
        (FIND, c"\x1b[1~", None),
        (HOME, c"\x1b[7~", Some(c"\x1b[7$")),
        (IC, c"\x1b[2~", Some(c"\x1b[2$")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (SELECT, c"\x1b[4~", None),
        (LEFT, c"\x1b[D", Some(c"\x1b[d")),
        (RIGHT, c"\x1b[C", Some(c"\x1b[c")),
    ],
    f_keys: &[
        Some(c"\x1b[11~"),
        Some(c"\x1b[12~"),
        Some(c"\x1b[13~"),
        Some(c"\x1b[14~"),
        Some(c"\x1b[15~"),
        Some(c"\x1b[17~"),
        Some(c"\x1b[18~"),
        Some(c"\x1b[19~"),
        Some(c"\x1b[20~"),
        Some(c"\x1b[21~"),
        Some(c"\x1b[23~"),
        Some(c"\x1b[24~"),
        Some(c"\x1b[25~"),
        Some(c"\x1b[26~"),
        Some(c"\x1b[28~"),
        Some(c"\x1b[29~"),
        Some(c"\x1b[31~"),
        Some(c"\x1b[32~"),
        Some(c"\x1b[33~"),
        Some(c"\x1b[34~"),
        Some(c"\x1b[23$"),
        Some(c"\x1b[24$"),
        Some(c"\x1b[11^"),
        Some(c"\x1b[12^"),
        Some(c"\x1b[13^"),
        Some(c"\x1b[14^"),
        Some(c"\x1b[15^"),
        Some(c"\x1b[17^"),
        Some(c"\x1b[18^"),
        Some(c"\x1b[19^"),
        Some(c"\x1b[20^"),
        Some(c"\x1b[21^"),
        Some(c"\x1b[23^"),
        Some(c"\x1b[24^"),
        Some(c"\x1b[25^"),
        Some(c"\x1b[26^"),
        Some(c"\x1b[28^"),
        Some(c"\x1b[29^"),
        Some(c"\x1b[31^"),
        Some(c"\x1b[32^"),
        Some(c"\x1b[33^"),
        Some(c"\x1b[34^"),
        Some(c"\x1b[23@"),
        Some(c"\x1b[24@"),
    ],
};

/// suckless' st.
pub static ST_256COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h"),
        (kTerm_enter_dim_mode, c"\x1b[2m"),
        (kTerm_enter_italics_mode, c"\x1b[3m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_secure_mode, c"\x1b[8m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b[0m"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l"),
        (kTerm_from_status_line, c"\x07"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_keypad_local, c"\x1b[?1l\x1b>"),
        (kTerm_keypad_xmit, c"\x1b[?1h\x1b="),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m"),
        (kTerm_set_a_foreground, c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m"),
        (kTerm_set_attributes, c"%?%p9%t\x1b(0%e\x1b(B%;\x1b[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p7%t;8%;m"),
        (kTerm_to_status_line, c"\x1b]0;"),
        (kTerm_reset_cursor_style, c"\x1b[2 q"),
        (kTerm_set_cursor_style, c"\x1b[%p1%d q"),
        (kTerm_enter_strikethrough_mode, c"\x1b[9m"),
        (kTerm_set_cursor_color, c"\x1b]12;%p1%s\x07"),
    ],
    keys: &[
        (BACKSPACE, c"\x7f", None),
        (CLEAR, c"\x1b[3;5~", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3;2~")),
        (END, c"\x1b[4~", Some(c"\x1b[1;2F")),
        (HOME, c"\x1b[1~", Some(c"\x1b[1;2H")),
        (IC, c"\x1b[2~", Some(c"\x1b[2;2~")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (LEFT, c"\x1bOD", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1bOC", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1bOP"), Some(c"\x1bOQ"), Some(c"\x1bOR"), Some(c"\x1bOS"), Some(c"\x1b[15~"),
        Some(c"\x1b[17~"), Some(c"\x1b[18~"), Some(c"\x1b[19~"), Some(c"\x1b[20~"),
        Some(c"\x1b[21~"), Some(c"\x1b[23~"), Some(c"\x1b[24~"), Some(c"\x1b[1;2P"),
        Some(c"\x1b[1;2Q"), Some(c"\x1b[1;2R"), Some(c"\x1b[1;2S"), Some(c"\x1b[15;2~"),
        Some(c"\x1b[17;2~"), Some(c"\x1b[18;2~"), Some(c"\x1b[19;2~"), Some(c"\x1b[20;2~"),
        Some(c"\x1b[21;2~"), Some(c"\x1b[23;2~"), Some(c"\x1b[24;2~"), Some(c"\x1b[1;5P"),
        Some(c"\x1b[1;5Q"), Some(c"\x1b[1;5R"), Some(c"\x1b[1;5S"), Some(c"\x1b[15;5~"),
        Some(c"\x1b[17;5~"), Some(c"\x1b[18;5~"), Some(c"\x1b[19;5~"), Some(c"\x1b[20;5~"),
        Some(c"\x1b[21;5~"), Some(c"\x1b[23;5~"), Some(c"\x1b[24;5~"), Some(c"\x1b[1;6P"),
        Some(c"\x1b[1;6Q"), Some(c"\x1b[1;6R"), Some(c"\x1b[1;6S"), Some(c"\x1b[15;6~"),
        Some(c"\x1b[17;6~"), Some(c"\x1b[18;6~"), Some(c"\x1b[19;6~"), Some(c"\x1b[20;6~"),
        Some(c"\x1b[21;6~"), Some(c"\x1b[23;6~"), Some(c"\x1b[24;6~"), Some(c"\x1b[1;3P"),
        Some(c"\x1b[1;3Q"), Some(c"\x1b[1;3R"), Some(c"\x1b[1;3S"), Some(c"\x1b[15;3~"),
        Some(c"\x1b[17;3~"), Some(c"\x1b[18;3~"), Some(c"\x1b[19;3~"), Some(c"\x1b[20;3~"),
        Some(c"\x1b[21;3~"), Some(c"\x1b[23;3~"), Some(c"\x1b[24;3~"), Some(c"\x1b[1;4P"),
        Some(c"\x1b[1;4Q"), Some(c"\x1b[1;4R"),
    ],
};

/// VTE, the widget behind GNOME Terminal and its relatives.
pub static VTE_256COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h\x1b[22;0;0t"),
        (kTerm_enter_dim_mode, c"\x1b[2m"),
        (kTerm_enter_italics_mode, c"\x1b[3m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_secure_mode, c"\x1b[8m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b[0m\x0f"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l\x1b[23;0;0t"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_keypad_local, c"\x1b[?1l\x1b>"),
        (kTerm_keypad_xmit, c"\x1b[?1h\x1b="),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m"),
        (kTerm_set_a_foreground, c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m"),
        (kTerm_set_attributes, c"\x1b[0%?%p6%t;1%;%?%p2%t;4%;%?%p4%t;5%;%?%p5%t;2%;%?%p7%t;8%;%?%p1%p3%|%t;7%;m%?%p9%t^N%e\x0f%;"),
        (kTerm_reset_cursor_style, c"\x1b[1 q"),
        (kTerm_set_cursor_style, c"\x1b[%p1%d q"),
        (kTerm_enter_strikethrough_mode, c"\x1b[9m"),
        (kTerm_set_cursor_color, c"\x1b]12;%p1%s\x07"),
        (kTerm_reset_cursor_color, c"\x1b]112\x07"),
        (kTerm_set_underline_style, c"\x1b[4:%p1%dm"),
    ],
    keys: &[
        (BACKSPACE, c"\x7f", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3;2~")),
        (END, c"\x1bOF", Some(c"\x1b[1;2F")),
        (FIND, c"\x1b[1~", None),
        (HOME, c"\x1bOH", Some(c"\x1b[1;2H")),
        (IC, c"\x1b[2~", Some(c"\x1b[2;2~")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (SELECT, c"\x1b[4~", None),
        (LEFT, c"\x1bOD", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1bOC", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1bOP"), Some(c"\x1bOQ"), Some(c"\x1bOR"), Some(c"\x1bOS"), Some(c"\x1b[15~"),
        Some(c"\x1b[17~"), Some(c"\x1b[18~"), Some(c"\x1b[19~"), Some(c"\x1b[20~"),
        Some(c"\x1b[21~"), Some(c"\x1b[23~"), Some(c"\x1b[24~"), Some(c"\x1b[1;2P"),
        Some(c"\x1b[1;2Q"), Some(c"\x1b[1;2R"), Some(c"\x1b[1;2S"), Some(c"\x1b[15;2~"),
        Some(c"\x1b[17;2~"), Some(c"\x1b[18;2~"), Some(c"\x1b[19;2~"), Some(c"\x1b[20;2~"),
        Some(c"\x1b[21;2~"), Some(c"\x1b[23;2~"), Some(c"\x1b[24;2~"), Some(c"\x1b[1;5P"),
        Some(c"\x1b[1;5Q"), Some(c"\x1b[1;5R"), Some(c"\x1b[1;5S"), Some(c"\x1b[15;5~"),
        Some(c"\x1b[17;5~"), Some(c"\x1b[18;5~"), Some(c"\x1b[19;5~"), Some(c"\x1b[20;5~"),
        Some(c"\x1b[21;5~"), Some(c"\x1b[23;5~"), Some(c"\x1b[24;5~"), Some(c"\x1b[1;6P"),
        Some(c"\x1b[1;6Q"), Some(c"\x1b[1;6R"), Some(c"\x1b[1;6S"), Some(c"\x1b[15;6~"),
        Some(c"\x1b[17;6~"), Some(c"\x1b[18;6~"), Some(c"\x1b[19;6~"), Some(c"\x1b[20;6~"),
        Some(c"\x1b[21;6~"), Some(c"\x1b[23;6~"), Some(c"\x1b[24;6~"), Some(c"\x1b[1;3P"),
        Some(c"\x1b[1;3Q"), Some(c"\x1b[1;3R"), Some(c"\x1b[1;3S"), Some(c"\x1b[15;3~"),
        Some(c"\x1b[17;3~"), Some(c"\x1b[18;3~"), Some(c"\x1b[19;3~"), Some(c"\x1b[20;3~"),
        Some(c"\x1b[21;3~"), Some(c"\x1b[23;3~"), Some(c"\x1b[24;3~"), Some(c"\x1b[1;4P"),
        Some(c"\x1b[1;4Q"), Some(c"\x1b[1;4R"),
    ],
};

/// xterm.
pub static XTERM_256COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?12l\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h\x1b[22;0;0t"),
        (kTerm_enter_dim_mode, c"\x1b[2m"),
        (kTerm_enter_italics_mode, c"\x1b[3m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_secure_mode, c"\x1b[8m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b(B\x1b[m"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l\x1b[23;0;0t"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_keypad_local, c"\x1b[?1l\x1b>"),
        (kTerm_keypad_xmit, c"\x1b[?1h\x1b="),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m"),
        (kTerm_set_a_foreground, c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m"),
        (kTerm_set_attributes, c"%?%p9%t\x1b(0%e\x1b(B%;\x1b[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m"),
        (kTerm_set_lr_margin, c"\x1b[?69h\x1b[%i%p1%d;%p2%ds"),
        (kTerm_reset_cursor_style, c"\x1b[2 q"),
        (kTerm_set_cursor_style, c"\x1b[%p1%d q"),
        (kTerm_enter_strikethrough_mode, c"\x1b[9m"),
        (kTerm_set_cursor_color, c"\x1b]12;%p1%s\x07"),
        (kTerm_reset_cursor_color, c"\x1b]112\x07"),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (BEG, c"\x1bOE", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3;2~")),
        (END, c"\x1bOF", Some(c"\x1b[1;2F")),
        (HOME, c"\x1bOH", Some(c"\x1b[1;2H")),
        (IC, c"\x1b[2~", Some(c"\x1b[2;2~")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (LEFT, c"\x1bOD", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1bOC", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1bOP"), Some(c"\x1bOQ"), Some(c"\x1bOR"), Some(c"\x1bOS"), Some(c"\x1b[15~"),
        Some(c"\x1b[17~"), Some(c"\x1b[18~"), Some(c"\x1b[19~"), Some(c"\x1b[20~"),
        Some(c"\x1b[21~"), Some(c"\x1b[23~"), Some(c"\x1b[24~"), Some(c"\x1b[1;2P"),
        Some(c"\x1b[1;2Q"), Some(c"\x1b[1;2R"), Some(c"\x1b[1;2S"), Some(c"\x1b[15;2~"),
        Some(c"\x1b[17;2~"), Some(c"\x1b[18;2~"), Some(c"\x1b[19;2~"), Some(c"\x1b[20;2~"),
        Some(c"\x1b[21;2~"), Some(c"\x1b[23;2~"), Some(c"\x1b[24;2~"), Some(c"\x1b[1;5P"),
        Some(c"\x1b[1;5Q"), Some(c"\x1b[1;5R"), Some(c"\x1b[1;5S"), Some(c"\x1b[15;5~"),
        Some(c"\x1b[17;5~"), Some(c"\x1b[18;5~"), Some(c"\x1b[19;5~"), Some(c"\x1b[20;5~"),
        Some(c"\x1b[21;5~"), Some(c"\x1b[23;5~"), Some(c"\x1b[24;5~"), Some(c"\x1b[1;6P"),
        Some(c"\x1b[1;6Q"), Some(c"\x1b[1;6R"), Some(c"\x1b[1;6S"), Some(c"\x1b[15;6~"),
        Some(c"\x1b[17;6~"), Some(c"\x1b[18;6~"), Some(c"\x1b[19;6~"), Some(c"\x1b[20;6~"),
        Some(c"\x1b[21;6~"), Some(c"\x1b[23;6~"), Some(c"\x1b[24;6~"), Some(c"\x1b[1;3P"),
        Some(c"\x1b[1;3Q"), Some(c"\x1b[1;3R"), Some(c"\x1b[1;3S"), Some(c"\x1b[15;3~"),
        Some(c"\x1b[17;3~"), Some(c"\x1b[18;3~"), Some(c"\x1b[19;3~"), Some(c"\x1b[20;3~"),
        Some(c"\x1b[21;3~"), Some(c"\x1b[23;3~"), Some(c"\x1b[24;3~"), Some(c"\x1b[1;4P"),
        Some(c"\x1b[1;4Q"), Some(c"\x1b[1;4R"),
    ],
};
