//! `:helptags`: reading a directory of help files and writing the tags
//! files a `:help` lookup then searches.
//!
//! One directory can hold help in several languages, distinguished by the
//! file suffix (`.txt` is English, `.frx` is French), and each language gets
//! its own tags file (`tags`, `tags-fr`). [`ex_helptags`] finds the
//! languages, [`helptags_one`] writes one file per language.
//!
//! **The output format is the contract.** `runtime/doc/tags` in this
//! repository is generated by this code and read back by `find_tags`, so a
//! line is exactly `<tag>\t<file>\t/*<tag with \ and / escaped>*\n` and the
//! entries are in `strcmp` order. The one exception is the `help-tags` entry
//! (`help-tags\t<tagfile>\t1\n`), which is built in final form and written
//! verbatim.
//!
//! Like the rest of the module this works in `NameBuff` -- the glob goes in,
//! `gen_expand_wildcards` reads it back out, then the same buffer becomes
//! the output path -- and reads each help line into `IObuff`. Nothing
//! reached from here wants either buffer meanwhile.
//!
//! Original: `src/nvim/help.c`, Vim/Neovim, Vim license.

#![deny(unsafe_op_in_unsafe_fn)]

use crate::ascii::{ascii_isalpha, ascii_isdigit, ascii_iswhite};
use crate::charset::skipwhite;
use crate::cmdexpand::{ExpandInit, ExpandOne, WildMode, WildOpts};
use crate::fileio::vim_fgets;
use crate::main::{IObuff, NameBuff, e_fnametoolong, got_int, p_rtp};
use crate::memory::{xfree, xmalloc, xstrlcat, xstrlcpy};
use crate::message::emsg;
use crate::os::cshim::{gettext, putc, snprintf, strchr, strncmp};
use crate::os::fs::{os_fopen, os_isdir};
use crate::os::input::line_breakcheck;
use crate::path::{ExpandFlags, FreeWild, add_pathsep, gen_expand_wildcards, path_full_compare};
use crate::runtime::{DIP_ALL, DIP_DIR, do_in_path};
use crate::semsg_c;
use crate::strings::{sort_strings, vim_snprintf, vim_strchr};
use crate::types::{FAIL, FILE, IOSIZE, MAXPATHL, NUL, exarg_T, expand_T, size_t, uint8_t};
use ::libc::{fclose, fprintf, fputs, memcpy, strcasecmp, strcmp, strlen};
use core::ffi::{CStr, c_char, c_int, c_void};
use core::ptr;

use super::flag::{EXPAND_DIRECTORIES, kEqualFiles};

/// `msg`, translated.  A helper rather than `gettext(..).as_ptr()` spelled
/// out at each site: written that way, the five calls below each wrap onto
/// four lines.
fn translated(msg: &CStr) -> *const c_char {
    // SAFETY: `msg` is a NUL-terminated literal.
    unsafe { gettext(msg.as_ptr()) }
}

/// `:helptags [++t] {dir}`, or `:helptags ALL` for every `doc` directory in
/// 'runtimepath'.
///
/// # Safety
/// `eap` is the current Ex command with a writable NUL-terminated argument.
pub unsafe fn ex_helptags(eap: *mut exarg_T) {
    let mut add_help_tags = false;
    // SAFETY: caller contract.
    unsafe {
        if strncmp((*eap).arg, c"++t".as_ptr(), 3) == 0
            && ascii_iswhite(*(*eap).arg.offset(3) as c_int)
        {
            add_help_tags = true;
            (*eap).arg = skipwhite((*eap).arg.offset(3));
        }

        if strcmp((*eap).arg, c"ALL".as_ptr()) == 0 {
            do_in_path(
                p_rtp.get(),
                c"".as_ptr(),
                c"doc".as_ptr().cast_mut(),
                (DIP_ALL + DIP_DIR) as c_int,
                Some(helptags_cb),
                (&raw mut add_help_tags).cast::<c_void>(),
            );
            return;
        }

        let mut xpc: expand_T = core::mem::zeroed();
        ExpandInit(&raw mut xpc);
        xpc.xp_context = EXPAND_DIRECTORIES;
        let dirname = ExpandOne(
            &raw mut xpc,
            (*eap).arg,
            ptr::null_mut(),
            WildOpts::LIST_NOTFOUND | WildOpts::SILENT,
            WildMode::ExpandFree,
        );
        if dirname.is_null() || !os_isdir(dirname) {
            semsg_c!(translated(c"E150: Not a directory: %s"), (*eap).arg);
        } else {
            do_helptags(dirname, add_help_tags, false);
        }
        xfree(dirname.cast::<c_void>());
    }
}

/// `do_in_path` callback for `:helptags ALL`: generate tags in each `doc`
/// directory it hands us.
///
/// # Safety
/// `fnames` holds `num_fnames` NUL-terminated directory names and `cookie`
/// points at the caller's `bool`.
unsafe fn helptags_cb(
    num_fnames: c_int,
    fnames: *mut *mut c_char,
    all: bool,
    cookie: *mut c_void,
) -> bool {
    // SAFETY: caller contract.
    unsafe {
        for i in 0..num_fnames {
            do_helptags(*fnames.offset(i as isize), *cookie.cast::<bool>(), true);
            if !all {
                return true;
            }
        }
    }
    num_fnames > 0
}

/// Generate the tags files for one help directory, one per language found
/// in it. English uses `.txt` and `tags`; a language `ab` uses `.abx` and
/// `tags-ab`.
///
/// # Safety
/// `dirname` is NUL-terminated. Main thread.
unsafe fn do_helptags(dirname: *mut c_char, add_help_tags: bool, ignore_writeerr: bool) {
    let namebuff = NameBuff.ptr().cast::<c_char>();
    // SAFETY: `NameBuff` is the shared path scratch buffer; nothing between
    // here and `gen_expand_wildcards` reading it wants it too.
    let files = unsafe {
        xstrlcpy(namebuff, dirname, MAXPATHL as usize);
        if !add_pathsep(namebuff)
            || xstrlcat(namebuff, c"**".as_ptr(), MAXPATHL as usize) >= MAXPATHL as usize
        {
            emsg(gettext(e_fnametoolong.as_ptr()));
            return;
        }
        match expand_help_files(namebuff) {
            Some(files) => files,
            None => {
                semsg_c!(translated(c"E151: No match: %s"), namebuff);
                return;
            }
        }
    };

    // Which languages does the directory hold?
    let mut langs: Vec<[c_char; 2]> = Vec::new();
    // SAFETY: `files` holds NUL-terminated names.
    unsafe {
        for i in 0..files.count {
            if let Some(lang) = help_file_lang(*files.names.offset(i as isize)) {
                if !langs.contains(&lang) {
                    langs.push(lang);
                }
            }
        }
    }

    for lang in langs {
        let mut fname = *b"tags-xx\0";
        let mut ext = *b".xxx\0";
        if lang == [b'e' as c_char, b'n' as c_char] {
            // English is the exception: ".txt" and "tags".
            fname[4] = 0;
            ext = *b".txt\0";
        } else {
            fname[5] = lang[0] as u8;
            fname[6] = lang[1] as u8;
            ext[1] = lang[0] as u8;
            ext[2] = lang[1] as u8;
        }
        // SAFETY: both buffers are NUL-terminated by construction, and
        // `dirname` by the caller.
        unsafe {
            helptags_one(
                dirname,
                ext.as_ptr().cast::<c_char>(),
                fname.as_ptr().cast::<c_char>(),
                add_help_tags,
                ignore_writeerr,
            );
        }
    }
    drop(files);
}

/// The language a help file's name says it is in: `.txt` is English, and
/// `.abx` is the language `ab`. Anything else has no language.
///
/// # Safety
/// `name` is NUL-terminated.
unsafe fn help_file_lang(name: *const c_char) -> Option<[c_char; 2]> {
    // SAFETY: caller contract; every read is within the name's length.
    unsafe {
        let len = strlen(name) as isize;
        if len <= 4 {
            return None;
        }
        let tail = name.offset(len - 4);
        if strcasecmp(tail, c".txt".as_ptr()) == 0 {
            return Some([b'e' as c_char, b'n' as c_char]);
        }
        let (a, b, x) = (*tail.offset(1), *tail.offset(2), *tail.offset(3));
        if *tail == b'.' as c_char
            && ascii_isalpha(a as c_int)
            && ascii_isalpha(b as c_int)
            && to_lower(x) == b'x' as c_char
        {
            return Some([to_lower(a), to_lower(b)]);
        }
        None
    }
}

/// `TOLOWER_ASC`: lowercase an ASCII letter, leaving everything else alone.
fn to_lower(c: c_char) -> c_char {
    if c >= b'A' as c_char && c <= b'Z' as c_char {
        c + (b'a' - b'A') as c_char
    } else {
        c
    }
}

/// A `gen_expand_wildcards` result, freed with `FreeWild` when dropped.
struct Wildcards {
    count: c_int,
    names: *mut *mut c_char,
}

impl Drop for Wildcards {
    fn drop(&mut self) {
        // SAFETY: `names` is `gen_expand_wildcards`'s own allocation of
        // `count` strings, and nothing else owns it.
        unsafe { FreeWild(self.count, self.names) };
    }
}

/// Expand the glob in `pattern`, or `None` when it matched nothing. The
/// caller reports the failure: the two callers word it differently.
///
/// # Safety
/// `pattern` is NUL-terminated.
unsafe fn expand_help_files(pattern: *mut c_char) -> Option<Wildcards> {
    let mut count: c_int = 0;
    let mut names: *mut *mut c_char = ptr::null_mut();
    // Note: the pattern is passed as a one-element array, not as `&pattern`,
    // because in C `NameBuff` and `&NameBuff` are the same address.
    let mut list = [pattern];
    // SAFETY: caller contract; the out-parameters are ours.
    let res = unsafe {
        gen_expand_wildcards(
            1,
            list.as_mut_ptr(),
            &raw mut count,
            &raw mut names,
            ExpandFlags::FILE | ExpandFlags::SILENT,
        )
    };
    if res == FAIL {
        return None;
    }
    let found = Wildcards { count, names };
    if count == 0 { None } else { Some(found) }
}

/// Generate one tags file.
///
/// `ext` is the suffix of the help files (`.txt`, `.itx`, ...) and
/// `tagfname` the name of the tags file (`tags`, `tags-fr`, ...).
/// `add_help_tags` adds the `help-tags` tag, which `$VIMRUNTIME/doc` gets
/// anyway; `ignore_writeerr` silences the "cannot open for writing" error,
/// which `:helptags ALL` wants for read-only runtime directories.
///
/// # Safety
/// All three strings are NUL-terminated. Main thread.
unsafe fn helptags_one(
    dir: *mut c_char,
    ext: *const c_char,
    tagfname: *const c_char,
    add_help_tags: bool,
    ignore_writeerr: bool,
) {
    let namebuff = NameBuff.ptr().cast::<c_char>();
    // Find all the help files: "<dir>/**/*<ext>".
    // SAFETY: `NameBuff` is the shared path scratch buffer, and this owns it
    // until `gen_expand_wildcards` has read the glob back out.
    let (dirlen, files) = unsafe {
        let dirlen = xstrlcpy(namebuff, dir, MAXPATHL as usize);
        if dirlen >= MAXPATHL as usize
            || xstrlcat(namebuff, c"/**/*".as_ptr(), MAXPATHL as usize) >= MAXPATHL as usize
            || xstrlcat(namebuff, ext, MAXPATHL as usize) >= MAXPATHL as usize
        {
            emsg(gettext(e_fnametoolong.as_ptr()));
            return;
        }
        match expand_help_files(namebuff) {
            Some(files) => (dirlen, files),
            None => {
                if !got_int.get() {
                    semsg_c!(translated(c"E151: No match: %s"), namebuff);
                }
                return;
            }
        }
    };

    // Open the tags file for writing before scanning, so that a directory
    // we cannot write to costs nothing.
    let (into, from, n) = (namebuff.cast::<c_void>(), dir.cast(), dirlen as size_t + 1);
    // SAFETY: `dir` is `dirlen` bytes plus its NUL, so the copy fits.
    let fd_tags = unsafe {
        memcpy(into, from, n);
        if !add_pathsep(namebuff)
            || xstrlcat(namebuff, tagfname, MAXPATHL as usize) >= MAXPATHL as usize
        {
            emsg(gettext(e_fnametoolong.as_ptr()));
            // Upstream leaks `files` here; the `Wildcards` drop frees it.
            return;
        }
        let fd_tags = os_fopen(namebuff, c"w".as_ptr());
        if fd_tags.is_null() {
            if !ignore_writeerr {
                semsg_c!(translated(c"E152: Cannot open %s for writing"), namebuff);
            }
            return;
        }
        fd_tags
    };

    // Every tag, as an owned "<tag>\t<file>" line.
    let mut tags: Vec<*mut c_char> = Vec::new();
    // SAFETY: `tagfname` is NUL-terminated and `dir` a directory name.
    unsafe {
        if add_help_tags
            || path_full_compare(c"$VIMRUNTIME/doc".as_ptr().cast_mut(), dir, false, true)
                == kEqualFiles
        {
            let len = 18 + strlen(tagfname);
            let entry = xmalloc(len).cast::<c_char>();
            snprintf(entry, len, c"help-tags\t%s\t1\n".as_ptr(), tagfname);
            tags.push(entry);
        }
    }

    // SAFETY: `files` holds NUL-terminated names all starting with `dir`.
    unsafe {
        for fi in 0..files.count {
            if got_int.get() {
                break;
            }
            let path = *files.names.offset(fi as isize);
            let fd = os_fopen(path, c"r".as_ptr());
            if fd.is_null() {
                semsg_c!(translated(c"E153: Unable to open %s for reading"), path);
                continue;
            }
            scan_help_file(fd, path.add(dirlen).offset(1), &mut tags);
            fclose(fd);
        }
    }
    drop(files);

    if !got_int.get() && !tags.is_empty() {
        // SAFETY: every entry is an owned NUL-terminated line, and
        // `fd_tags` is open for writing.
        unsafe {
            sort_strings(tags.as_mut_ptr(), tags.len() as c_int);
            report_duplicates(&tags, dir);
            write_tags(fd_tags, &tags);
        }
    }

    for entry in tags {
        // SAFETY: each entry was allocated by `xmalloc` above.
        unsafe { xfree(entry.cast::<c_void>()) };
    }
    // There is no check for a write error, as upstream.
    // SAFETY: `fd_tags` is open and nothing else holds it.
    unsafe { fclose(fd_tags) };
}

/// Read one help file, appending a `"<tag>\t<fname>"` entry to `tags` for
/// every `*tag*` in it.
///
/// A tag is only accepted when it holds no space, tab or `|`, has
/// whitespace or the line start before it, and whitespace or the line end
/// after it. Lines inside an example — everything indented after a line
/// ending in `>` — are skipped.
///
/// # Safety
/// `fd` is open for reading and `fname` NUL-terminated. Uses `IObuff`.
unsafe fn scan_help_file(fd: *mut FILE, fname: *const c_char, tags: &mut Vec<*mut c_char>) {
    let iobuff = IObuff.ptr().cast::<c_char>();
    let mut in_example = false;
    // SAFETY: `vim_fgets` NUL-terminates `IObuff` within `IOSIZE` bytes, and
    // every pointer below stays between its start and that NUL.
    unsafe {
        while !vim_fgets(iobuff, IOSIZE, fd) && !got_int.get() {
            if in_example {
                // Skip the example; a non-white in the first column ends it.
                if !vim_strchr(c" \t\n\r".as_ptr(), *iobuff as uint8_t as c_int).is_null() {
                    continue;
                }
                in_example = false;
            }

            let mut p1 = vim_strchr(iobuff, b'*' as c_int);
            while !p1.is_null() {
                let mut p2 = strchr(p1.offset(1), b'*' as c_int);
                // Skip "*" and "**".
                if !p2.is_null() && p2 > p1.offset(1) {
                    let mut s = p1.offset(1);
                    while s < p2
                        && *s != b' ' as c_char
                        && *s != b'\t' as c_char
                        && *s != b'|' as c_char
                    {
                        s = s.offset(1);
                    }
                    // Only accept a *tag* made of valid characters, with
                    // white space before it and a white character or the end
                    // of the line after it. The order matters: `p1[-1]` is
                    // only in bounds once `p1 != iobuff` has been ruled out.
                    if s == p2
                        && (p1 == iobuff
                            || *p1.offset(-1) == b' ' as c_char
                            || *p1.offset(-1) == b'\t' as c_char)
                        && (!vim_strchr(c" \t\n\r".as_ptr(), *s.offset(1) as uint8_t as c_int)
                            .is_null()
                            || *s.offset(1) == NUL as c_char)
                    {
                        *p2 = NUL as c_char;
                        p1 = p1.offset(1);
                        let len = p2.offset_from(p1) as size_t + strlen(fname) + 2;
                        let entry = xmalloc(len).cast::<c_char>();
                        tags.push(entry);
                        snprintf(entry, len, c"%s\t%s".as_ptr(), p1, fname);
                        // Find the next '*'.
                        p2 = vim_strchr(p2.offset(1), b'*' as c_int);
                    }
                }
                p1 = p2;
            }

            // A line ending in ">" — optionally with a `:lang` tail — opens
            // an example.
            let mut off = strlen(iobuff);
            if off >= 2 && *iobuff.add(off - 1) == b'\n' as c_char {
                off -= 2;
                while off > 0
                    && (is_lower(*iobuff.add(off)) || ascii_isdigit(*iobuff.add(off) as c_int))
                {
                    off -= 1;
                }
                if *iobuff.add(off) == b'>' as c_char
                    && (off == 0 || *iobuff.add(off - 1) == b' ' as c_char)
                {
                    in_example = true;
                }
            }
            line_breakcheck();
        }
    }
}

/// ASCII lowercase letter, the `ASCII_ISLOWER` of the C.
fn is_lower(c: c_char) -> bool {
    c >= b'a' as c_char && c <= b'z' as c_char
}

/// Report every tag defined twice. The entries are sorted, so duplicates
/// are adjacent; two entries are the same tag when they agree up to the tab
/// that separates the tag from its file name.
///
/// # Safety
/// Every entry is a NUL-terminated `"<tag>\t<file>"` line; `dir` is
/// NUL-terminated.
unsafe fn report_duplicates(tags: &[*mut c_char], dir: *const c_char) {
    let namebuff = NameBuff.ptr().cast::<c_char>();
    // SAFETY: caller contract. The tab is restored before returning, so the
    // entry is still a whole line for the writer below.
    unsafe {
        for pair in tags.windows(2) {
            let (mut p1, mut p2) = (pair[0], pair[1]);
            while *p1 == *p2 {
                if *p2 != b'\t' as c_char {
                    p1 = p1.offset(1);
                    p2 = p2.offset(1);
                    continue;
                }
                *p2 = NUL as c_char;
                vim_snprintf(
                    namebuff,
                    MAXPATHL as size_t,
                    c"E154: Duplicate tag \"%s\" in file %s/%s".as_ptr(),
                    pair[1],
                    dir,
                    p2.offset(1),
                );
                emsg(namebuff);
                *p2 = b'\t' as c_char;
                break;
            }
        }
    }
}

/// Write the sorted entries out as a tags file. Each becomes
/// `"<tag>\t<file>\t/*<tag>*\n"`, with `\` and `/` escaped inside the
/// search pattern; the `help-tags` entry was built in final form already.
///
/// # Safety
/// `fd` is open for writing and every entry a NUL-terminated
/// `"<tag>\t<file>"` line.
unsafe fn write_tags(fd: *mut FILE, tags: &[*mut c_char]) {
    // SAFETY: caller contract.
    unsafe {
        for &entry in tags {
            if strncmp(entry, c"help-tags\t".as_ptr(), 10) == 0 {
                fputs(entry, fd);
                continue;
            }
            fprintf(fd, c"%s\t/*".as_ptr(), entry);
            let mut p = entry;
            while *p != b'\t' as c_char {
                if *p == b'\\' as c_char || *p == b'/' as c_char {
                    putc(b'\\' as c_int, fd);
                }
                putc(*p as c_int, fd);
                p = p.offset(1);
            }
            fprintf(fd, c"*\n".as_ptr());
        }
    }
}
