//! `:helptags`: reading a directory of help files and writing the tags
//! files a `:help` lookup then searches.
//!
//! One directory can hold help in several languages, distinguished by the
//! file suffix (`.txt` is English, `.frx` is French), and each language gets
//! its own tags file (`tags`, `tags-fr`). [`ex_helptags`] finds the
//! languages, [`helptags_one`] writes one file per language.
//!
//! **The output format is the contract.** `runtime/doc/tags` in this
//! repository is generated by this code and read back by `find_tags`, so a
//! line is exactly `<tag>\t<file>\t/*<tag with \ and / escaped>*\n` and the
//! entries are in `strcmp` order. The one exception is the `help-tags` entry
//! (`help-tags\t<tagfile>\t1\n`), which is built in final form and written
//! verbatim.
//!
//! Each step owns the buffer it works in: the glob goes into a local,
//! `gen_expand_wildcards` reads it back out, and the same buffer becomes the
//! output path. Upstream uses the shared `NameBuff`/`IObuff` for all of it.
//!
//! Original: `src/nvim/help.c`, Vim/Neovim, Vim license.

#![deny(unsafe_op_in_unsafe_fn)]

use crate::ascii::{ascii_isalpha, ascii_isdigit, ascii_iswhite};
use crate::charset::skipwhite;
use crate::cmdexpand::{WildMode, WildOpts, expand_init, expand_one};
use crate::cstr;
use crate::fileio::vim_fgets;
use crate::main::{e_fnametoolong, got_int, p_rtp};
use crate::memory::{xfree, xmalloc, xstrlcat, xstrlcpy};
use crate::message::{emsg, emsg_ptr};
use crate::message_fmt::c_str;
use crate::os::cshim::{gettext, putc, snprintf, strchr};
use crate::os::fs::{os_fopen, os_isdir};
use crate::os::input::line_breakcheck;
use crate::path::{ExpandFlags, add_pathsep, free_wild, gen_expand_wildcards, path_full_compare};
use crate::runtime::{RuntimeOpts, do_in_path};
use crate::semsg;
use crate::strings::{sort_strings, vim_snprintf, vim_strchr};
use crate::types::{
    ExpandContext, FILE, IOSIZE, MAXPATHL, NUL, exarg_T, expand_T, size_t, uint8_t,
};
use ::libc::{fclose, fprintf, fputs, strcasecmp};
use core::ffi::{c_char, c_int, c_void};
use core::ptr;

use super::flag::kEqualFiles;

/// `:helptags [++t] {dir}`, or `:helptags ALL` for every `doc` directory in
/// 'runtimepath'.
///
/// # Safety
/// `eap` is the current Ex command with a writable NUL-terminated argument.
pub(crate) unsafe fn ex_helptags(eap: *mut exarg_T) {
    let mut add_help_tags = false;
    // SAFETY: caller contract.
    if unsafe { cstr::starts_with((*eap).arg, b"++t") }
        && ascii_iswhite(unsafe { *(*eap).arg.offset(3) } as c_int)
    {
        add_help_tags = true;
        unsafe { (*eap).arg = skipwhite((*eap).arg.offset(3)) };
    }

    if unsafe { cstr::eq_bytes((*eap).arg, b"ALL") } {
        let (rtp, none, doc) = (p_rtp.get(), c"".as_ptr(), c"doc".as_ptr().cast_mut());
        let opts = RuntimeOpts::ALL | RuntimeOpts::DIR;
        let flag = (&raw mut add_help_tags).cast::<c_void>();
        // SAFETY: `flag` outlives the walk, which is the callback's only
        // argument; the rest are static strings and the runtimepath.
        unsafe { do_in_path(rtp, none, doc, opts, Some(helptags_cb), flag) };
        return;
    }

    let mut xpc: expand_T = unsafe { core::mem::zeroed() };
    unsafe { expand_init(&raw mut xpc) };
    xpc.xp_context = ExpandContext::Directories;
    let arg = unsafe { (*eap).arg };
    let opts = WildOpts::LIST_NOTFOUND | WildOpts::SILENT;
    let (orig, mode) = (ptr::null_mut(), WildMode::ExpandFree);
    // SAFETY: `xpc` was just initialised and `arg` is the command's own.
    let dirname = unsafe { expand_one(&raw mut xpc, arg, orig, opts, mode) };
    if dirname.is_null() || !unsafe { os_isdir(dirname) } {
        // SAFETY: a message argument the caller holds as a NUL-terminated string.
        let arg = unsafe { c_str((*eap).arg) };
        semsg!("E150: Not a directory: {arg}");
    } else {
        unsafe { do_helptags(dirname, add_help_tags, false) };
    }
    unsafe { xfree(dirname.cast::<c_void>()) };
}

/// `do_in_path` callback for `:helptags ALL`: generate tags in each `doc`
/// directory it hands us.
///
/// # Safety
/// `fnames` holds `num_fnames` NUL-terminated directory names and `cookie`
/// points at the caller's `bool`.
unsafe fn helptags_cb(
    num_fnames: c_int,
    fnames: *mut *mut c_char,
    all: bool,
    cookie: *mut c_void,
) -> bool {
    // SAFETY: caller contract.
    for i in 0..num_fnames {
        unsafe { do_helptags(*fnames.offset(i as isize), *cookie.cast::<bool>(), true) };
        if !all {
            return true;
        }
    }
    num_fnames > 0
}

/// Generate the tags files for one help directory, one per language found
/// in it. English uses `.txt` and `tags`; a language `ab` uses `.abx` and
/// `tags-ab`.
///
/// # Safety
/// `dirname` is NUL-terminated. Main thread.
unsafe fn do_helptags(dirname: *mut c_char, add_help_tags: bool, ignore_writeerr: bool) {
    let mut glob = [0 as c_char; MAXPATHL as usize];
    let namebuff = glob.as_mut_ptr();
    // SAFETY: `glob` is `MAXPATHL` bytes and outlives the expansion below,
    // and `dirname` is the caller's NUL-terminated string.
    unsafe { xstrlcpy(namebuff, dirname, MAXPATHL as usize) };
    let too_long = !unsafe { add_pathsep(namebuff) }
        || unsafe { xstrlcat(namebuff, c"**".as_ptr(), MAXPATHL as usize) } >= MAXPATHL as usize;
    if too_long {
        emsg(gettext(e_fnametoolong));
        return;
    }
    let Some(files) = (unsafe { expand_help_files(namebuff) }) else {
        // SAFETY: a message argument the caller holds as a NUL-terminated string.
        let namebuff = unsafe { c_str(namebuff) };
        semsg!("E151: No match: {namebuff}");
        return;
    };

    // Which languages does the directory hold?
    let mut langs: Vec<[c_char; 2]> = Vec::new();
    // SAFETY: `files` holds NUL-terminated names.
    for i in 0..files.count {
        if let Some(lang) = unsafe { help_file_lang(*files.names.offset(i as isize)) }
            && !langs.contains(&lang)
        {
            langs.push(lang);
        }
    }

    for lang in langs {
        let mut fname = *b"tags-xx\0";
        let mut ext = *b".xxx\0";
        if lang == [b'e' as c_char, b'n' as c_char] {
            // English is the exception: ".txt" and "tags".
            fname[4] = 0;
            ext = *b".txt\0";
        } else {
            fname[5] = lang[0] as u8;
            fname[6] = lang[1] as u8;
            ext[1] = lang[0] as u8;
            ext[2] = lang[1] as u8;
        }
        // SAFETY: both buffers are NUL-terminated by construction, and
        // `dirname` by the caller.
        let ext = ext.as_ptr().cast::<c_char>();
        let fname = fname.as_ptr().cast::<c_char>();
        unsafe { helptags_one(dirname, ext, fname, add_help_tags, ignore_writeerr) };
    }
    drop(files);
}

/// The language a help file's name says it is in: `.txt` is English, and
/// `.abx` is the language `ab`. Anything else has no language.
///
/// # Safety
/// `name` is NUL-terminated.
unsafe fn help_file_lang(name: *const c_char) -> Option<[c_char; 2]> {
    // SAFETY: caller contract; every read is within the name's length.
    let len = unsafe { cstr::bytes_at(name) }.len() as isize;
    if len <= 4 {
        return None;
    }
    let tail = unsafe { name.offset(len - 4) };
    if unsafe { strcasecmp(tail, c".txt".as_ptr()) } == 0 {
        return Some([b'e' as c_char, b'n' as c_char]);
    }
    let (a, b, x) = (
        unsafe { *tail.offset(1) },
        unsafe { *tail.offset(2) },
        unsafe { *tail.offset(3) },
    );
    if unsafe { *tail } == b'.' as c_char
        && ascii_isalpha(a as c_int)
        && ascii_isalpha(b as c_int)
        && to_lower(x) == b'x' as c_char
    {
        return Some([to_lower(a), to_lower(b)]);
    }
    None
}

/// `TOLOWER_ASC`: lowercase an ASCII letter, leaving everything else alone.
fn to_lower(c: c_char) -> c_char {
    if c >= b'A' as c_char && c <= b'Z' as c_char {
        c + (b'a' - b'A') as c_char
    } else {
        c
    }
}

/// A `gen_expand_wildcards` result, freed with `free_wild` when dropped.
struct Wildcards {
    count: c_int,
    names: *mut *mut c_char,
}

impl Drop for Wildcards {
    fn drop(&mut self) {
        // SAFETY: `names` is `gen_expand_wildcards`'s own allocation of
        // `count` strings, and nothing else owns it.
        unsafe { free_wild(self.count, self.names) };
    }
}

/// Expand the glob in `pattern`, or `None` when it matched nothing. The
/// caller reports the failure: the two callers word it differently.
///
/// # Safety
/// `pattern` is NUL-terminated.
unsafe fn expand_help_files(pattern: *mut c_char) -> Option<Wildcards> {
    let mut count: c_int = 0;
    let mut names: *mut *mut c_char = ptr::null_mut();
    // Note: the pattern is passed as a one-element array, not as `&pattern`,
    // because in C `NameBuff` and `&NameBuff` are the same address.
    let mut list = [pattern];
    let flags = ExpandFlags::FILE | ExpandFlags::SILENT;
    let (out_count, out_names) = (&raw mut count, &raw mut names);
    // SAFETY: caller contract; the out-parameters are ours.
    let res = unsafe { gen_expand_wildcards(1, list.as_mut_ptr(), out_count, out_names, flags) };
    if res.is_err() {
        return None;
    }
    let found = Wildcards { count, names };
    if count == 0 { None } else { Some(found) }
}

/// Generate one tags file.
///
/// `ext` is the suffix of the help files (`.txt`, `.itx`, ...) and
/// `tagfname` the name of the tags file (`tags`, `tags-fr`, ...).
/// `add_help_tags` adds the `help-tags` tag, which `$VIMRUNTIME/doc` gets
/// anyway; `ignore_writeerr` silences the "cannot open for writing" error,
/// which `:helptags ALL` wants for read-only runtime directories.
///
/// # Safety
/// All three strings are NUL-terminated. Main thread.
unsafe fn helptags_one(
    dir: *mut c_char,
    ext: *const c_char,
    tagfname: *const c_char,
    add_help_tags: bool,
    ignore_writeerr: bool,
) {
    let mut glob = [0 as c_char; MAXPATHL as usize];
    let namebuff = glob.as_mut_ptr();
    // Find all the help files: "<dir>/**/*<ext>".
    // SAFETY: `glob` is `MAXPATHL` bytes and outlives the expansion below,
    // and `dir`/`ext` are the caller's NUL-terminated strings.
    let dirlen = unsafe { xstrlcpy(namebuff, dir, MAXPATHL as usize) };
    let too_long = dirlen >= MAXPATHL as usize
        || unsafe { xstrlcat(namebuff, c"/**/*".as_ptr(), MAXPATHL as usize) } >= MAXPATHL as usize
        || unsafe { xstrlcat(namebuff, ext, MAXPATHL as usize) } >= MAXPATHL as usize;
    if too_long {
        emsg(gettext(e_fnametoolong));
        return;
    }
    let Some(files) = (unsafe { expand_help_files(namebuff) }) else {
        if !got_int.get() {
            // SAFETY: a message argument the caller holds as a NUL-terminated string.
            let namebuff = unsafe { c_str(namebuff) };
            semsg!("E151: No match: {namebuff}");
        }
        return;
    };

    // Open the tags file for writing before scanning, so that a directory
    // we cannot write to costs nothing.
    let (into, from, n) = (namebuff, dir, dirlen as size_t + 1);
    // SAFETY: `dir` is `dirlen` bytes plus its NUL, so the copy fits;
    // `namebuff` stays NUL-terminated for the two appends after it.
    unsafe { into.cast::<u8>().copy_from_nonoverlapping(from.cast(), n) };
    let too_long = !unsafe { add_pathsep(namebuff) }
        || unsafe { xstrlcat(namebuff, tagfname, MAXPATHL as usize) } >= MAXPATHL as usize;
    if too_long {
        emsg(gettext(e_fnametoolong));
        // Upstream leaks `files` here; the `Wildcards` drop frees it.
        return;
    }
    let fd_tags = unsafe { os_fopen(namebuff, c"w".as_ptr()) };
    if fd_tags.is_null() {
        if !ignore_writeerr {
            // SAFETY: a message argument the caller holds as a NUL-terminated string.
            let namebuff = unsafe { c_str(namebuff) };
            semsg!("E152: Cannot open {namebuff} for writing");
        }
        return;
    }

    // Every tag, as an owned "<tag>\t<file>" line.
    let mut tags: Vec<*mut c_char> = Vec::new();
    // SAFETY: `tagfname` is NUL-terminated and `dir` a directory name.
    if add_help_tags
        || unsafe { path_full_compare(c"$VIMRUNTIME/doc".as_ptr().cast_mut(), dir, false, true) }
            == kEqualFiles
    {
        let len = 18 + unsafe { cstr::bytes_at(tagfname) }.len();
        let entry = unsafe { xmalloc(len) }.cast::<c_char>();
        unsafe { snprintf(entry, len, c"help-tags\t%s\t1\n".as_ptr(), tagfname) };
        tags.push(entry);
    }

    // SAFETY: `files` holds NUL-terminated names all starting with `dir`.
    for fi in 0..files.count {
        if got_int.get() {
            break;
        }
        let path = unsafe { *files.names.offset(fi as isize) };
        let fd = unsafe { os_fopen(path, c"r".as_ptr()) };
        if fd.is_null() {
            // SAFETY: a message argument the caller holds as a NUL-terminated string.
            let path = unsafe { c_str(path) };
            semsg!("E153: Unable to open {path} for reading");
            continue;
        }
        unsafe { scan_help_file(fd, path.add(dirlen).offset(1), &mut tags) };
        unsafe { fclose(fd) };
    }
    drop(files);

    if !got_int.get() && !tags.is_empty() {
        // SAFETY: every entry is an owned NUL-terminated line, and
        // `fd_tags` is open for writing.
        unsafe { sort_strings(tags.as_mut_ptr(), tags.len() as c_int) };
        unsafe { report_duplicates(&tags, dir) };
        unsafe { write_tags(fd_tags, &tags) };
    }

    for entry in tags {
        // SAFETY: each entry was allocated by `xmalloc` above.
        unsafe { xfree(entry.cast::<c_void>()) };
    }
    // There is no check for a write error, as upstream.
    // SAFETY: `fd_tags` is open and nothing else holds it.
    unsafe { fclose(fd_tags) };
}

/// Read one help file, appending a `"<tag>\t<fname>"` entry to `tags` for
/// every `*tag*` in it.
///
/// A tag is only accepted when it holds no space, tab or `|`, has
/// whitespace or the line start before it, and whitespace or the line end
/// after it. Lines inside an example — everything indented after a line
/// ending in `>` — are skipped.
///
/// # Safety
/// `fd` is open for reading and `fname` NUL-terminated. Uses `IObuff`.
unsafe fn scan_help_file(fd: *mut FILE, fname: *const c_char, tags: &mut Vec<*mut c_char>) {
    let mut line = [0 as c_char; IOSIZE as usize];
    let iobuff = line.as_mut_ptr();
    let mut in_example = false;
    // SAFETY: `vim_fgets` NUL-terminates `line` within `IOSIZE` bytes, and
    // every pointer below stays between its start and that NUL.
    while !unsafe { vim_fgets(iobuff, IOSIZE, fd) } && !got_int.get() {
        if in_example {
            // Skip the example; a non-white in the first column ends it.
            if !unsafe { vim_strchr(c" \t\n\r".as_ptr(), *iobuff as uint8_t as c_int) }.is_null() {
                continue;
            }
            in_example = false;
        }

        let mut p1 = unsafe { vim_strchr(iobuff, b'*' as c_int) };
        while !p1.is_null() {
            let mut p2 = unsafe { strchr(p1.offset(1), b'*' as c_int) };
            // Skip "*" and "**".
            if !p2.is_null() && p2 > unsafe { p1.offset(1) } {
                let mut s = unsafe { p1.offset(1) };
                while s < p2
                    && unsafe { *s } != b' ' as c_char
                    && unsafe { *s } != b'\t' as c_char
                    && unsafe { *s } != b'|' as c_char
                {
                    s = unsafe { s.offset(1) };
                }
                // Only accept a *tag* made of valid characters, with
                // white space before it and a white character or the end
                // of the line after it. The order matters: `p1[-1]` is
                // only in bounds once `p1 != iobuff` has been ruled out.
                if s == p2
                    && (p1 == iobuff
                        || unsafe { *p1.offset(-1) } == b' ' as c_char
                        || unsafe { *p1.offset(-1) } == b'\t' as c_char)
                    && (!unsafe {
                        vim_strchr(c" \t\n\r".as_ptr(), *s.offset(1) as uint8_t as c_int)
                    }
                    .is_null()
                        || unsafe { *s.offset(1) } == NUL as c_char)
                {
                    unsafe { *p2 = NUL as c_char };
                    p1 = unsafe { p1.offset(1) };
                    let len = unsafe { p2.offset_from(p1) } as size_t
                        + unsafe { cstr::bytes_at(fname) }.len()
                        + 2;
                    let entry = unsafe { xmalloc(len) }.cast::<c_char>();
                    tags.push(entry);
                    unsafe { snprintf(entry, len, c"%s\t%s".as_ptr(), p1, fname) };
                    // Find the next '*'.
                    p2 = unsafe { vim_strchr(p2.offset(1), b'*' as c_int) };
                }
            }
            p1 = p2;
        }

        // A line ending in ">" — optionally with a `:lang` tail — opens
        // an example.
        let mut off = unsafe { cstr::bytes_at(iobuff) }.len();
        if off >= 2 && unsafe { *iobuff.add(off - 1) } == b'\n' as c_char {
            off -= 2;
            while off > 0
                && (is_lower(unsafe { *iobuff.add(off) })
                    || ascii_isdigit(unsafe { *iobuff.add(off) } as c_int))
            {
                off -= 1;
            }
            if unsafe { *iobuff.add(off) } == b'>' as c_char
                && (off == 0 || unsafe { *iobuff.add(off - 1) } == b' ' as c_char)
            {
                in_example = true;
            }
        }
        line_breakcheck();
    }
}

/// ASCII lowercase letter, the `ASCII_ISLOWER` of the C.
fn is_lower(c: c_char) -> bool {
    c >= b'a' as c_char && c <= b'z' as c_char
}

/// Report every tag defined twice. The entries are sorted, so duplicates
/// are adjacent; two entries are the same tag when they agree up to the tab
/// that separates the tag from its file name.
///
/// # Safety
/// Every entry is a NUL-terminated `"<tag>\t<file>"` line; `dir` is
/// NUL-terminated.
unsafe fn report_duplicates(tags: &[*mut c_char], dir: *const c_char) {
    let mut path = [0 as c_char; MAXPATHL as usize];
    let namebuff = path.as_mut_ptr();
    // SAFETY: caller contract. The tab is restored before returning, so the
    // entry is still a whole line for the writer below.
    for pair in tags.windows(2) {
        let (mut p1, mut p2) = (pair[0], pair[1]);
        while unsafe { *p1 } == unsafe { *p2 } {
            if unsafe { *p2 } != b'\t' as c_char {
                p1 = unsafe { p1.offset(1) };
                p2 = unsafe { p2.offset(1) };
                continue;
            }
            unsafe { *p2 = NUL as c_char };
            let fmt = c"E154: Duplicate tag \"%s\" in file %s/%s".as_ptr();
            let (tag, rest) = (pair[1], unsafe { p2.offset(1) });
            let cap = MAXPATHL as size_t;
            unsafe { vim_snprintf(namebuff, cap, fmt, tag, dir, rest) };
            unsafe { emsg_ptr(namebuff) };
            unsafe { *p2 = b'\t' as c_char };
            break;
        }
    }
}

/// Write the sorted entries out as a tags file. Each becomes
/// `"<tag>\t<file>\t/*<tag>*\n"`, with `\` and `/` escaped inside the
/// search pattern; the `help-tags` entry was built in final form already.
///
/// # Safety
/// `fd` is open for writing and every entry a NUL-terminated
/// `"<tag>\t<file>"` line.
unsafe fn write_tags(fd: *mut FILE, tags: &[*mut c_char]) {
    // SAFETY: caller contract.
    for &entry in tags {
        if unsafe { cstr::starts_with(entry, b"help-tags\t") } {
            unsafe { fputs(entry, fd) };
            continue;
        }
        unsafe { fprintf(fd, c"%s\t/*".as_ptr(), entry) };
        let mut p = entry;
        while unsafe { *p } != b'\t' as c_char {
            if unsafe { *p } == b'\\' as c_char || unsafe { *p } == b'/' as c_char {
                unsafe { putc(b'\\' as c_int, fd) };
            }
            unsafe { putc(*p as c_int, fd) };
            p = unsafe { p.offset(1) };
        }
        unsafe { fprintf(fd, c"*\n".as_ptr()) };
    }
}
