//! Built-in descriptions for system consoles, and the `ansi` fallback
//! nvim settles on when it recognises nothing else.
//!
//! Generated from Dickey's terminfo.src by way of ncurses; edited only by
//! regenerating. See [`Description`] for the shape.

#![forbid(unsafe_code)]
#![deny(
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::ptr_as_ptr
)]

use super::Description;
use crate::tui::terminfo::caps::key_slot::*;
use crate::tui::terminfo::caps::*;

/// The last-resort description: what any ANSI/ECMA-48 terminal can be assumed to do.
pub static ANSI: Description = Description {
    bce: false,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 8,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_clear_screen, c"\x1b[H\x1b[J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\x1b[B"),
        (kTerm_cursor_left, c"\x1b[D"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_secure_mode, c"\x1b[8m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b[0;10m"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[4%p1%dm"),
        (kTerm_set_a_foreground, c"\x1b[3%p1%dm"),
        (kTerm_set_attributes, c"\x1b[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p6%t;1%;%?%p7%t;8%;%?%p9%t;11%;m"),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (BTAB, c"\x1b[Z", None),
        (HOME, c"\x1b[H", None),
        (IC, c"\x1b[L", None),
        (LEFT, c"\x1b[D", None),
        (RIGHT, c"\x1b[C", None),
    ],
    f_keys: &[],
};

/// Interix, the POSIX subsystem Microsoft once shipped for Windows.
pub static INTERIX_8COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 8,
    lines: 25,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_clear_screen, c"\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_left, c"\x1b[D"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[s\x1b[1b"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_exit_attribute_mode, c"\x1b[0m"),
        (kTerm_exit_ca_mode, c"\x1b[2b\x1b[u\r\x1b[K"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[4%p1%dm"),
        (kTerm_set_a_foreground, c"\x1b[3%p1%dm"),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x7f", None),
        (END, c"\x1b[U", None),
        (HOME, c"\x1b[H", None),
        (IC, c"\x1b[L", None),
        (NPAGE, c"\x1b[T", None),
        (PPAGE, c"\x1b[S", None),
        (LEFT, c"\x1b[D", Some(c"\x1bF^")),
        (RIGHT, c"\x1b[C", Some(c"\x1bF$")),
    ],
    f_keys: &[
        Some(c"\x1bF1"),
        Some(c"\x1bF2"),
        Some(c"\x1bF3"),
        Some(c"\x1bF4"),
        Some(c"\x1bF5"),
        Some(c"\x1bF6"),
        Some(c"\x1bF7"),
        Some(c"\x1bF8"),
        Some(c"\x1bF9"),
        Some(c"\x1bFA"),
        Some(c"\x1bFB"),
        Some(c"\x1bFC"),
        Some(c"\x1bFD"),
        Some(c"\x1bFE"),
        Some(c"\x1bFF"),
        Some(c"\x1bFG"),
        Some(c"\x1bFH"),
        Some(c"\x1bFI"),
        Some(c"\x1bFJ"),
        Some(c"\x1bFK"),
        Some(c"\x1bFL"),
        Some(c"\x1bFM"),
        Some(c"\x1bFN"),
        Some(c"\x1bFO"),
        Some(c"\x1bFP"),
        Some(c"\x1bFQ"),
        Some(c"\x1bFR"),
        Some(c"\x1bFS"),
        Some(c"\x1bFT"),
        Some(c"\x1bFU"),
        Some(c"\x1bFV"),
        Some(c"\x1bFW"),
        Some(c"\x1bFX"),
        Some(c"\x1bFY"),
        Some(c"\x1bFZ"),
        Some(c"\x1bFa"),
        Some(c"\x1bFb"),
        Some(c"\x1bFc"),
        Some(c"\x1bFd"),
        Some(c"\x1bFe"),
        Some(c"\x1bFf"),
        Some(c"\x1bFg"),
        Some(c"\x1bFh"),
        Some(c"\x1bFi"),
        Some(c"\x1bFj"),
        Some(c"\x1bFk"),
        Some(c"\x1bFm"),
        Some(c"\x1bFn"),
        Some(c"\x1bFo"),
        Some(c"\x1bFp"),
        Some(c"\x1bFq"),
        Some(c"\x1bFr"),
        Some(c"\x1bFs"),
        Some(c"\x1bFt"),
        Some(c"\x1bFu"),
        Some(c"\x1bFv"),
        Some(c"\x1bFw"),
        Some(c"\x1bFx"),
        Some(c"\x1bFy"),
        Some(c"\x1bFz"),
    ],
};

/// The Linux kernel console.
pub static LINUX_16COLOUR: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 8,
    lines: -1,
    columns: -1,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\n"),
        (kTerm_cursor_invisible, c"\x1b[?25l\x1b[?1c"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?25h\x1b[?0c"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_blink_mode, c"\x1b[5m"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_dim_mode, c"\x1b[2m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b[m\x0f"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[4%p1%dm"),
        (kTerm_set_a_foreground, c"\x1b[3%p1%dm"),
        (kTerm_set_attributes, c"\x1b[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p6%t;1%;m%?%p9%t^N%e\x0f%;"),
    ],
    keys: &[
        (BACKSPACE, c"\x7f", None),
        (BTAB, c"\x1b^I", None),
        (DC, c"\x1b[3~", None),
        (END, c"\x1b[4~", None),
        (HOME, c"\x1b[1~", None),
        (IC, c"\x1b[2~", None),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (SUSPEND, c"^Z", None),
        (LEFT, c"\x1b[D", None),
        (RIGHT, c"\x1b[C", None),
    ],
    f_keys: &[
        Some(c"\x1b[[A"), Some(c"\x1b[[B"), Some(c"\x1b[[C"), Some(c"\x1b[[D"), Some(c"\x1b[[E"),
        Some(c"\x1b[17~"), Some(c"\x1b[18~"), Some(c"\x1b[19~"), Some(c"\x1b[20~"),
        Some(c"\x1b[21~"), Some(c"\x1b[23~"), Some(c"\x1b[24~"), Some(c"\x1b[25~"),
        Some(c"\x1b[26~"), Some(c"\x1b[28~"), Some(c"\x1b[29~"), Some(c"\x1b[31~"),
        Some(c"\x1b[32~"), Some(c"\x1b[33~"), Some(c"\x1b[34~"),
    ],
};
