//! Built-in descriptions for the Windows consoles and Cygwin.
//!
//! Generated from Dickey's terminfo.src by way of ncurses; edited only by
//! regenerating. See [`Description`] for the shape.

#![forbid(unsafe_code)]
#![deny(
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::ptr_as_ptr
)]

use super::Description;
use crate::tui::terminfo::caps::key_slot::*;
use crate::tui::terminfo::caps::*;

/// Cygwin's terminal.
pub static CYGWIN: Description = Description {
    bce: false,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 8,
    lines: -1,
    columns: -1,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_clear_screen, c"\x1b[H\x1b[J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\x1b[B"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b7\x1b[?47h"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_secure_mode, c"\x1b[8m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_exit_attribute_mode, c"\x1b[0;10m"),
        (kTerm_exit_ca_mode, c"\x1b[2J\x1b[?47l\x1b8"),
        (kTerm_from_status_line, c"\x07"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[4%p1%dm"),
        (kTerm_set_a_foreground, c"\x1b[3%p1%dm"),
        (
            kTerm_set_attributes,
            c"\x1b[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p6%t;1%;%?%p7%t;8%;%?%p9%t;11%;m",
        ),
        (kTerm_to_status_line, c"\x1b];"),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (DC, c"\x1b[3~", None),
        (END, c"\x1b[4~", None),
        (HOME, c"\x1b[1~", None),
        (IC, c"\x1b[2~", None),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (SUSPEND, c"^Z", None),
        (LEFT, c"\x1b[D", None),
        (RIGHT, c"\x1b[C", None),
    ],
    f_keys: &[
        Some(c"\x1b[[A"),
        Some(c"\x1b[[B"),
        Some(c"\x1b[[C"),
        Some(c"\x1b[[D"),
        Some(c"\x1b[[E"),
        Some(c"\x1b[17~"),
        Some(c"\x1b[18~"),
        Some(c"\x1b[19~"),
        Some(c"\x1b[20~"),
        Some(c"\x1b[21~"),
        Some(c"\x1b[23~"),
        Some(c"\x1b[24~"),
        Some(c"\x1b[25~"),
        Some(c"\x1b[26~"),
        Some(c"\x1b[28~"),
        Some(c"\x1b[29~"),
        Some(c"\x1b[31~"),
        Some(c"\x1b[32~"),
        Some(c"\x1b[33~"),
        Some(c"\x1b[34~"),
    ],
};

/// The classic Windows console, before it spoke escape sequences.
pub static WIN32CON: Description = Description {
    bce: false,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 8,
    lines: -1,
    columns: -1,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_clear_screen, c"\x1b[H\x1b[J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\x1b[B"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b7\x1b[?47h"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_exit_attribute_mode, c"\x1b[0m"),
        (kTerm_exit_ca_mode, c"\x1b[2J\x1b[?47l\x1b8"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[4%p1%dm"),
        (kTerm_set_a_foreground, c"\x1b[3%p1%dm"),
        (
            kTerm_set_attributes,
            c"\x1b[0%?%p1%t;7%;%?%p3%t;7%;%?%p6%t;1%;m",
        ),
        (kTerm_reset_cursor_style, c"\x1b[0 q"),
        (kTerm_set_cursor_style, c"\x1b[%p1%d q"),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3;2~")),
        (END, c"\x1b[4~", Some(c"\x1b[4;2~")),
        (HOME, c"\x1b[1~", Some(c"\x1b[1;2~")),
        (IC, c"\x1b[2~", Some(c"\x1b[2;2~")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (SUSPEND, c"^Z", None),
        (LEFT, c"\x1b[D", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1b[C", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1b[[A"),
        Some(c"\x1b[[B"),
        Some(c"\x1b[[C"),
        Some(c"\x1b[[D"),
        Some(c"\x1b[[E"),
        Some(c"\x1b[17~"),
        Some(c"\x1b[18~"),
        Some(c"\x1b[19~"),
        Some(c"\x1b[20~"),
        Some(c"\x1b[21~"),
        Some(c"\x1b[23~"),
        Some(c"\x1b[24~"),
        Some(c"\x1b[25~"),
        Some(c"\x1b[26~"),
        Some(c"\x1b[28~"),
        Some(c"\x1b[29~"),
        Some(c"\x1b[31~"),
        Some(c"\x1b[32~"),
        Some(c"\x1b[33~"),
        Some(c"\x1b[34~"),
        Some(c"\x1b[23$"),
        Some(c"\x1b[24$"),
        Some(c"\x1b[11^"),
        Some(c"\x1b[12^"),
        Some(c"\x1b[13^"),
        Some(c"\x1b[14^"),
        Some(c"\x1b[15^"),
        Some(c"\x1b[17^"),
        Some(c"\x1b[18^"),
        Some(c"\x1b[19^"),
        Some(c"\x1b[20^"),
        Some(c"\x1b[21^"),
        Some(c"\x1b[23^"),
        Some(c"\x1b[24^"),
        Some(c"\x1b[25^"),
        Some(c"\x1b[26^"),
        Some(c"\x1b[28^"),
        Some(c"\x1b[29^"),
        Some(c"\x1b[31^"),
        None,
        Some(c"\x1b[32^"),
        Some(c"\x1b[33^"),
        Some(c"\x1b[34^"),
        Some(c"\x1b[23@"),
        Some(c"\x1b[24@"),
    ],
};

/// ConEmu.
pub static CONEMU: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\x1b[B"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h"),
        (kTerm_enter_italics_mode, c"\x1b[3m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b[0m"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (kTerm_set_a_background, c"\x1b[48;5;%p1%dm"),
        (kTerm_set_a_foreground, c"\x1b[38;5;%p1%dm"),
        (
            kTerm_set_attributes,
            c"\x1b[0%?%p1%p3%|%t;7%;%?%p2%t;4%;%?%p6%t;1%;m",
        ),
        (kTerm_reset_cursor_style, c"\x1b[2 q"),
        (kTerm_set_cursor_style, c"\x1b[%p1%d q"),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (BEG, c"\x1bOE", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3;2~")),
        (END, c"\x1b[4~", Some(c"\x1b[4;2~")),
        (HOME, c"\x1b[1~", Some(c"\x1b[1;2~")),
        (IC, c"\x1b[2~", Some(c"\x1b[2;2~")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (LEFT, c"\x1b[D", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1b[C", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1b[[A"),
        Some(c"\x1b[[B"),
        Some(c"\x1b[[C"),
        Some(c"\x1b[[D"),
        Some(c"\x1b[[E"),
        Some(c"\x1b[17~"),
        Some(c"\x1b[18~"),
        Some(c"\x1b[19~"),
        Some(c"\x1b[20~"),
        Some(c"\x1b[21~"),
        Some(c"\x1b[23~"),
        Some(c"\x1b[24~"),
        Some(c"\x1b[25~"),
        Some(c"\x1b[26~"),
        Some(c"\x1b[28~"),
        Some(c"\x1b[29~"),
        Some(c"\x1b[31~"),
        Some(c"\x1b[32~"),
        Some(c"\x1b[33~"),
        Some(c"\x1b[34~"),
        Some(c"\x1b[23$"),
        Some(c"\x1b[24$"),
        Some(c"\x1b[11^"),
        Some(c"\x1b[12^"),
        Some(c"\x1b[13^"),
        Some(c"\x1b[14^"),
        Some(c"\x1b[15^"),
        Some(c"\x1b[17^"),
        Some(c"\x1b[18^"),
        Some(c"\x1b[19^"),
        Some(c"\x1b[20^"),
        Some(c"\x1b[21^"),
        Some(c"\x1b[23^"),
        Some(c"\x1b[24^"),
        Some(c"\x1b[25^"),
        Some(c"\x1b[26^"),
        Some(c"\x1b[28^"),
        Some(c"\x1b[29^"),
        Some(c"\x1b[31^"),
        Some(c"\x1b[1;6S"),
        Some(c"\x1b[32^"),
        Some(c"\x1b[33^"),
        Some(c"\x1b[34^"),
        Some(c"\x1b[23@"),
        Some(c"\x1b[24@"),
    ],
};

/// Windows' virtual-terminal console mode.
pub static VTPCON: Description = Description {
    bce: true,
    has_tc_or_rgb: false,
    su: false,
    max_colors: 0x100,
    lines: 24,
    columns: 80,
    defs: &[
        (kTerm_carriage_return, c"\r"),
        (kTerm_change_scroll_region, c"\x1b[%i%p1%d;%p2%dr"),
        (kTerm_clear_screen, c"\x1b[H\x1b[2J"),
        (kTerm_clr_eol, c"\x1b[K"),
        (kTerm_clr_eos, c"\x1b[J"),
        (kTerm_cursor_address, c"\x1b[%i%p1%d;%p2%dH"),
        (kTerm_cursor_down, c"\x1b[B"),
        (kTerm_cursor_invisible, c"\x1b[?25l"),
        (kTerm_cursor_left, c"\x08"),
        (kTerm_cursor_home, c"\x1b[H"),
        (kTerm_cursor_normal, c"\x1b[?12l\x1b[?25h"),
        (kTerm_cursor_up, c"\x1b[A"),
        (kTerm_cursor_right, c"\x1b[C"),
        (kTerm_delete_line, c"\x1b[M"),
        (kTerm_enter_bold_mode, c"\x1b[1m"),
        (kTerm_enter_ca_mode, c"\x1b[?1049h"),
        (kTerm_enter_italics_mode, c"\x1b[3m"),
        (kTerm_enter_reverse_mode, c"\x1b[7m"),
        (kTerm_enter_standout_mode, c"\x1b[7m"),
        (kTerm_enter_underline_mode, c"\x1b[4m"),
        (kTerm_erase_chars, c"\x1b[%p1%dX"),
        (kTerm_exit_attribute_mode, c"\x1b[0m"),
        (kTerm_exit_ca_mode, c"\x1b[?1049l"),
        (kTerm_from_status_line, c"\x07"),
        (kTerm_insert_line, c"\x1b[L"),
        (kTerm_parm_delete_line, c"\x1b[%p1%dM"),
        (kTerm_parm_down_cursor, c"\x1b[%p1%dB"),
        (kTerm_parm_insert_line, c"\x1b[%p1%dL"),
        (kTerm_parm_left_cursor, c"\x1b[%p1%dD"),
        (kTerm_parm_right_cursor, c"\x1b[%p1%dC"),
        (kTerm_parm_up_cursor, c"\x1b[%p1%dA"),
        (
            kTerm_set_a_background,
            c"\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m",
        ),
        (
            kTerm_set_a_foreground,
            c"\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m",
        ),
        (
            kTerm_set_attributes,
            c"\x1b[0%?%p1%p3%|%t;7%;%?%p2%t;4%;%?%p6%t;1%;%?%p9%t;9%;m",
        ),
        (kTerm_to_status_line, c"\x1b]0;"),
        (kTerm_reset_cursor_style, c"\x1b[2 q"),
        (kTerm_set_cursor_style, c"\x1b[%p1%d q"),
        (kTerm_enter_strikethrough_mode, c"\x1b[9m"),
    ],
    keys: &[
        (BACKSPACE, c"\x08", None),
        (BEG, c"\x1bOE", None),
        (BTAB, c"\x1b[Z", None),
        (DC, c"\x1b[3~", Some(c"\x1b[3;2~")),
        (END, c"\x1b[4~", Some(c"\x1b[4;2~")),
        (HOME, c"\x1b[1~", Some(c"\x1b[1;2~")),
        (IC, c"\x1b[2~", Some(c"\x1b[2;2~")),
        (NPAGE, c"\x1b[6~", None),
        (PPAGE, c"\x1b[5~", None),
        (LEFT, c"\x1b[D", Some(c"\x1b[1;2D")),
        (RIGHT, c"\x1b[C", Some(c"\x1b[1;2C")),
    ],
    f_keys: &[
        Some(c"\x1b[[A"),
        Some(c"\x1b[[B"),
        Some(c"\x1b[[C"),
        Some(c"\x1b[[D"),
        Some(c"\x1b[[E"),
        Some(c"\x1b[17~"),
        Some(c"\x1b[18~"),
        Some(c"\x1b[19~"),
        Some(c"\x1b[20~"),
        Some(c"\x1b[21~"),
        Some(c"\x1b[23~"),
        Some(c"\x1b[24~"),
        Some(c"\x1b[25~"),
        Some(c"\x1b[26~"),
        Some(c"\x1b[28~"),
        Some(c"\x1b[29~"),
        Some(c"\x1b[31~"),
        Some(c"\x1b[32~"),
        Some(c"\x1b[33~"),
        Some(c"\x1b[34~"),
        Some(c"\x1b[23$"),
        Some(c"\x1b[24$"),
        Some(c"\x1b[11^"),
        Some(c"\x1b[12^"),
        Some(c"\x1b[13^"),
        Some(c"\x1b[14^"),
        Some(c"\x1b[15^"),
        Some(c"\x1b[17^"),
        Some(c"\x1b[18^"),
        Some(c"\x1b[19^"),
        Some(c"\x1b[20^"),
        Some(c"\x1b[21^"),
        Some(c"\x1b[23^"),
        Some(c"\x1b[24^"),
        Some(c"\x1b[25^"),
        Some(c"\x1b[26^"),
        Some(c"\x1b[28^"),
        Some(c"\x1b[29^"),
        Some(c"\x1b[31^"),
        Some(c"\x1b[1;6S"),
        Some(c"\x1b[32^"),
        Some(c"\x1b[33^"),
        Some(c"\x1b[34^"),
        Some(c"\x1b[23@"),
        Some(c"\x1b[24@"),
    ],
};
