//! The flag enums a string option's value parses into.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![forbid(unsafe_code)]

// A chunk may hold nothing that needs the parent's support code.
#[allow(unused_imports)]
use super::*;

/// The bits 'backupcopy' parses into.
pub type OptBkcFlags = c_uint;
pub const kOptBkcFlagYes: OptBkcFlags = 0x01;
pub const kOptBkcFlagAuto: OptBkcFlags = 0x02;
pub const kOptBkcFlagNo: OptBkcFlags = 0x04;
pub const kOptBkcFlagBreaksymlink: OptBkcFlags = 0x08;
pub const kOptBkcFlagBreakhardlink: OptBkcFlags = 0x10;

/// The bits 'belloff' parses into.
pub type OptBoFlags = c_uint;
pub const kOptBoFlagAll: OptBoFlags = 0x01;
pub const kOptBoFlagBackspace: OptBoFlags = 0x02;
pub const kOptBoFlagCursor: OptBoFlags = 0x04;
pub const kOptBoFlagComplete: OptBoFlags = 0x08;
pub const kOptBoFlagCopy: OptBoFlags = 0x10;
pub const kOptBoFlagCtrlg: OptBoFlags = 0x20;
pub const kOptBoFlagError: OptBoFlags = 0x40;
pub const kOptBoFlagEsc: OptBoFlags = 0x80;
pub const kOptBoFlagEx: OptBoFlags = 0x100;
pub const kOptBoFlagHangul: OptBoFlags = 0x200;
pub const kOptBoFlagInsertmode: OptBoFlags = 0x400;
pub const kOptBoFlagLang: OptBoFlags = 0x800;
pub const kOptBoFlagMess: OptBoFlags = 0x1000;
pub const kOptBoFlagShowmatch: OptBoFlags = 0x2000;
pub const kOptBoFlagOperator: OptBoFlags = 0x4000;
pub const kOptBoFlagRegister: OptBoFlags = 0x8000;
pub const kOptBoFlagShell: OptBoFlags = 0x10000;
pub const kOptBoFlagSpell: OptBoFlags = 0x20000;
pub const kOptBoFlagTerm: OptBoFlags = 0x40000;
pub const kOptBoFlagWildmode: OptBoFlags = 0x80000;

/// The bits 'casemap' parses into.
pub type OptCmpFlags = c_uint;
pub const kOptCmpFlagInternal: OptCmpFlags = 0x01;
pub const kOptCmpFlagKeepascii: OptCmpFlags = 0x02;

/// The bits 'clipboard' parses into.
pub type OptCbFlags = c_uint;
pub const kOptCbFlagUnnamed: OptCbFlags = 0x01;
pub const kOptCbFlagUnnamedplus: OptCbFlags = 0x02;

/// The bits 'completeopt' parses into.
pub type OptCotFlags = c_uint;
pub const kOptCotFlagMenu: OptCotFlags = 0x01;
pub const kOptCotFlagMenuone: OptCotFlags = 0x02;
pub const kOptCotFlagLongest: OptCotFlags = 0x04;
pub const kOptCotFlagPreview: OptCotFlags = 0x08;
pub const kOptCotFlagPopup: OptCotFlags = 0x10;
pub const kOptCotFlagNoinsert: OptCotFlags = 0x20;
pub const kOptCotFlagNoselect: OptCotFlags = 0x40;
pub const kOptCotFlagFuzzy: OptCotFlags = 0x80;
pub const kOptCotFlagNosort: OptCotFlags = 0x100;
pub const kOptCotFlagPreinsert: OptCotFlags = 0x200;
pub const kOptCotFlagNearest: OptCotFlags = 0x400;

/// The bits 'cursorlineopt' parses into.
pub type OptCuloptFlags = c_uint;
pub const kOptCuloptFlagLine: OptCuloptFlags = 0x01;
pub const kOptCuloptFlagScreenline: OptCuloptFlags = 0x02;
pub const kOptCuloptFlagNumber: OptCuloptFlags = 0x04;

/// The bits 'display' parses into.
pub type OptDyFlags = c_uint;
pub const kOptDyFlagLastline: OptDyFlags = 0x01;
pub const kOptDyFlagTruncate: OptDyFlags = 0x02;
pub const kOptDyFlagUhex: OptDyFlags = 0x04;
pub const kOptDyFlagMsgsep: OptDyFlags = 0x08;

/// The bits 'foldopen' parses into.
pub type OptFdoFlags = c_uint;
pub const kOptFdoFlagAll: OptFdoFlags = 0x01;
pub const kOptFdoFlagBlock: OptFdoFlags = 0x02;
pub const kOptFdoFlagHor: OptFdoFlags = 0x04;
pub const kOptFdoFlagMark: OptFdoFlags = 0x08;
pub const kOptFdoFlagPercent: OptFdoFlags = 0x10;
pub const kOptFdoFlagQuickfix: OptFdoFlags = 0x20;
pub const kOptFdoFlagSearch: OptFdoFlags = 0x40;
pub const kOptFdoFlagTag: OptFdoFlags = 0x80;
pub const kOptFdoFlagInsert: OptFdoFlags = 0x100;
pub const kOptFdoFlagUndo: OptFdoFlags = 0x200;
pub const kOptFdoFlagJump: OptFdoFlags = 0x400;

/// The bits 'jumpoptions' parses into.
pub type OptJopFlags = c_uint;
pub const kOptJopFlagStack: OptJopFlags = 0x01;
pub const kOptJopFlagView: OptJopFlags = 0x02;
pub const kOptJopFlagClean: OptJopFlags = 0x04;

/// The bits 'messagesopt' parses into.
pub type OptMoptFlags = c_uint;
pub const kOptMoptFlagHitEnter: OptMoptFlags = 0x01;
pub const kOptMoptFlagWait: OptMoptFlags = 0x02;
pub const kOptMoptFlagHistory: OptMoptFlags = 0x04;
pub const kOptMoptFlagProgress: OptMoptFlags = 0x08;

/// The bits 'redrawdebug' parses into.
pub type OptRdbFlags = c_uint;
pub const kOptRdbFlagCompositor: OptRdbFlags = 0x01;
pub const kOptRdbFlagNothrottle: OptRdbFlags = 0x02;
pub const kOptRdbFlagInvalid: OptRdbFlags = 0x04;
pub const kOptRdbFlagNodelta: OptRdbFlags = 0x08;
pub const kOptRdbFlagLine: OptRdbFlags = 0x10;
pub const kOptRdbFlagFlush: OptRdbFlags = 0x20;

/// The bits 'sessionoptions' parses into.
pub type OptSsopFlags = c_uint;
pub const kOptSsopFlagBuffers: OptSsopFlags = 0x01;
pub const kOptSsopFlagWinpos: OptSsopFlags = 0x02;
pub const kOptSsopFlagResize: OptSsopFlags = 0x04;
pub const kOptSsopFlagWinsize: OptSsopFlags = 0x08;
pub const kOptSsopFlagLocaloptions: OptSsopFlags = 0x10;
pub const kOptSsopFlagOptions: OptSsopFlags = 0x20;
pub const kOptSsopFlagHelp: OptSsopFlags = 0x40;
pub const kOptSsopFlagBlank: OptSsopFlags = 0x80;
pub const kOptSsopFlagGlobals: OptSsopFlags = 0x100;
pub const kOptSsopFlagSlash: OptSsopFlags = 0x200;
pub const kOptSsopFlagUnix: OptSsopFlags = 0x400;
pub const kOptSsopFlagSesdir: OptSsopFlags = 0x800;
pub const kOptSsopFlagCurdir: OptSsopFlags = 0x1000;
pub const kOptSsopFlagFolds: OptSsopFlags = 0x2000;
pub const kOptSsopFlagCursor: OptSsopFlags = 0x4000;
pub const kOptSsopFlagTabpages: OptSsopFlags = 0x8000;
pub const kOptSsopFlagTerminal: OptSsopFlags = 0x10000;
pub const kOptSsopFlagSkiprtp: OptSsopFlags = 0x20000;

/// The bits 'spelloptions' parses into.
pub type OptSpoFlags = c_uint;
pub const kOptSpoFlagCamel: OptSpoFlags = 0x01;
pub const kOptSpoFlagNoplainbuffer: OptSpoFlags = 0x02;

/// The bits 'switchbuf' parses into.
pub type OptSwbFlags = c_uint;
pub const kOptSwbFlagUseopen: OptSwbFlags = 0x01;
pub const kOptSwbFlagUsetab: OptSwbFlags = 0x02;
pub const kOptSwbFlagSplit: OptSwbFlags = 0x04;
pub const kOptSwbFlagNewtab: OptSwbFlags = 0x08;
pub const kOptSwbFlagVsplit: OptSwbFlags = 0x10;
pub const kOptSwbFlagUselast: OptSwbFlags = 0x20;

/// The bits 'tabclose' parses into.
pub type OptTclFlags = c_uint;
pub const kOptTclFlagLeft: OptTclFlags = 0x01;
pub const kOptTclFlagUselast: OptTclFlags = 0x02;

/// The bits 'tagcase' parses into.
pub type OptTcFlags = c_uint;
pub const kOptTcFlagFollowic: OptTcFlags = 0x01;
pub const kOptTcFlagIgnore: OptTcFlags = 0x02;
pub const kOptTcFlagMatch: OptTcFlags = 0x04;
pub const kOptTcFlagFollowscs: OptTcFlags = 0x08;
pub const kOptTcFlagSmart: OptTcFlags = 0x10;

/// The bits 'termpastefilter' parses into.
pub type OptTpfFlags = c_uint;
pub const kOptTpfFlagBS: OptTpfFlags = 0x01;
pub const kOptTpfFlagHT: OptTpfFlags = 0x02;
pub const kOptTpfFlagFF: OptTpfFlags = 0x04;
pub const kOptTpfFlagESC: OptTpfFlags = 0x08;
pub const kOptTpfFlagDEL: OptTpfFlags = 0x10;
pub const kOptTpfFlagC0: OptTpfFlags = 0x20;
pub const kOptTpfFlagC1: OptTpfFlags = 0x40;

/// The bits 'virtualedit' parses into.
pub type OptVeFlags = c_uint;
pub const kOptVeFlagAll: OptVeFlags = 0x04;
pub const kOptVeFlagBlock: OptVeFlags = 0x05;
pub const kOptVeFlagInsert: OptVeFlags = 0x06;
pub const kOptVeFlagOnemore: OptVeFlags = 0x08;
pub const kOptVeFlagNone: OptVeFlags = 0x10;
pub const kOptVeFlagNoneU: OptVeFlags = 0x20;

/// The bits 'wildmode' parses into.
pub type OptWimFlags = c_uint;
pub const kOptWimFlagFull: OptWimFlags = 0x01;
pub const kOptWimFlagLongest: OptWimFlags = 0x02;
pub const kOptWimFlagList: OptWimFlags = 0x04;
pub const kOptWimFlagLastused: OptWimFlags = 0x08;
pub const kOptWimFlagNoselect: OptWimFlags = 0x10;

/// The bits 'wildoptions' parses into.
pub type OptWopFlags = c_uint;
pub const kOptWopFlagFuzzy: OptWopFlags = 0x01;
pub const kOptWopFlagTagfile: OptWopFlags = 0x02;
pub const kOptWopFlagPum: OptWopFlags = 0x04;
pub const kOptWopFlagExacttext: OptWopFlags = 0x08;
