//! A run of the option table's rows.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![forbid(unsafe_code)]
#![deny(
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::ptr_as_ptr
)]

// A chunk may hold nothing that needs the parent's support code.
#[allow(unused_imports)]
use super::*;

/// This file's run of the option table, spliced in by the parent.
pub(super) const PART: [VimOption; 81] = [
    // 'jumpoptions'
    VimOption {
        fullname: name(c"jumpoptions"),
        shortname: name(c"jop"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptJumpoptions, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_JOP),
        flags_var: Some(&jop_flags),
        values: &opt_jop_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"clean"),
        ..BLANK
    },
    // 'keymap'
    VimOption {
        fullname: name(c"keymap"),
        shortname: name(c"kmp"),
        flags: kOptFlagRedrStat | kOptFlagRedrBuf | kOptFlagNFname | kOptFlagPriMkrc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptKeymap),
        var: OptVar::String(P_KEYMAP),
        opt_did_set_cb: Some(did_set_keymap),
        def_val: string(c""),
        ..BLANK
    },
    // 'keymodel'
    VimOption {
        fullname: name(c"keymodel"),
        shortname: name(c"km"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptKeymodel, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_KM),
        values: &opt_km_values,
        opt_did_set_cb: Some(did_set_keymodel),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'keywordprg'
    VimOption {
        fullname: name(c"keywordprg"),
        shortname: name(c"kp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptKeywordprg, kWinOptInvalid, kBufOptKeywordprg),
        var: OptVar::String(P_KP),
        def_val: string(c":Man"),
        ..BLANK
    },
    // 'langmap'
    VimOption {
        fullname: name(c"langmap"),
        shortname: name(c"lmap"),
        flags: kOptFlagOneComma | kOptFlagSecure | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangmap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_LANGMAP),
        opt_did_set_cb: Some(did_set_langmap),
        def_val: string(c""),
        ..BLANK
    },
    // 'langmenu'
    VimOption {
        fullname: name(c"langmenu"),
        shortname: name(c"lm"),
        flags: kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangmenu, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_LM),
        def_val: string(c""),
        ..BLANK
    },
    // 'langnoremap'
    VimOption {
        fullname: name(c"langnoremap"),
        shortname: name(c"lnr"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangnoremap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LNR),
        opt_did_set_cb: Some(did_set_langnoremap),
        def_val: boolean(true),
        ..BLANK
    },
    // 'langremap'
    VimOption {
        fullname: name(c"langremap"),
        shortname: name(c"lrm"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangremap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LRM),
        opt_did_set_cb: Some(did_set_langremap),
        ..BLANK
    },
    // 'laststatus'
    VimOption {
        fullname: name(c"laststatus"),
        shortname: name(c"ls"),
        flags: kOptFlagRedrAll,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLaststatus, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_LS),
        opt_did_set_cb: Some(did_set_laststatus),
        def_val: number(2),
        ..BLANK
    },
    // 'lazyredraw'
    VimOption {
        fullname: name(c"lazyredraw"),
        shortname: name(c"lz"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLazyredraw, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LZ),
        ..BLANK
    },
    // 'lhistory'
    VimOption {
        fullname: name(c"lhistory"),
        shortname: name(c"lhi"),
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptLhistory, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_xhistory),
        def_val: number(10),
        ..BLANK
    },
    // 'linebreak'
    VimOption {
        fullname: name(c"linebreak"),
        shortname: name(c"lbr"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptLinebreak, kBufOptInvalid),
        ..BLANK
    },
    // 'lines'
    VimOption {
        fullname: name(c"lines"),
        flags: kOptFlagNoMkrc,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLines, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_LINES),
        opt_did_set_cb: Some(did_set_lines_or_columns),
        def_val: number(DFLT_ROWS as OptInt),
        ..BLANK
    },
    // 'linespace'
    VimOption {
        fullname: name(c"linespace"),
        shortname: name(c"lsp"),
        flags: kOptFlagUIOption,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLinespace, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_LINESPACE),
        def_val: number(0),
        ..BLANK
    },
    // 'lisp'
    VimOption {
        fullname: name(c"lisp"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptLisp),
        var: OptVar::Boolean(P_LISP),
        opt_did_set_cb: Some(did_set_lisp),
        ..BLANK
    },
    // 'lispoptions'
    VimOption {
        fullname: name(c"lispoptions"),
        shortname: name(c"lop"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptLispoptions),
        var: OptVar::String(P_LOP),
        values: &opt_lop_values,
        opt_did_set_cb: Some(did_set_lispoptions),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'lispwords'
    VimOption {
        fullname: name(c"lispwords"),
        shortname: name(c"lw"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptLispwords, kWinOptInvalid, kBufOptLispwords),
        var: OptVar::String(P_LISPWORDS),
        def_val: string(LISPWORD_VALUE),
        ..BLANK
    },
    // 'list'
    VimOption {
        fullname: name(c"list"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptList, kBufOptInvalid),
        ..BLANK
    },
    // 'listchars'
    VimOption {
        fullname: name(c"listchars"),
        shortname: name(c"lcs"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagRedrWin | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | WIN,
        scope_idx: scope_idx(kGlobalOptListchars, kWinOptListchars, kBufOptInvalid),
        var: OptVar::String(P_LCS),
        opt_did_set_cb: Some(did_set_chars_option),
        opt_expand_cb: Some(expand_set_chars_option),
        def_val: string(c"tab:> ,trail:-,nbsp:+"),
        ..BLANK
    },
    // 'loadplugins'
    VimOption {
        fullname: name(c"loadplugins"),
        shortname: name(c"lpl"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLoadplugins, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LPL),
        def_val: boolean(true),
        ..BLANK
    },
    // 'magic'
    VimOption {
        fullname: name(c"magic"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMagic, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MAGIC),
        def_val: boolean(true),
        ..BLANK
    },
    // 'makeef'
    VimOption {
        fullname: name(c"makeef"),
        shortname: name(c"mef"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMakeef, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MEF),
        def_val: string(c""),
        ..BLANK
    },
    // 'makeencoding'
    VimOption {
        fullname: name(c"makeencoding"),
        shortname: name(c"menc"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptMakeencoding, kWinOptInvalid, kBufOptMakeencoding),
        var: OptVar::String(P_MENC),
        opt_did_set_cb: Some(did_set_encoding),
        opt_expand_cb: Some(expand_set_encoding),
        def_val: string(c""),
        ..BLANK
    },
    // 'makeprg'
    VimOption {
        fullname: name(c"makeprg"),
        shortname: name(c"mp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptMakeprg, kWinOptInvalid, kBufOptMakeprg),
        var: OptVar::String(P_MP),
        def_val: string(c"make"),
        ..BLANK
    },
    // 'matchpairs'
    VimOption {
        fullname: name(c"matchpairs"),
        shortname: name(c"mps"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptMatchpairs),
        var: OptVar::String(P_MPS),
        opt_did_set_cb: Some(did_set_matchpairs),
        def_val: string(c"(:),{:},[:]"),
        ..BLANK
    },
    // 'matchtime'
    VimOption {
        fullname: name(c"matchtime"),
        shortname: name(c"mat"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMatchtime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MAT),
        def_val: number(5),
        ..BLANK
    },
    // 'maxcombine'
    VimOption {
        fullname: name(c"maxcombine"),
        shortname: name(c"mco"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxcombine, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MCO),
        def_val: number(MAX_MCO as OptInt),
        ..BLANK
    },
    // 'maxfuncdepth'
    VimOption {
        fullname: name(c"maxfuncdepth"),
        shortname: name(c"mfd"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxfuncdepth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MFD),
        def_val: number(100),
        ..BLANK
    },
    // 'maxmapdepth'
    VimOption {
        fullname: name(c"maxmapdepth"),
        shortname: name(c"mmd"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxmapdepth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MMD),
        def_val: number(1000),
        ..BLANK
    },
    // 'maxmempattern'
    VimOption {
        fullname: name(c"maxmempattern"),
        shortname: name(c"mmp"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxmempattern, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MMP),
        def_val: number(1000),
        ..BLANK
    },
    // 'maxsearchcount'
    VimOption {
        fullname: name(c"maxsearchcount"),
        shortname: name(c"msc"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxsearchcount, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MSC),
        def_val: number(999),
        ..BLANK
    },
    // 'menuitems'
    VimOption {
        fullname: name(c"menuitems"),
        shortname: name(c"mis"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMenuitems, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MIS),
        def_val: number(25),
        ..BLANK
    },
    // 'messagesopt'
    VimOption {
        fullname: name(c"messagesopt"),
        shortname: name(c"mopt"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMessagesopt, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOPT),
        values: &opt_mopt_values,
        opt_did_set_cb: Some(did_set_messagesopt),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"hit-enter,history:500,progress:c"),
        ..BLANK
    },
    // 'mkspellmem'
    VimOption {
        fullname: name(c"mkspellmem"),
        shortname: name(c"msm"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMkspellmem, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MSM),
        opt_did_set_cb: Some(did_set_mkspellmem),
        def_val: string(c"460000,2000,500"),
        ..BLANK
    },
    // 'modeline'
    VimOption {
        fullname: name(c"modeline"),
        shortname: name(c"ml"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModeline),
        var: OptVar::Boolean(P_ML),
        def_val: boolean(true),
        ..BLANK
    },
    // 'modelineexpr'
    VimOption {
        fullname: name(c"modelineexpr"),
        shortname: name(c"mle"),
        flags: kOptFlagSecure,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptModelineexpr, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MLE),
        ..BLANK
    },
    // 'modelines'
    VimOption {
        fullname: name(c"modelines"),
        shortname: name(c"mls"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptModelines, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MLS),
        def_val: number(5),
        ..BLANK
    },
    // 'modifiable'
    VimOption {
        fullname: name(c"modifiable"),
        shortname: name(c"ma"),
        flags: kOptFlagNoGlob,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModifiable),
        var: OptVar::Boolean(P_MA),
        opt_did_set_cb: Some(did_set_modifiable),
        def_val: boolean(true),
        ..BLANK
    },
    // 'modified'
    VimOption {
        fullname: name(c"modified"),
        shortname: name(c"mod"),
        flags: kOptFlagRedrStat | kOptFlagNoMkrc,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModified),
        var: OptVar::Boolean(P_MOD),
        opt_did_set_cb: Some(did_set_modified),
        ..BLANK
    },
    // 'more'
    VimOption {
        fullname: name(c"more"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMore, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MORE),
        def_val: boolean(true),
        ..BLANK
    },
    // 'mouse'
    VimOption {
        fullname: name(c"mouse"),
        flags: kOptFlagFlagList,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMouse, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOUSE),
        opt_did_set_cb: Some(did_set_mouse),
        opt_expand_cb: Some(expand_set_mouse),
        def_val: string(c"nvi"),
        ..BLANK
    },
    // 'mousefocus'
    VimOption {
        fullname: name(c"mousefocus"),
        shortname: name(c"mousef"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousefocus, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MOUSEF),
        ..BLANK
    },
    // 'mousehide'
    VimOption {
        fullname: name(c"mousehide"),
        shortname: name(c"mh"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousehide, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MH),
        def_val: boolean(true),
        ..BLANK
    },
    // 'mousemodel'
    VimOption {
        fullname: name(c"mousemodel"),
        shortname: name(c"mousem"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousemodel, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOUSEM),
        values: &opt_mousem_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"popup_setpos"),
        ..BLANK
    },
    // 'mousemoveevent'
    VimOption {
        fullname: name(c"mousemoveevent"),
        shortname: name(c"mousemev"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousemoveevent, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MOUSEMEV),
        ..BLANK
    },
    // 'mousescroll'
    VimOption {
        fullname: name(c"mousescroll"),
        flags: kOptFlagComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousescroll, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOUSESCROLL),
        values: &opt_mousescroll_values,
        opt_did_set_cb: Some(did_set_mousescroll),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"ver:3,hor:6"),
        ..BLANK
    },
    // 'mouseshape'
    VimOption {
        fullname: name(c"mouseshape"),
        shortname: name(c"mouses"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMouseshape, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'mousetime'
    VimOption {
        fullname: name(c"mousetime"),
        shortname: name(c"mouset"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousetime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MOUSET),
        def_val: number(500),
        ..BLANK
    },
    // 'nrformats'
    VimOption {
        fullname: name(c"nrformats"),
        shortname: name(c"nf"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptNrformats),
        var: OptVar::String(P_NF),
        values: &opt_nf_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"bin,hex"),
        ..BLANK
    },
    // 'number'
    VimOption {
        fullname: name(c"number"),
        shortname: name(c"nu"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptNumber, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_number_relativenumber),
        ..BLANK
    },
    // 'numberwidth'
    VimOption {
        fullname: name(c"numberwidth"),
        shortname: name(c"nuw"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptNumberwidth, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_numberwidth),
        def_val: number(4),
        ..BLANK
    },
    // 'omnifunc'
    VimOption {
        fullname: name(c"omnifunc"),
        shortname: name(c"ofu"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptOmnifunc),
        var: OptVar::String(P_OFU),
        opt_did_set_cb: Some(did_set_omnifunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'opendevice'
    VimOption {
        fullname: name(c"opendevice"),
        shortname: name(c"odev"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptOpendevice, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'operatorfunc'
    VimOption {
        fullname: name(c"operatorfunc"),
        shortname: name(c"opfunc"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptOperatorfunc, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_OPFUNC),
        opt_did_set_cb: Some(did_set_operatorfunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'packpath'
    VimOption {
        fullname: name(c"packpath"),
        shortname: name(c"pp"),
        flags: kOptFlagOneComma | kOptFlagExpand | kOptFlagSecure | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPackpath, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PP),
        opt_did_set_cb: Some(did_set_runtimepackpath),
        def_val: string(c""),
        ..BLANK
    },
    // 'paragraphs'
    VimOption {
        fullname: name(c"paragraphs"),
        shortname: name(c"para"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptParagraphs, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PARA),
        def_val: string(c"IPLPPPQPP TPHPLIPpLpItpplpipbp"),
        ..BLANK
    },
    // 'paste'
    VimOption {
        fullname: name(c"paste"),
        flags: kOptFlagPriMkrc,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPaste, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_PASTE),
        opt_did_set_cb: Some(did_set_paste),
        ..BLANK
    },
    // 'pastetoggle'
    VimOption {
        fullname: name(c"pastetoggle"),
        shortname: name(c"pt"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPastetoggle, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'patchexpr'
    VimOption {
        fullname: name(c"patchexpr"),
        shortname: name(c"pex"),
        flags: kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPatchexpr, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PEX),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'patchmode'
    VimOption {
        fullname: name(c"patchmode"),
        shortname: name(c"pm"),
        flags: kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPatchmode, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PM),
        opt_did_set_cb: Some(did_set_backupext_or_patchmode),
        def_val: string(c""),
        ..BLANK
    },
    // 'path'
    VimOption {
        fullname: name(c"path"),
        shortname: name(c"pa"),
        flags: kOptFlagComma | kOptFlagExpand | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptPath, kWinOptInvalid, kBufOptPath),
        var: OptVar::String(P_PATH),
        def_val: string(c".,,"),
        ..BLANK
    },
    // 'preserveindent'
    VimOption {
        fullname: name(c"preserveindent"),
        shortname: name(c"pi"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptPreserveindent),
        var: OptVar::Boolean(P_PI),
        ..BLANK
    },
    // 'previewheight'
    VimOption {
        fullname: name(c"previewheight"),
        shortname: name(c"pvh"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPreviewheight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PVH),
        def_val: number(12),
        ..BLANK
    },
    // 'previewwindow'
    VimOption {
        fullname: name(c"previewwindow"),
        shortname: name(c"pvw"),
        flags: kOptFlagRedrStat | kOptFlagNoGlob,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptPreviewwindow, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_previewwindow),
        ..BLANK
    },
    // 'prompt'
    VimOption {
        fullname: name(c"prompt"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPrompt, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: boolean(true),
        ..BLANK
    },
    // 'pumblend'
    VimOption {
        fullname: name(c"pumblend"),
        shortname: name(c"pb"),
        flags: kOptFlagUIOption,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumblend, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PB),
        opt_did_set_cb: Some(did_set_pumblend),
        def_val: number(0),
        ..BLANK
    },
    // 'pumborder'
    VimOption {
        fullname: name(c"pumborder"),
        flags: kOptFlagOneComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumborder, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PUMBORDER),
        values: &opt_pumborder_values,
        opt_did_set_cb: Some(did_set_pumborder),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'pumheight'
    VimOption {
        fullname: name(c"pumheight"),
        shortname: name(c"ph"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumheight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PH),
        def_val: number(0),
        ..BLANK
    },
    // 'pummaxwidth'
    VimOption {
        fullname: name(c"pummaxwidth"),
        shortname: name(c"pmw"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPummaxwidth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PMW),
        def_val: number(0),
        ..BLANK
    },
    // 'pumwidth'
    VimOption {
        fullname: name(c"pumwidth"),
        shortname: name(c"pw"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumwidth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PW),
        def_val: number(15),
        ..BLANK
    },
    // 'pyxversion'
    VimOption {
        fullname: name(c"pyxversion"),
        shortname: name(c"pyx"),
        flags: kOptFlagSecure,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPyxversion, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PYX),
        def_val: number(3),
        ..BLANK
    },
    // 'quickfixtextfunc'
    VimOption {
        fullname: name(c"quickfixtextfunc"),
        shortname: name(c"qftf"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptQuickfixtextfunc, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_QFTF),
        opt_did_set_cb: Some(did_set_quickfixtextfunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'quoteescape'
    VimOption {
        fullname: name(c"quoteescape"),
        shortname: name(c"qe"),
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptQuoteescape),
        var: OptVar::String(P_QE),
        def_val: string(c"\\"),
        ..BLANK
    },
    // 'readonly'
    VimOption {
        fullname: name(c"readonly"),
        shortname: name(c"ro"),
        flags: kOptFlagRedrStat | kOptFlagNoGlob,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptReadonly),
        var: OptVar::Boolean(P_RO),
        opt_did_set_cb: Some(did_set_readonly),
        ..BLANK
    },
    // 'redrawdebug'
    VimOption {
        fullname: name(c"redrawdebug"),
        shortname: name(c"rdb"),
        flags: kOptFlagOneComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRedrawdebug, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_RDB),
        flags_var: Some(&rdb_flags),
        values: &opt_rdb_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'redrawtime'
    VimOption {
        fullname: name(c"redrawtime"),
        shortname: name(c"rdt"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRedrawtime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_RDT),
        def_val: number(2000),
        ..BLANK
    },
    // 'regexpengine'
    VimOption {
        fullname: name(c"regexpengine"),
        shortname: name(c"re"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRegexpengine, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_RE),
        def_val: number(0),
        ..BLANK
    },
    // 'relativenumber'
    VimOption {
        fullname: name(c"relativenumber"),
        shortname: name(c"rnu"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptRelativenumber, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_number_relativenumber),
        ..BLANK
    },
    // 'remap'
    VimOption {
        fullname: name(c"remap"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRemap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: boolean(true),
        ..BLANK
    },
    // 'report'
    VimOption {
        fullname: name(c"report"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptReport, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_REPORT),
        def_val: number(2),
        ..BLANK
    },
    // 'revins'
    VimOption {
        fullname: name(c"revins"),
        shortname: name(c"ri"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRevins, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_RI),
        ..BLANK
    },
];
