//! A run of the option table's rows.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![forbid(unsafe_code)]
#![deny(
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::ptr_as_ptr
)]

// A chunk may hold nothing that needs the parent's support code.
#[allow(unused_imports)]
use super::*;

/// This file's run of the option table, spliced in by the parent.
pub(super) const PART: [VimOption; 81] = [
    // 'jumpoptions'
    VimOption {
        fullname: c"jumpoptions",
        shortname: Some(c"jop"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptJumpoptions, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_JOP),
        flags_var: Some(&jop_flags),
        values: &opt_jop_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"clean"),
        ..BLANK
    },
    // 'keymap'
    VimOption {
        fullname: c"keymap",
        shortname: Some(c"kmp"),
        flags: kOptFlagRedrStat | kOptFlagRedrBuf | kOptFlagNFname | kOptFlagPriMkrc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptKeymap),
        var: OptVar::String(P_KEYMAP),
        opt_did_set_cb: Some(did_set_keymap),
        def_val: string(c""),
        ..BLANK
    },
    // 'keymodel'
    VimOption {
        fullname: c"keymodel",
        shortname: Some(c"km"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptKeymodel, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_KM),
        values: &opt_km_values,
        opt_did_set_cb: Some(did_set_keymodel),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'keywordprg'
    VimOption {
        fullname: c"keywordprg",
        shortname: Some(c"kp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptKeywordprg, kWinOptInvalid, kBufOptKeywordprg),
        var: OptVar::String(P_KP),
        def_val: string(c":Man"),
        ..BLANK
    },
    // 'langmap'
    VimOption {
        fullname: c"langmap",
        shortname: Some(c"lmap"),
        flags: kOptFlagOneComma | kOptFlagSecure | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangmap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_LANGMAP),
        opt_did_set_cb: Some(did_set_langmap),
        def_val: string(c""),
        ..BLANK
    },
    // 'langmenu'
    VimOption {
        fullname: c"langmenu",
        shortname: Some(c"lm"),
        flags: kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangmenu, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_LM),
        def_val: string(c""),
        ..BLANK
    },
    // 'langnoremap'
    VimOption {
        fullname: c"langnoremap",
        shortname: Some(c"lnr"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangnoremap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LNR),
        opt_did_set_cb: Some(did_set_langnoremap),
        def_val: boolean(true),
        ..BLANK
    },
    // 'langremap'
    VimOption {
        fullname: c"langremap",
        shortname: Some(c"lrm"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLangremap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LRM),
        opt_did_set_cb: Some(did_set_langremap),
        ..BLANK
    },
    // 'laststatus'
    VimOption {
        fullname: c"laststatus",
        shortname: Some(c"ls"),
        flags: kOptFlagRedrAll,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLaststatus, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_LS),
        opt_did_set_cb: Some(did_set_laststatus),
        def_val: number(2),
        ..BLANK
    },
    // 'lazyredraw'
    VimOption {
        fullname: c"lazyredraw",
        shortname: Some(c"lz"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLazyredraw, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LZ),
        ..BLANK
    },
    // 'lhistory'
    VimOption {
        fullname: c"lhistory",
        shortname: Some(c"lhi"),
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptLhistory, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_xhistory),
        def_val: number(10),
        ..BLANK
    },
    // 'linebreak'
    VimOption {
        fullname: c"linebreak",
        shortname: Some(c"lbr"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptLinebreak, kBufOptInvalid),
        ..BLANK
    },
    // 'lines'
    VimOption {
        fullname: c"lines",
        flags: kOptFlagNoMkrc,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLines, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_LINES),
        opt_did_set_cb: Some(did_set_lines_or_columns),
        def_val: number(DFLT_ROWS as OptInt),
        ..BLANK
    },
    // 'linespace'
    VimOption {
        fullname: c"linespace",
        shortname: Some(c"lsp"),
        flags: kOptFlagUIOption,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLinespace, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_LINESPACE),
        def_val: number(0),
        ..BLANK
    },
    // 'lisp'
    VimOption {
        fullname: c"lisp",
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptLisp),
        var: OptVar::Boolean(P_LISP),
        opt_did_set_cb: Some(did_set_lisp),
        ..BLANK
    },
    // 'lispoptions'
    VimOption {
        fullname: c"lispoptions",
        shortname: Some(c"lop"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptLispoptions),
        var: OptVar::String(P_LOP),
        values: &opt_lop_values,
        opt_did_set_cb: Some(did_set_lispoptions),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'lispwords'
    VimOption {
        fullname: c"lispwords",
        shortname: Some(c"lw"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptLispwords, kWinOptInvalid, kBufOptLispwords),
        var: OptVar::String(P_LISPWORDS),
        def_val: string(LISPWORD_VALUE),
        ..BLANK
    },
    // 'list'
    VimOption {
        fullname: c"list",
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptList, kBufOptInvalid),
        ..BLANK
    },
    // 'listchars'
    VimOption {
        fullname: c"listchars",
        shortname: Some(c"lcs"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagRedrWin | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | WIN,
        scope_idx: scope_idx(kGlobalOptListchars, kWinOptListchars, kBufOptInvalid),
        var: OptVar::String(P_LCS),
        opt_did_set_cb: Some(did_set_chars_option),
        opt_expand_cb: Some(expand_set_chars_option),
        def_val: string(c"tab:> ,trail:-,nbsp:+"),
        ..BLANK
    },
    // 'loadplugins'
    VimOption {
        fullname: c"loadplugins",
        shortname: Some(c"lpl"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptLoadplugins, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_LPL),
        def_val: boolean(true),
        ..BLANK
    },
    // 'magic'
    VimOption {
        fullname: c"magic",
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMagic, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MAGIC),
        def_val: boolean(true),
        ..BLANK
    },
    // 'makeef'
    VimOption {
        fullname: c"makeef",
        shortname: Some(c"mef"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMakeef, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MEF),
        def_val: string(c""),
        ..BLANK
    },
    // 'makeencoding'
    VimOption {
        fullname: c"makeencoding",
        shortname: Some(c"menc"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptMakeencoding, kWinOptInvalid, kBufOptMakeencoding),
        var: OptVar::String(P_MENC),
        opt_did_set_cb: Some(did_set_encoding),
        opt_expand_cb: Some(expand_set_encoding),
        def_val: string(c""),
        ..BLANK
    },
    // 'makeprg'
    VimOption {
        fullname: c"makeprg",
        shortname: Some(c"mp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptMakeprg, kWinOptInvalid, kBufOptMakeprg),
        var: OptVar::String(P_MP),
        def_val: string(c"make"),
        ..BLANK
    },
    // 'matchpairs'
    VimOption {
        fullname: c"matchpairs",
        shortname: Some(c"mps"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptMatchpairs),
        var: OptVar::String(P_MPS),
        opt_did_set_cb: Some(did_set_matchpairs),
        def_val: string(c"(:),{:},[:]"),
        ..BLANK
    },
    // 'matchtime'
    VimOption {
        fullname: c"matchtime",
        shortname: Some(c"mat"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMatchtime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MAT),
        def_val: number(5),
        ..BLANK
    },
    // 'maxcombine'
    VimOption {
        fullname: c"maxcombine",
        shortname: Some(c"mco"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxcombine, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MCO),
        def_val: number(MAX_MCO as OptInt),
        ..BLANK
    },
    // 'maxfuncdepth'
    VimOption {
        fullname: c"maxfuncdepth",
        shortname: Some(c"mfd"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxfuncdepth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MFD),
        def_val: number(100),
        ..BLANK
    },
    // 'maxmapdepth'
    VimOption {
        fullname: c"maxmapdepth",
        shortname: Some(c"mmd"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxmapdepth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MMD),
        def_val: number(1000),
        ..BLANK
    },
    // 'maxmempattern'
    VimOption {
        fullname: c"maxmempattern",
        shortname: Some(c"mmp"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxmempattern, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MMP),
        def_val: number(1000),
        ..BLANK
    },
    // 'maxsearchcount'
    VimOption {
        fullname: c"maxsearchcount",
        shortname: Some(c"msc"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMaxsearchcount, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MSC),
        def_val: number(999),
        ..BLANK
    },
    // 'menuitems'
    VimOption {
        fullname: c"menuitems",
        shortname: Some(c"mis"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMenuitems, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MIS),
        def_val: number(25),
        ..BLANK
    },
    // 'messagesopt'
    VimOption {
        fullname: c"messagesopt",
        shortname: Some(c"mopt"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMessagesopt, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOPT),
        values: &opt_mopt_values,
        opt_did_set_cb: Some(did_set_messagesopt),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"hit-enter,history:500,progress:c"),
        ..BLANK
    },
    // 'mkspellmem'
    VimOption {
        fullname: c"mkspellmem",
        shortname: Some(c"msm"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMkspellmem, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MSM),
        opt_did_set_cb: Some(did_set_mkspellmem),
        def_val: string(c"460000,2000,500"),
        ..BLANK
    },
    // 'modeline'
    VimOption {
        fullname: c"modeline",
        shortname: Some(c"ml"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModeline),
        var: OptVar::Boolean(P_ML),
        def_val: boolean(true),
        ..BLANK
    },
    // 'modelineexpr'
    VimOption {
        fullname: c"modelineexpr",
        shortname: Some(c"mle"),
        flags: kOptFlagSecure,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptModelineexpr, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MLE),
        ..BLANK
    },
    // 'modelines'
    VimOption {
        fullname: c"modelines",
        shortname: Some(c"mls"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptModelines, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MLS),
        def_val: number(5),
        ..BLANK
    },
    // 'modifiable'
    VimOption {
        fullname: c"modifiable",
        shortname: Some(c"ma"),
        flags: kOptFlagNoGlob,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModifiable),
        var: OptVar::Boolean(P_MA),
        opt_did_set_cb: Some(did_set_modifiable),
        def_val: boolean(true),
        ..BLANK
    },
    // 'modified'
    VimOption {
        fullname: c"modified",
        shortname: Some(c"mod"),
        flags: kOptFlagRedrStat | kOptFlagNoMkrc,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptModified),
        var: OptVar::Boolean(P_MOD),
        opt_did_set_cb: Some(did_set_modified),
        ..BLANK
    },
    // 'more'
    VimOption {
        fullname: c"more",
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMore, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MORE),
        def_val: boolean(true),
        ..BLANK
    },
    // 'mouse'
    VimOption {
        fullname: c"mouse",
        flags: kOptFlagFlagList,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMouse, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOUSE),
        opt_did_set_cb: Some(did_set_mouse),
        opt_expand_cb: Some(expand_set_mouse),
        def_val: string(c"nvi"),
        ..BLANK
    },
    // 'mousefocus'
    VimOption {
        fullname: c"mousefocus",
        shortname: Some(c"mousef"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousefocus, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MOUSEF),
        ..BLANK
    },
    // 'mousehide'
    VimOption {
        fullname: c"mousehide",
        shortname: Some(c"mh"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousehide, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MH),
        def_val: boolean(true),
        ..BLANK
    },
    // 'mousemodel'
    VimOption {
        fullname: c"mousemodel",
        shortname: Some(c"mousem"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousemodel, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOUSEM),
        values: &opt_mousem_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"popup_setpos"),
        ..BLANK
    },
    // 'mousemoveevent'
    VimOption {
        fullname: c"mousemoveevent",
        shortname: Some(c"mousemev"),
        flags: kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousemoveevent, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_MOUSEMEV),
        ..BLANK
    },
    // 'mousescroll'
    VimOption {
        fullname: c"mousescroll",
        flags: kOptFlagComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousescroll, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_MOUSESCROLL),
        values: &opt_mousescroll_values,
        opt_did_set_cb: Some(did_set_mousescroll),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"ver:3,hor:6"),
        ..BLANK
    },
    // 'mouseshape'
    VimOption {
        fullname: c"mouseshape",
        shortname: Some(c"mouses"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMouseshape, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'mousetime'
    VimOption {
        fullname: c"mousetime",
        shortname: Some(c"mouset"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptMousetime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_MOUSET),
        def_val: number(500),
        ..BLANK
    },
    // 'nrformats'
    VimOption {
        fullname: c"nrformats",
        shortname: Some(c"nf"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptNrformats),
        var: OptVar::String(P_NF),
        values: &opt_nf_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"bin,hex"),
        ..BLANK
    },
    // 'number'
    VimOption {
        fullname: c"number",
        shortname: Some(c"nu"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptNumber, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_number_relativenumber),
        ..BLANK
    },
    // 'numberwidth'
    VimOption {
        fullname: c"numberwidth",
        shortname: Some(c"nuw"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptNumberwidth, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_numberwidth),
        def_val: number(4),
        ..BLANK
    },
    // 'omnifunc'
    VimOption {
        fullname: c"omnifunc",
        shortname: Some(c"ofu"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptOmnifunc),
        var: OptVar::String(P_OFU),
        opt_did_set_cb: Some(did_set_omnifunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'opendevice'
    VimOption {
        fullname: c"opendevice",
        shortname: Some(c"odev"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptOpendevice, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'operatorfunc'
    VimOption {
        fullname: c"operatorfunc",
        shortname: Some(c"opfunc"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptOperatorfunc, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_OPFUNC),
        opt_did_set_cb: Some(did_set_operatorfunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'packpath'
    VimOption {
        fullname: c"packpath",
        shortname: Some(c"pp"),
        flags: kOptFlagOneComma | kOptFlagExpand | kOptFlagSecure | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPackpath, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PP),
        opt_did_set_cb: Some(did_set_runtimepackpath),
        def_val: string(c""),
        ..BLANK
    },
    // 'paragraphs'
    VimOption {
        fullname: c"paragraphs",
        shortname: Some(c"para"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptParagraphs, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PARA),
        def_val: string(c"IPLPPPQPP TPHPLIPpLpItpplpipbp"),
        ..BLANK
    },
    // 'paste'
    VimOption {
        fullname: c"paste",
        flags: kOptFlagPriMkrc,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPaste, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_PASTE),
        opt_did_set_cb: Some(did_set_paste),
        ..BLANK
    },
    // 'pastetoggle'
    VimOption {
        fullname: c"pastetoggle",
        shortname: Some(c"pt"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPastetoggle, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'patchexpr'
    VimOption {
        fullname: c"patchexpr",
        shortname: Some(c"pex"),
        flags: kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPatchexpr, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PEX),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'patchmode'
    VimOption {
        fullname: c"patchmode",
        shortname: Some(c"pm"),
        flags: kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPatchmode, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PM),
        opt_did_set_cb: Some(did_set_backupext_or_patchmode),
        def_val: string(c""),
        ..BLANK
    },
    // 'path'
    VimOption {
        fullname: c"path",
        shortname: Some(c"pa"),
        flags: kOptFlagComma | kOptFlagExpand | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptPath, kWinOptInvalid, kBufOptPath),
        var: OptVar::String(P_PATH),
        def_val: string(c".,,"),
        ..BLANK
    },
    // 'preserveindent'
    VimOption {
        fullname: c"preserveindent",
        shortname: Some(c"pi"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptPreserveindent),
        var: OptVar::Boolean(P_PI),
        ..BLANK
    },
    // 'previewheight'
    VimOption {
        fullname: c"previewheight",
        shortname: Some(c"pvh"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPreviewheight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PVH),
        def_val: number(12),
        ..BLANK
    },
    // 'previewwindow'
    VimOption {
        fullname: c"previewwindow",
        shortname: Some(c"pvw"),
        flags: kOptFlagRedrStat | kOptFlagNoGlob,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptPreviewwindow, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_previewwindow),
        ..BLANK
    },
    // 'prompt'
    VimOption {
        fullname: c"prompt",
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPrompt, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: boolean(true),
        ..BLANK
    },
    // 'pumblend'
    VimOption {
        fullname: c"pumblend",
        shortname: Some(c"pb"),
        flags: kOptFlagUIOption,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumblend, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PB),
        opt_did_set_cb: Some(did_set_pumblend),
        def_val: number(0),
        ..BLANK
    },
    // 'pumborder'
    VimOption {
        fullname: c"pumborder",
        flags: kOptFlagOneComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumborder, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_PUMBORDER),
        values: &opt_pumborder_values,
        opt_did_set_cb: Some(did_set_pumborder),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'pumheight'
    VimOption {
        fullname: c"pumheight",
        shortname: Some(c"ph"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumheight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PH),
        def_val: number(0),
        ..BLANK
    },
    // 'pummaxwidth'
    VimOption {
        fullname: c"pummaxwidth",
        shortname: Some(c"pmw"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPummaxwidth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PMW),
        def_val: number(0),
        ..BLANK
    },
    // 'pumwidth'
    VimOption {
        fullname: c"pumwidth",
        shortname: Some(c"pw"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPumwidth, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PW),
        def_val: number(15),
        ..BLANK
    },
    // 'pyxversion'
    VimOption {
        fullname: c"pyxversion",
        shortname: Some(c"pyx"),
        flags: kOptFlagSecure,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptPyxversion, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_PYX),
        def_val: number(3),
        ..BLANK
    },
    // 'quickfixtextfunc'
    VimOption {
        fullname: c"quickfixtextfunc",
        shortname: Some(c"qftf"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptQuickfixtextfunc, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_QFTF),
        opt_did_set_cb: Some(did_set_quickfixtextfunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'quoteescape'
    VimOption {
        fullname: c"quoteescape",
        shortname: Some(c"qe"),
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptQuoteescape),
        var: OptVar::String(P_QE),
        def_val: string(c"\\"),
        ..BLANK
    },
    // 'readonly'
    VimOption {
        fullname: c"readonly",
        shortname: Some(c"ro"),
        flags: kOptFlagRedrStat | kOptFlagNoGlob,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptReadonly),
        var: OptVar::Boolean(P_RO),
        opt_did_set_cb: Some(did_set_readonly),
        ..BLANK
    },
    // 'redrawdebug'
    VimOption {
        fullname: c"redrawdebug",
        shortname: Some(c"rdb"),
        flags: kOptFlagOneComma,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRedrawdebug, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_RDB),
        flags_var: Some(&rdb_flags),
        values: &opt_rdb_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'redrawtime'
    VimOption {
        fullname: c"redrawtime",
        shortname: Some(c"rdt"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRedrawtime, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_RDT),
        def_val: number(2000),
        ..BLANK
    },
    // 'regexpengine'
    VimOption {
        fullname: c"regexpengine",
        shortname: Some(c"re"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRegexpengine, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_RE),
        def_val: number(0),
        ..BLANK
    },
    // 'relativenumber'
    VimOption {
        fullname: c"relativenumber",
        shortname: Some(c"rnu"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptRelativenumber, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_number_relativenumber),
        ..BLANK
    },
    // 'remap'
    VimOption {
        fullname: c"remap",
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRemap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: boolean(true),
        ..BLANK
    },
    // 'report'
    VimOption {
        fullname: c"report",
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptReport, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_REPORT),
        def_val: number(2),
        ..BLANK
    },
    // 'revins'
    VimOption {
        fullname: c"revins",
        shortname: Some(c"ri"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptRevins, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_RI),
        ..BLANK
    },
];
