//! A run of the option table's rows.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![forbid(unsafe_code)]
#![deny(
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::ptr_as_ptr
)]

// A chunk may hold nothing that needs the parent's support code.
#[allow(unused_imports)]
use super::*;

/// This file's run of the option table, spliced in by the parent.
pub(super) const PART: [VimOption; 78] = [
    // 'emoji'
    VimOption {
        fullname: c"emoji",
        shortname: Some(c"emo"),
        flags: kOptFlagRedrAll | kOptFlagUIOption,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptEmoji, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_EMOJI),
        opt_did_set_cb: Some(did_set_emoji),
        def_val: boolean(true),
        ..BLANK
    },
    // 'encoding'
    VimOption {
        fullname: c"encoding",
        shortname: Some(c"enc"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptEncoding, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_ENC),
        opt_did_set_cb: Some(did_set_encoding),
        def_val: string(ENC_DFLT),
        ..BLANK
    },
    // 'endoffile'
    VimOption {
        fullname: c"endoffile",
        shortname: Some(c"eof"),
        flags: kOptFlagRedrStat | kOptFlagNoMkrc,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptEndoffile),
        var: OptVar::Boolean(P_EOF),
        opt_did_set_cb: Some(did_set_eof_eol_fixeol_bomb),
        ..BLANK
    },
    // 'endofline'
    VimOption {
        fullname: c"endofline",
        shortname: Some(c"eol"),
        flags: kOptFlagRedrStat | kOptFlagNoMkrc,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptEndofline),
        var: OptVar::Boolean(P_EOL),
        opt_did_set_cb: Some(did_set_eof_eol_fixeol_bomb),
        def_val: boolean(true),
        ..BLANK
    },
    // 'equalalways'
    VimOption {
        fullname: c"equalalways",
        shortname: Some(c"ea"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptEqualalways, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_EA),
        opt_did_set_cb: Some(did_set_equalalways),
        def_val: boolean(true),
        ..BLANK
    },
    // 'equalprg'
    VimOption {
        fullname: c"equalprg",
        shortname: Some(c"ep"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptEqualprg, kWinOptInvalid, kBufOptEqualprg),
        var: OptVar::String(P_EP),
        def_val: string(c""),
        ..BLANK
    },
    // 'errorbells'
    VimOption {
        fullname: c"errorbells",
        shortname: Some(c"eb"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptErrorbells, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_EB),
        ..BLANK
    },
    // 'errorfile'
    VimOption {
        fullname: c"errorfile",
        shortname: Some(c"ef"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptErrorfile, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_EF),
        def_val: string(DFLT_ERRORFILE),
        ..BLANK
    },
    // 'errorformat'
    VimOption {
        fullname: c"errorformat",
        shortname: Some(c"efm"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptErrorformat, kWinOptInvalid, kBufOptErrorformat),
        var: OptVar::String(P_EFM),
        def_val: string(DFLT_EFM),
        ..BLANK
    },
    // 'eventignore'
    VimOption {
        fullname: c"eventignore",
        shortname: Some(c"ei"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptEventignore, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_EI),
        opt_did_set_cb: Some(did_set_eventignore),
        opt_expand_cb: Some(expand_set_eventignore),
        def_val: string(c""),
        ..BLANK
    },
    // 'eventignorewin'
    VimOption {
        fullname: c"eventignorewin",
        shortname: Some(c"eiw"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptEventignorewin, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_eventignore),
        opt_expand_cb: Some(expand_set_eventignore),
        def_val: string(c""),
        ..BLANK
    },
    // 'expandtab'
    VimOption {
        fullname: c"expandtab",
        shortname: Some(c"et"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptExpandtab),
        var: OptVar::Boolean(P_ET),
        ..BLANK
    },
    // 'exrc'
    VimOption {
        fullname: c"exrc",
        shortname: Some(c"ex"),
        flags: kOptFlagSecure,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptExrc, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_EXRC),
        ..BLANK
    },
    // 'fileencoding'
    VimOption {
        fullname: c"fileencoding",
        shortname: Some(c"fenc"),
        flags: kOptFlagRedrStat | kOptFlagRedrBuf | kOptFlagNoMkrc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptFileencoding),
        var: OptVar::String(P_FENC),
        opt_did_set_cb: Some(did_set_encoding),
        opt_expand_cb: Some(expand_set_encoding),
        def_val: string(c""),
        ..BLANK
    },
    // 'fileencodings'
    VimOption {
        fullname: c"fileencodings",
        shortname: Some(c"fencs"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptFileencodings, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_FENCS),
        opt_expand_cb: Some(expand_set_encoding),
        def_val: string(c"ucs-bom,utf-8,default,latin1"),
        ..BLANK
    },
    // 'fileformat'
    VimOption {
        fullname: c"fileformat",
        shortname: Some(c"ff"),
        flags: kOptFlagCurswant | kOptFlagRedrStat | kOptFlagNoMkrc,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptFileformat),
        var: OptVar::String(P_FF),
        values: &opt_ff_values,
        opt_did_set_cb: Some(did_set_fileformat),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"unix"),
        ..BLANK
    },
    // 'fileformats'
    VimOption {
        fullname: c"fileformats",
        shortname: Some(c"ffs"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptFileformats, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_FFS),
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"unix,dos"),
        ..BLANK
    },
    // 'fileignorecase'
    VimOption {
        fullname: c"fileignorecase",
        shortname: Some(c"fic"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptFileignorecase, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_FIC),
        ..BLANK
    },
    // 'filetype'
    VimOption {
        fullname: c"filetype",
        shortname: Some(c"ft"),
        flags: kOptFlagNoGlob | kOptFlagNFname,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptFiletype),
        var: OptVar::String(P_FT),
        opt_did_set_cb: Some(did_set_filetype_or_syntax),
        def_val: string(c""),
        ..BLANK
    },
    // 'fillchars'
    VimOption {
        fullname: c"fillchars",
        shortname: Some(c"fcs"),
        flags: kOptFlagOneComma | kOptFlagColon | kOptFlagRedrWin | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | WIN,
        scope_idx: scope_idx(kGlobalOptFillchars, kWinOptFillchars, kBufOptInvalid),
        var: OptVar::String(P_FCS),
        opt_did_set_cb: Some(did_set_chars_option),
        opt_expand_cb: Some(expand_set_chars_option),
        def_val: string(c""),
        ..BLANK
    },
    // 'findfunc'
    VimOption {
        fullname: c"findfunc",
        shortname: Some(c"ffu"),
        flags: kOptFlagSecure | kOptFlagFunc,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptFindfunc, kWinOptInvalid, kBufOptFindfunc),
        var: OptVar::String(P_FFU),
        opt_did_set_cb: Some(did_set_findfunc),
        def_val: string(c""),
        ..BLANK
    },
    // 'fixendofline'
    VimOption {
        fullname: c"fixendofline",
        shortname: Some(c"fixeol"),
        flags: kOptFlagRedrStat,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptFixendofline),
        var: OptVar::Boolean(P_FIXEOL),
        opt_did_set_cb: Some(did_set_eof_eol_fixeol_bomb),
        def_val: boolean(true),
        ..BLANK
    },
    // 'foldclose'
    VimOption {
        fullname: c"foldclose",
        shortname: Some(c"fcl"),
        flags: kOptFlagOneComma | kOptFlagRedrWin | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptFoldclose, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_FCL),
        values: &opt_fcl_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c""),
        ..BLANK
    },
    // 'foldcolumn'
    VimOption {
        fullname: c"foldcolumn",
        shortname: Some(c"fdc"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldcolumn, kBufOptInvalid),
        values: &opt_fdc_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"0"),
        ..BLANK
    },
    // 'foldenable'
    VimOption {
        fullname: c"foldenable",
        shortname: Some(c"fen"),
        flags: kOptFlagRedrWin,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldenable, kBufOptInvalid),
        def_val: boolean(true),
        ..BLANK
    },
    // 'foldexpr'
    VimOption {
        fullname: c"foldexpr",
        shortname: Some(c"fde"),
        flags: kOptFlagRedrWin | kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldexpr, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_foldexpr),
        def_val: string(c"0"),
        ..BLANK
    },
    // 'foldignore'
    VimOption {
        fullname: c"foldignore",
        shortname: Some(c"fdi"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldignore, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_foldignore),
        def_val: string(c"#"),
        ..BLANK
    },
    // 'foldlevel'
    VimOption {
        fullname: c"foldlevel",
        shortname: Some(c"fdl"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldlevel, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_foldlevel),
        def_val: number(0),
        ..BLANK
    },
    // 'foldlevelstart'
    VimOption {
        fullname: c"foldlevelstart",
        shortname: Some(c"fdls"),
        flags: kOptFlagCurswant,
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptFoldlevelstart, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_FDLS),
        def_val: number(-1),
        ..BLANK
    },
    // 'foldmarker'
    VimOption {
        fullname: c"foldmarker",
        shortname: Some(c"fmr"),
        flags: kOptFlagOneComma | kOptFlagRedrWin | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldmarker, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_foldmarker),
        def_val: string(c"{{{,}}}"),
        ..BLANK
    },
    // 'foldmethod'
    VimOption {
        fullname: c"foldmethod",
        shortname: Some(c"fdm"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldmethod, kBufOptInvalid),
        values: &opt_fdm_values,
        opt_did_set_cb: Some(did_set_foldmethod),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"manual"),
        ..BLANK
    },
    // 'foldminlines'
    VimOption {
        fullname: c"foldminlines",
        shortname: Some(c"fml"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldminlines, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_foldminlines),
        def_val: number(1),
        ..BLANK
    },
    // 'foldnestmax'
    VimOption {
        fullname: c"foldnestmax",
        shortname: Some(c"fdn"),
        flags: kOptFlagRedrWin,
        type_0: kOptValTypeNumber,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldnestmax, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_foldnestmax),
        def_val: number(20),
        ..BLANK
    },
    // 'foldopen'
    VimOption {
        fullname: c"foldopen",
        shortname: Some(c"fdo"),
        flags: kOptFlagOneComma | kOptFlagCurswant | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptFoldopen, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_FDO),
        flags_var: Some(&fdo_flags),
        values: &opt_fdo_values,
        opt_did_set_cb: Some(did_set_str_generic),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"block,hor,mark,percent,quickfix,search,tag,undo"),
        ..BLANK
    },
    // 'foldtext'
    VimOption {
        fullname: c"foldtext",
        shortname: Some(c"fdt"),
        flags: kOptFlagRedrWin | kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: WIN,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptFoldtext, kBufOptInvalid),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c"foldtext()"),
        ..BLANK
    },
    // 'formatexpr'
    VimOption {
        fullname: c"formatexpr",
        shortname: Some(c"fex"),
        flags: kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptFormatexpr),
        var: OptVar::String(P_FEX),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'formatlistpat'
    VimOption {
        fullname: c"formatlistpat",
        shortname: Some(c"flp"),
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptFormatlistpat),
        var: OptVar::String(P_FLP),
        def_val: string(c"^\\s*\\d\\+[\\]:.)}\\t ]\\s*"),
        ..BLANK
    },
    // 'formatoptions'
    VimOption {
        fullname: c"formatoptions",
        shortname: Some(c"fo"),
        flags: kOptFlagFlagList,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptFormatoptions),
        var: OptVar::String(P_FO),
        opt_did_set_cb: Some(did_set_formatoptions),
        opt_expand_cb: Some(expand_set_formatoptions),
        def_val: string(DFLT_FO_VIM),
        ..BLANK
    },
    // 'formatprg'
    VimOption {
        fullname: c"formatprg",
        shortname: Some(c"fp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptFormatprg, kWinOptInvalid, kBufOptFormatprg),
        var: OptVar::String(P_FP),
        def_val: string(c""),
        ..BLANK
    },
    // 'fsync'
    VimOption {
        fullname: c"fsync",
        shortname: Some(c"fs"),
        flags: kOptFlagSecure,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptFsync, kWinOptInvalid, kBufOptFsync),
        var: OptVar::Boolean(P_FS),
        def_val: boolean(true),
        ..BLANK
    },
    // 'gdefault'
    VimOption {
        fullname: c"gdefault",
        shortname: Some(c"gd"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptGdefault, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_GD),
        ..BLANK
    },
    // 'grepformat'
    VimOption {
        fullname: c"grepformat",
        shortname: Some(c"gfm"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptGrepformat, kWinOptInvalid, kBufOptGrepformat),
        var: OptVar::String(P_GEFM),
        def_val: string(DFLT_GREPFORMAT),
        ..BLANK
    },
    // 'grepprg'
    VimOption {
        fullname: c"grepprg",
        shortname: Some(c"gp"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptGrepprg, kWinOptInvalid, kBufOptGrepprg),
        var: OptVar::String(P_GP),
        def_val: string(c"grep -HIn $* /dev/null"),
        ..BLANK
    },
    // 'guicursor'
    VimOption {
        fullname: c"guicursor",
        shortname: Some(c"gcr"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptGuicursor, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_GUICURSOR),
        opt_did_set_cb: Some(did_set_guicursor),
        def_val: string(
            c"n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,t:block-blinkon500-blinkoff500-TermCursor",
        ),
        ..BLANK
    },
    // 'guifont'
    VimOption {
        fullname: c"guifont",
        shortname: Some(c"gfn"),
        flags: kOptFlagOneComma | kOptFlagUIOption | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptGuifont, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_GUIFONT),
        def_val: string(DFLT_GFN),
        ..BLANK
    },
    // 'guifontwide'
    VimOption {
        fullname: c"guifontwide",
        shortname: Some(c"gfw"),
        flags: kOptFlagOneComma | kOptFlagUIOption | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptGuifontwide, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_GUIFONTWIDE),
        def_val: string(c""),
        ..BLANK
    },
    // 'guioptions'
    VimOption {
        fullname: c"guioptions",
        shortname: Some(c"go"),
        flags: kOptFlagFlagList,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptGuioptions, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'guitablabel'
    VimOption {
        fullname: c"guitablabel",
        shortname: Some(c"gtl"),
        flags: kOptFlagRedrWin | kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptGuitablabel, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'guitabtooltip'
    VimOption {
        fullname: c"guitabtooltip",
        shortname: Some(c"gtt"),
        flags: kOptFlagRedrWin | kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptGuitabtooltip, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        def_val: string(c""),
        ..BLANK
    },
    // 'helpfile'
    VimOption {
        fullname: c"helpfile",
        shortname: Some(c"hf"),
        flags: kOptFlagExpand | kOptFlagSecure,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHelpfile, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_HF),
        opt_did_set_cb: Some(did_set_helpfile),
        def_val: string(DFLT_HELPFILE),
        ..BLANK
    },
    // 'helpheight'
    VimOption {
        fullname: c"helpheight",
        shortname: Some(c"hh"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHelpheight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_HH),
        opt_did_set_cb: Some(did_set_helpheight),
        def_val: number(20),
        ..BLANK
    },
    // 'helplang'
    VimOption {
        fullname: c"helplang",
        shortname: Some(c"hlg"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHelplang, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_HLG),
        opt_did_set_cb: Some(did_set_helplang),
        def_val: string(c""),
        ..BLANK
    },
    // 'hidden'
    VimOption {
        fullname: c"hidden",
        shortname: Some(c"hid"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHidden, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_HID),
        def_val: boolean(true),
        ..BLANK
    },
    // 'highlight'
    VimOption {
        fullname: c"highlight",
        shortname: Some(c"hl"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHighlight, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_HL),
        opt_did_set_cb: Some(did_set_highlight),
        def_val: string(HIGHLIGHT_INIT),
        ..BLANK
    },
    // 'history'
    VimOption {
        fullname: c"history",
        shortname: Some(c"hi"),
        type_0: kOptValTypeNumber,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHistory, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Number(P_HI),
        def_val: number(10000),
        ..BLANK
    },
    // 'hkmap'
    VimOption {
        fullname: c"hkmap",
        shortname: Some(c"hk"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHkmap, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'hkmapp'
    VimOption {
        fullname: c"hkmapp",
        shortname: Some(c"hkp"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHkmapp, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'hlsearch'
    VimOption {
        fullname: c"hlsearch",
        shortname: Some(c"hls"),
        flags: kOptFlagRedrAll | kOptFlagHLOnly,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptHlsearch, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_HLS),
        opt_did_set_cb: Some(did_set_hlsearch),
        def_val: boolean(true),
        ..BLANK
    },
    // 'icon'
    VimOption {
        fullname: c"icon",
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptIcon, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_ICON),
        opt_did_set_cb: Some(did_set_title_icon),
        ..BLANK
    },
    // 'iconstring'
    VimOption {
        fullname: c"iconstring",
        flags: kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptIconstring, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_ICONSTRING),
        opt_did_set_cb: Some(did_set_iconstring),
        def_val: string(c""),
        ..BLANK
    },
    // 'ignorecase'
    VimOption {
        fullname: c"ignorecase",
        shortname: Some(c"ic"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptIgnorecase, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_IC),
        opt_did_set_cb: Some(did_set_ignorecase),
        ..BLANK
    },
    // 'imcmdline'
    VimOption {
        fullname: c"imcmdline",
        shortname: Some(c"imc"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptImcmdline, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'imdisable'
    VimOption {
        fullname: c"imdisable",
        shortname: Some(c"imd"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptImdisable, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'iminsert'
    VimOption {
        fullname: c"iminsert",
        shortname: Some(c"imi"),
        type_0: kOptValTypeNumber,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptIminsert),
        var: OptVar::Number(P_IMINSERT),
        opt_did_set_cb: Some(did_set_iminsert),
        def_val: number(B_IMODE_NONE as OptInt),
        ..BLANK
    },
    // 'imsearch'
    VimOption {
        fullname: c"imsearch",
        shortname: Some(c"ims"),
        type_0: kOptValTypeNumber,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptImsearch),
        var: OptVar::Number(P_IMSEARCH),
        def_val: number(B_IMODE_USE_INSERT as OptInt),
        ..BLANK
    },
    // 'inccommand'
    VimOption {
        fullname: c"inccommand",
        shortname: Some(c"icm"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptInccommand, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_ICM),
        values: &opt_icm_values,
        opt_did_set_cb: Some(did_set_inccommand),
        opt_expand_cb: Some(expand_set_str_generic),
        def_val: string(c"nosplit"),
        ..BLANK
    },
    // 'include'
    VimOption {
        fullname: c"include",
        shortname: Some(c"inc"),
        type_0: kOptValTypeString,
        scope_flags: GLOBAL | BUF,
        scope_idx: scope_idx(kGlobalOptInclude, kWinOptInvalid, kBufOptInclude),
        var: OptVar::String(P_INC),
        def_val: string(c""),
        ..BLANK
    },
    // 'includeexpr'
    VimOption {
        fullname: c"includeexpr",
        shortname: Some(c"inex"),
        flags: kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptIncludeexpr),
        var: OptVar::String(P_INEX),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'incsearch'
    VimOption {
        fullname: c"incsearch",
        shortname: Some(c"is"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptIncsearch, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_IS),
        def_val: boolean(true),
        ..BLANK
    },
    // 'indentexpr'
    VimOption {
        fullname: c"indentexpr",
        shortname: Some(c"inde"),
        flags: kOptFlagMLE,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptIndentexpr),
        var: OptVar::String(P_INDE),
        opt_did_set_cb: Some(did_set_optexpr),
        def_val: string(c""),
        ..BLANK
    },
    // 'indentkeys'
    VimOption {
        fullname: c"indentkeys",
        shortname: Some(c"indk"),
        flags: kOptFlagOneComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptIndentkeys),
        var: OptVar::String(P_INDK),
        def_val: string(c"0{,0},0),0],:,0#,!^F,o,O,e"),
        ..BLANK
    },
    // 'infercase'
    VimOption {
        fullname: c"infercase",
        shortname: Some(c"inf"),
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptInfercase),
        var: OptVar::Boolean(P_INF),
        ..BLANK
    },
    // 'insertmode'
    VimOption {
        fullname: c"insertmode",
        shortname: Some(c"im"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptInsertmode, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::OwnDefault,
        immutable: true,
        ..BLANK
    },
    // 'isfname'
    VimOption {
        fullname: c"isfname",
        shortname: Some(c"isf"),
        flags: kOptFlagComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptIsfname, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_ISF),
        opt_did_set_cb: Some(did_set_isopt),
        def_val: string(c"@,48-57,/,.,-,_,+,,,#,$,%,~,="),
        ..BLANK
    },
    // 'isident'
    VimOption {
        fullname: c"isident",
        shortname: Some(c"isi"),
        flags: kOptFlagComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptIsident, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_ISI),
        opt_did_set_cb: Some(did_set_isopt),
        def_val: string(c"@,48-57,_,192-255"),
        ..BLANK
    },
    // 'iskeyword'
    VimOption {
        fullname: c"iskeyword",
        shortname: Some(c"isk"),
        flags: kOptFlagComma | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: BUF,
        scope_idx: scope_idx(kGlobalOptInvalid, kWinOptInvalid, kBufOptIskeyword),
        var: OptVar::String(P_ISK),
        opt_did_set_cb: Some(did_set_iskeyword),
        def_val: string(c"@,48-57,_,192-255"),
        ..BLANK
    },
    // 'isprint'
    VimOption {
        fullname: c"isprint",
        shortname: Some(c"isp"),
        flags: kOptFlagComma | kOptFlagRedrAll | kOptFlagNoDup,
        type_0: kOptValTypeString,
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptIsprint, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::String(P_ISP),
        opt_did_set_cb: Some(did_set_isopt),
        def_val: string(c"@,161-255"),
        ..BLANK
    },
    // 'joinspaces'
    VimOption {
        fullname: c"joinspaces",
        shortname: Some(c"js"),
        scope_flags: GLOBAL,
        scope_idx: scope_idx(kGlobalOptJoinspaces, kWinOptInvalid, kBufOptInvalid),
        var: OptVar::Boolean(P_JS),
        ..BLANK
    },
];
