/// Static assertions validating that Rust's WinStruct matches C's win_T layout.
///
/// These compile-time checks ensure every field accessed directly from Rust
/// has the correct offset and the overall struct size matches.

#include <stddef.h>
#include "nvim/buffer_defs.h"
#include "nvim/grid_defs.h"
#include "nvim/map_defs.h"

// Overall struct size
_Static_assert(sizeof(win_T) == 10968, "win_T size mismatch: update WinStruct in win_struct.rs");

// Top-level fields
_Static_assert(offsetof(win_T, handle) == 0, "handle offset mismatch");
_Static_assert(offsetof(win_T, w_buffer) == 8, "w_buffer offset mismatch");
_Static_assert(offsetof(win_T, w_s) == 16, "w_s offset mismatch");
_Static_assert(offsetof(win_T, w_ns_hl) == 24, "w_ns_hl offset mismatch");
_Static_assert(offsetof(win_T, w_ns_hl_winhl) == 28, "w_ns_hl_winhl offset mismatch");
_Static_assert(offsetof(win_T, w_ns_hl_active) == 32, "w_ns_hl_active offset mismatch");
_Static_assert(offsetof(win_T, w_ns_hl_attr) == 40, "w_ns_hl_attr offset mismatch");
_Static_assert(offsetof(win_T, w_ns_set) == 48, "w_ns_set offset mismatch");
_Static_assert(offsetof(win_T, w_hl_id_normal) == 88, "w_hl_id_normal offset mismatch");
_Static_assert(offsetof(win_T, w_hl_attr_normal) == 92, "w_hl_attr_normal offset mismatch");
_Static_assert(offsetof(win_T, w_hl_attr_normalnc) == 96, "w_hl_attr_normalnc offset mismatch");
_Static_assert(offsetof(win_T, w_hl_needs_update) == 100, "w_hl_needs_update offset mismatch");
_Static_assert(offsetof(win_T, w_prev) == 104, "w_prev offset mismatch");
_Static_assert(offsetof(win_T, w_next) == 112, "w_next offset mismatch");
_Static_assert(offsetof(win_T, w_locked) == 120, "w_locked offset mismatch");
_Static_assert(offsetof(win_T, w_frame) == 128, "w_frame offset mismatch");
_Static_assert(offsetof(win_T, w_cursor) == 136, "w_cursor offset mismatch");
_Static_assert(offsetof(win_T, w_curswant) == 148, "w_curswant offset mismatch");
_Static_assert(offsetof(win_T, w_set_curswant) == 152, "w_set_curswant offset mismatch");
_Static_assert(offsetof(win_T, w_cursorline) == 156, "w_cursorline offset mismatch");
_Static_assert(offsetof(win_T, w_last_cursorline) == 160, "w_last_cursorline offset mismatch");
_Static_assert(offsetof(win_T, w_old_visual_mode) == 164, "w_old_visual_mode offset mismatch");
_Static_assert(offsetof(win_T, w_old_cursor_lnum) == 168, "w_old_cursor_lnum offset mismatch");
_Static_assert(offsetof(win_T, w_old_cursor_fcol) == 172, "w_old_cursor_fcol offset mismatch");
_Static_assert(offsetof(win_T, w_old_cursor_lcol) == 176, "w_old_cursor_lcol offset mismatch");
_Static_assert(offsetof(win_T, w_old_visual_lnum) == 180, "w_old_visual_lnum offset mismatch");
_Static_assert(offsetof(win_T, w_old_visual_col) == 184, "w_old_visual_col offset mismatch");
_Static_assert(offsetof(win_T, w_old_curswant) == 188, "w_old_curswant offset mismatch");
_Static_assert(offsetof(win_T, w_last_cursor_lnum_rnu) == 192, "w_last_cursor_lnum_rnu offset mismatch");
_Static_assert(offsetof(win_T, w_p_lcs_chars) == 200, "w_p_lcs_chars offset mismatch");
_Static_assert(offsetof(win_T, w_p_fcs_chars) == 264, "w_p_fcs_chars offset mismatch");
_Static_assert(offsetof(win_T, w_topline) == 348, "w_topline offset mismatch");
_Static_assert(offsetof(win_T, w_topline_was_set) == 352, "w_topline_was_set offset mismatch");
_Static_assert(offsetof(win_T, w_topfill) == 356, "w_topfill offset mismatch");
_Static_assert(offsetof(win_T, w_old_topfill) == 360, "w_old_topfill offset mismatch");
_Static_assert(offsetof(win_T, w_botfill) == 364, "w_botfill offset mismatch");
_Static_assert(offsetof(win_T, w_old_botfill) == 365, "w_old_botfill offset mismatch");
_Static_assert(offsetof(win_T, w_leftcol) == 368, "w_leftcol offset mismatch");
_Static_assert(offsetof(win_T, w_skipcol) == 372, "w_skipcol offset mismatch");
_Static_assert(offsetof(win_T, w_last_topline) == 376, "w_last_topline offset mismatch");
_Static_assert(offsetof(win_T, w_last_topfill) == 380, "w_last_topfill offset mismatch");
_Static_assert(offsetof(win_T, w_last_leftcol) == 384, "w_last_leftcol offset mismatch");
_Static_assert(offsetof(win_T, w_last_skipcol) == 388, "w_last_skipcol offset mismatch");
_Static_assert(offsetof(win_T, w_last_width) == 392, "w_last_width offset mismatch");
_Static_assert(offsetof(win_T, w_last_height) == 396, "w_last_height offset mismatch");
_Static_assert(offsetof(win_T, w_winrow) == 400, "w_winrow offset mismatch");
_Static_assert(offsetof(win_T, w_height) == 404, "w_height offset mismatch");
_Static_assert(offsetof(win_T, w_prev_winrow) == 408, "w_prev_winrow offset mismatch");
_Static_assert(offsetof(win_T, w_prev_height) == 412, "w_prev_height offset mismatch");
_Static_assert(offsetof(win_T, w_status_height) == 416, "w_status_height offset mismatch");
_Static_assert(offsetof(win_T, w_winbar_height) == 420, "w_winbar_height offset mismatch");
_Static_assert(offsetof(win_T, w_wincol) == 424, "w_wincol offset mismatch");
_Static_assert(offsetof(win_T, w_width) == 428, "w_width offset mismatch");
_Static_assert(offsetof(win_T, w_hsep_height) == 432, "w_hsep_height offset mismatch");
_Static_assert(offsetof(win_T, w_vsep_width) == 436, "w_vsep_width offset mismatch");
_Static_assert(offsetof(win_T, w_save_cursor) == 440, "w_save_cursor offset mismatch");
_Static_assert(offsetof(win_T, w_do_win_fix_cursor) == 472, "w_do_win_fix_cursor offset mismatch");
_Static_assert(offsetof(win_T, w_winrow_off) == 476, "w_winrow_off offset mismatch");
_Static_assert(offsetof(win_T, w_wincol_off) == 480, "w_wincol_off offset mismatch");
_Static_assert(offsetof(win_T, w_view_height) == 484, "w_view_height offset mismatch");
_Static_assert(offsetof(win_T, w_view_width) == 488, "w_view_width offset mismatch");
_Static_assert(offsetof(win_T, w_height_request) == 492, "w_height_request offset mismatch");
_Static_assert(offsetof(win_T, w_width_request) == 496, "w_width_request offset mismatch");
_Static_assert(offsetof(win_T, w_border_adj) == 500, "w_border_adj offset mismatch");
_Static_assert(offsetof(win_T, w_height_outer) == 516, "w_height_outer offset mismatch");
_Static_assert(offsetof(win_T, w_width_outer) == 520, "w_width_outer offset mismatch");
_Static_assert(offsetof(win_T, w_valid) == 524, "w_valid offset mismatch");
_Static_assert(offsetof(win_T, w_valid_cursor) == 528, "w_valid_cursor offset mismatch");
_Static_assert(offsetof(win_T, w_valid_leftcol) == 540, "w_valid_leftcol offset mismatch");
_Static_assert(offsetof(win_T, w_valid_skipcol) == 544, "w_valid_skipcol offset mismatch");
_Static_assert(offsetof(win_T, w_viewport_invalid) == 548, "w_viewport_invalid offset mismatch");
_Static_assert(offsetof(win_T, w_viewport_last_topline) == 552, "w_viewport_last_topline offset mismatch");
_Static_assert(offsetof(win_T, w_viewport_last_botline) == 556, "w_viewport_last_botline offset mismatch");
_Static_assert(offsetof(win_T, w_viewport_last_topfill) == 560, "w_viewport_last_topfill offset mismatch");
_Static_assert(offsetof(win_T, w_viewport_last_skipcol) == 564, "w_viewport_last_skipcol offset mismatch");
_Static_assert(offsetof(win_T, w_cline_height) == 568, "w_cline_height offset mismatch");
_Static_assert(offsetof(win_T, w_cline_folded) == 572, "w_cline_folded offset mismatch");
_Static_assert(offsetof(win_T, w_cline_row) == 576, "w_cline_row offset mismatch");
_Static_assert(offsetof(win_T, w_virtcol) == 580, "w_virtcol offset mismatch");
_Static_assert(offsetof(win_T, w_wrow) == 584, "w_wrow offset mismatch");
_Static_assert(offsetof(win_T, w_wcol) == 588, "w_wcol offset mismatch");
_Static_assert(offsetof(win_T, w_botline) == 592, "w_botline offset mismatch");
_Static_assert(offsetof(win_T, w_empty_rows) == 596, "w_empty_rows offset mismatch");
_Static_assert(offsetof(win_T, w_filler_rows) == 600, "w_filler_rows offset mismatch");
_Static_assert(offsetof(win_T, w_lines_valid) == 604, "w_lines_valid offset mismatch");
_Static_assert(offsetof(win_T, w_lines) == 608, "w_lines offset mismatch");
_Static_assert(offsetof(win_T, w_lines_size) == 616, "w_lines_size offset mismatch");
_Static_assert(offsetof(win_T, w_folds) == 624, "w_folds offset mismatch");
_Static_assert(offsetof(win_T, w_fold_manual) == 648, "w_fold_manual offset mismatch");
_Static_assert(offsetof(win_T, w_foldinvalid) == 649, "w_foldinvalid offset mismatch");
_Static_assert(offsetof(win_T, w_nrwidth) == 652, "w_nrwidth offset mismatch");
_Static_assert(offsetof(win_T, w_scwidth) == 656, "w_scwidth offset mismatch");
_Static_assert(offsetof(win_T, w_minscwidth) == 660, "w_minscwidth offset mismatch");
_Static_assert(offsetof(win_T, w_maxscwidth) == 664, "w_maxscwidth offset mismatch");
_Static_assert(offsetof(win_T, w_redr_type) == 668, "w_redr_type offset mismatch");
_Static_assert(offsetof(win_T, w_upd_rows) == 672, "w_upd_rows offset mismatch");
_Static_assert(offsetof(win_T, w_redraw_top) == 676, "w_redraw_top offset mismatch");
_Static_assert(offsetof(win_T, w_redraw_bot) == 680, "w_redraw_bot offset mismatch");
_Static_assert(offsetof(win_T, w_redr_status) == 684, "w_redr_status offset mismatch");
_Static_assert(offsetof(win_T, w_redr_border) == 685, "w_redr_border offset mismatch");
_Static_assert(offsetof(win_T, w_redr_statuscol) == 686, "w_redr_statuscol offset mismatch");
_Static_assert(offsetof(win_T, w_stl_cursor) == 688, "w_stl_cursor offset mismatch");
_Static_assert(offsetof(win_T, w_stl_virtcol) == 700, "w_stl_virtcol offset mismatch");
_Static_assert(offsetof(win_T, w_stl_topline) == 704, "w_stl_topline offset mismatch");
_Static_assert(offsetof(win_T, w_stl_line_count) == 708, "w_stl_line_count offset mismatch");
_Static_assert(offsetof(win_T, w_stl_topfill) == 712, "w_stl_topfill offset mismatch");
_Static_assert(offsetof(win_T, w_stl_empty) == 716, "w_stl_empty offset mismatch");
_Static_assert(offsetof(win_T, w_stl_recording) == 720, "w_stl_recording offset mismatch");
_Static_assert(offsetof(win_T, w_stl_state) == 724, "w_stl_state offset mismatch");
_Static_assert(offsetof(win_T, w_stl_visual_mode) == 728, "w_stl_visual_mode offset mismatch");
_Static_assert(offsetof(win_T, w_stl_visual_pos) == 732, "w_stl_visual_pos offset mismatch");
_Static_assert(offsetof(win_T, w_alt_fnum) == 744, "w_alt_fnum offset mismatch");
_Static_assert(offsetof(win_T, w_alist) == 752, "w_alist offset mismatch");
_Static_assert(offsetof(win_T, w_arg_idx) == 760, "w_arg_idx offset mismatch");
_Static_assert(offsetof(win_T, w_arg_idx_invalid) == 764, "w_arg_idx_invalid offset mismatch");
_Static_assert(offsetof(win_T, w_localdir) == 768, "w_localdir offset mismatch");
_Static_assert(offsetof(win_T, w_prevdir) == 776, "w_prevdir offset mismatch");
_Static_assert(offsetof(win_T, w_onebuf_opt) == 784, "w_onebuf_opt offset mismatch");
_Static_assert(offsetof(win_T, w_allbuf_opt) == 2424, "w_allbuf_opt offset mismatch");
_Static_assert(offsetof(win_T, w_p_cc_cols) == 4064, "w_p_cc_cols offset mismatch");
_Static_assert(offsetof(win_T, w_p_culopt_flags) == 4072, "w_p_culopt_flags offset mismatch");
_Static_assert(offsetof(win_T, w_briopt_min) == 4076, "w_briopt_min offset mismatch");
_Static_assert(offsetof(win_T, w_briopt_shift) == 4080, "w_briopt_shift offset mismatch");
_Static_assert(offsetof(win_T, w_briopt_sbr) == 4084, "w_briopt_sbr offset mismatch");
_Static_assert(offsetof(win_T, w_scbind_pos) == 4096, "w_scbind_pos offset mismatch");
_Static_assert(offsetof(win_T, w_winvar) == 4104, "w_winvar offset mismatch");
_Static_assert(offsetof(win_T, w_vars) == 4128, "w_vars offset mismatch");
_Static_assert(offsetof(win_T, w_pcmark) == 4136, "w_pcmark offset mismatch");
_Static_assert(offsetof(win_T, w_prev_pcmark) == 4148, "w_prev_pcmark offset mismatch");
_Static_assert(offsetof(win_T, w_jumplist) == 4160, "w_jumplist offset mismatch");
_Static_assert(offsetof(win_T, w_jumplistlen) == 8960, "w_jumplistlen offset mismatch");
_Static_assert(offsetof(win_T, w_changelistidx) == 8968, "w_changelistidx offset mismatch");
_Static_assert(offsetof(win_T, w_match_head) == 8976, "w_match_head offset mismatch");
_Static_assert(offsetof(win_T, w_next_match_id) == 8984, "w_next_match_id offset mismatch");
_Static_assert(offsetof(win_T, w_tagstack) == 8992, "w_tagstack offset mismatch");
_Static_assert(offsetof(win_T, w_tagstackidx) == 10272, "w_tagstackidx offset mismatch");
_Static_assert(offsetof(win_T, w_tagstacklen) == 10276, "w_tagstacklen offset mismatch");
_Static_assert(offsetof(win_T, w_grid) == 10280, "w_grid offset mismatch");
_Static_assert(offsetof(win_T, w_grid_alloc) == 10296, "w_grid_alloc offset mismatch");
_Static_assert(offsetof(win_T, w_pos_changed) == 10392, "w_pos_changed offset mismatch");
_Static_assert(offsetof(win_T, w_floating) == 10393, "w_floating offset mismatch");
_Static_assert(offsetof(win_T, w_float_is_info) == 10394, "w_float_is_info offset mismatch");
_Static_assert(offsetof(win_T, w_config) == 10400, "w_config offset mismatch");
_Static_assert(offsetof(win_T, w_fraction) == 10880, "w_fraction offset mismatch");
_Static_assert(offsetof(win_T, w_prev_fraction_row) == 10884, "w_prev_fraction_row offset mismatch");
_Static_assert(offsetof(win_T, w_nrwidth_line_count) == 10888, "w_nrwidth_line_count offset mismatch");
_Static_assert(offsetof(win_T, w_statuscol_line_count) == 10892, "w_statuscol_line_count offset mismatch");
_Static_assert(offsetof(win_T, w_nrwidth_width) == 10896, "w_nrwidth_width offset mismatch");
_Static_assert(offsetof(win_T, w_llist) == 10904, "w_llist offset mismatch");
_Static_assert(offsetof(win_T, w_llist_ref) == 10912, "w_llist_ref offset mismatch");
_Static_assert(offsetof(win_T, w_status_click_defs) == 10920, "w_status_click_defs offset mismatch");
_Static_assert(offsetof(win_T, w_winbar_click_defs) == 10936, "w_winbar_click_defs offset mismatch");
_Static_assert(offsetof(win_T, w_statuscol_click_defs) == 10952, "w_statuscol_click_defs offset mismatch");

// Winopt field offsets for fields accessed via pointer arithmetic in Rust
_Static_assert(offsetof(win_T, w_p_arab) == 784, "w_p_arab offset mismatch");
_Static_assert(offsetof(win_T, w_p_bri) == 788, "w_p_bri offset mismatch");
_Static_assert(offsetof(win_T, w_p_diff) == 800, "w_p_diff offset mismatch");
_Static_assert(offsetof(win_T, w_p_fen) == 832, "w_p_fen offset mismatch");
_Static_assert(offsetof(win_T, w_p_nu) == 928, "w_p_nu offset mismatch");
_Static_assert(offsetof(win_T, w_p_rnu) == 932, "w_p_rnu offset mismatch");
_Static_assert(offsetof(win_T, w_p_list) == 924, "w_p_list offset mismatch");
_Static_assert(offsetof(win_T, w_p_sms) == 1008, "w_p_sms offset mismatch");
_Static_assert(offsetof(win_T, w_p_spell) == 1012, "w_p_spell offset mismatch");
_Static_assert(offsetof(win_T, w_p_cuc) == 1016, "w_p_cuc offset mismatch");
_Static_assert(offsetof(win_T, w_p_cul) == 1020, "w_p_cul offset mismatch");
_Static_assert(offsetof(win_T, w_p_wfb) == 960, "w_p_wfb offset mismatch");
_Static_assert(offsetof(win_T, w_p_wfh) == 964, "w_p_wfh offset mismatch");
_Static_assert(offsetof(win_T, w_p_wfw) == 968, "w_p_wfw offset mismatch");
_Static_assert(offsetof(win_T, w_p_pvw) == 972, "w_p_pvw offset mismatch");
_Static_assert(offsetof(win_T, w_p_rl) == 984, "w_p_rl offset mismatch");
_Static_assert(offsetof(win_T, w_p_scb) == 1072, "w_p_scb offset mismatch");
_Static_assert(offsetof(win_T, w_p_wrap) == 1084, "w_p_wrap offset mismatch");
_Static_assert(offsetof(win_T, w_p_crb) == 1112, "w_p_crb offset mismatch");
_Static_assert(offsetof(win_T, w_p_siso) == 1128, "w_p_siso offset mismatch");
_Static_assert(offsetof(win_T, w_p_so) == 1136, "w_p_so offset mismatch");
_Static_assert(offsetof(win_T, w_p_cole) == 1104, "w_p_cole offset mismatch");
_Static_assert(offsetof(win_T, w_p_nuw) == 952, "w_p_nuw offset mismatch");
_Static_assert(offsetof(win_T, w_p_winbl) == 1168, "w_p_winbl offset mismatch");
_Static_assert(offsetof(win_T, w_p_wrap_flags) == 1176, "w_p_wrap_flags offset mismatch");
_Static_assert(offsetof(win_T, w_p_lbr) == 920, "w_p_lbr offset mismatch");
_Static_assert(offsetof(win_T, w_ve_flags) == 944, "w_ve_flags offset mismatch");
_Static_assert(offsetof(win_T, w_p_fdt) == 904, "w_p_fdt offset mismatch");
// String option pointer fields (in w_onebuf_opt)
_Static_assert(offsetof(win_T, w_p_fdc) == 808, "w_p_fdc offset mismatch");
_Static_assert(offsetof(win_T, w_p_eiw) == 816, "w_p_eiw offset mismatch");
_Static_assert(offsetof(win_T, w_p_cc) == 1032, "w_p_cc offset mismatch");
_Static_assert(offsetof(win_T, w_p_sbr) == 1040, "w_p_sbr offset mismatch");
_Static_assert(offsetof(win_T, w_p_stc) == 1048, "w_p_stc offset mismatch");
_Static_assert(offsetof(win_T, w_p_stl) == 1056, "w_p_stl offset mismatch");
_Static_assert(offsetof(win_T, w_p_wbr) == 1064, "w_p_wbr offset mismatch");
_Static_assert(offsetof(win_T, w_p_cocu) == 1096, "w_p_cocu offset mismatch");
_Static_assert(offsetof(win_T, w_p_scl) == 1120, "w_p_scl offset mismatch");
_Static_assert(offsetof(win_T, w_p_winhl) == 1144, "w_p_winhl offset mismatch");
_Static_assert(offsetof(win_T, w_p_lcs) == 1152, "w_p_lcs offset mismatch");
_Static_assert(offsetof(win_T, w_p_fcs) == 1160, "w_p_fcs offset mismatch");

// Struct type sizes
_Static_assert(sizeof(pos_save_T) == 32, "pos_save_T size mismatch");
_Static_assert(sizeof(lcs_chars_T) == 64, "lcs_chars_T size mismatch");
_Static_assert(sizeof(fcs_chars_T) == 84, "fcs_chars_T size mismatch");
_Static_assert(sizeof(Set(uint32_t)) == 40, "Set_uint32_t size mismatch");
_Static_assert(sizeof(winopt_T) == 1640, "winopt_T size mismatch");
_Static_assert(sizeof(WinConfig) == 480, "WinConfig size mismatch");
_Static_assert(sizeof(ScreenGrid) == 96, "ScreenGrid size mismatch");
_Static_assert(sizeof(GridView) == 16, "GridView size mismatch");

// tabpage_T layout assertions (for TabpageStruct in tabpage_struct.rs)
_Static_assert(sizeof(tabpage_T) == 224, "tabpage_T size mismatch: update TabpageStruct in tabpage_struct.rs");
_Static_assert(offsetof(tabpage_T, handle) == 0, "tabpage handle offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_next) == 8, "tabpage tp_next offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_topframe) == 16, "tabpage tp_topframe offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_curwin) == 24, "tabpage tp_curwin offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_prevwin) == 32, "tabpage tp_prevwin offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_firstwin) == 40, "tabpage tp_firstwin offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_lastwin) == 48, "tabpage tp_lastwin offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_old_Rows_avail) == 56, "tabpage tp_old_Rows_avail offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_old_Columns) == 64, "tabpage tp_old_Columns offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_ch_used) == 72, "tabpage tp_ch_used offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_first_diff) == 80, "tabpage tp_first_diff offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_diffbuf) == 88, "tabpage tp_diffbuf offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_diff_invalid) == 152, "tabpage tp_diff_invalid offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_diff_update) == 156, "tabpage tp_diff_update offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_snapshot) == 160, "tabpage tp_snapshot offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_winvar) == 176, "tabpage tp_winvar offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_vars) == 200, "tabpage tp_vars offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_localdir) == 208, "tabpage tp_localdir offset mismatch");
_Static_assert(offsetof(tabpage_T, tp_prevdir) == 216, "tabpage tp_prevdir offset mismatch");
