#!/usr/bin/env python3
"""Regenerate crates/nvim/src/keycodes.lua from the Rust key-name table.

Upstream kept the `<>` key names in `src/nvim/keycodes.lua` and turned them
into a C array plus a perfect-hash dispatch at build time (`v0.12.4`'s
`src/gen/gen_keycodes.lua`). The port inverted that: the table is
`KEY_NAME_ROWS` in crates/nvim/src/keycodes/tables.rs, sorted by
lower-cased name and binary searched, so the editor needs no generated Lua at
all and the Lua file was deleted with the rest of the C tree.

`test/benchmark/keycodes_spec.lua` still wants it — it feeds every name
through nvim_replace_termcodes — and a benchmark is exactly the consumer that
must not carry its own copy of a 187-row table: a stale copy would benchmark
names the editor no longer knows and silently skip ones it gained. So the
data flows the other way now, Rust to Lua, and this script is the arrow.

The two tables were verified row-for-row identical to upstream's before this
script was written, so the output is a faithful stand-in for the deleted file
in everything but row order: upstream grouped its rows by hand ("preferred
name first"), while KEY_NAME_ROWS is sorted by lower-cased name because a
binary search needs it to be. Consumers that care about which spelling is
preferred want the `is_alt` column, which upstream expressed only as
position and which this file therefore cannot carry.

Column 1 is upstream's C spelling in every row, recovered from the Rust
expression: a bare macro name (`K_BS`), a C character literal with its quotes
(`' '`), `extra(KE_FOO)` for `K_FOO`, or a `Key` variant, whose name is the C
one with each underscore-separated word capitalised (`K_S_F1` is `Key::SF1`)
and so inverts by splitting on the capitals again.

Usage: gen-keycodes-lua.py [--check]
  --check   regenerate and diff against the committed file; exit 1 on drift
            instead of writing.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLES = ROOT / "crates/nvim/src/keycodes/tables.rs"
OUT = ROOT / "crates/nvim/src/keycodes.lua"

# The `const KEY_NAME_ROWS: [KeyName; N] = [ ... ];` literal, and one
# `key_name(<key>, <is_alt>, "<name>"),` row inside it. The key expression is
# matched lazily up to the `, true,` / `, false,` that follows it, so the
# parenthesised `extra(KE_FOO)` form needs no bracket counting.
ROWS = re.compile(r"^const KEY_NAME_ROWS[^=]*= \[$(.*?)^\];$", re.M | re.S)
ROW = re.compile(
    r'^\s*key_name\((?P<key>.*?), (?:true|false), "(?P<name>[^"]*)"\),$', re.M
)

HEADER = """\
-- Generated by scripts/gen-keycodes-lua.py from the key-name table in
-- crates/nvim/src/keycodes/tables.rs, which is the source of truth.
-- Do not edit: run `just keycodes-lua` (or `just refresh`) instead.
--
-- Rows are in the Rust table's order, sorted by lower-cased name, which is
-- not the hand-grouped order the deleted upstream keycodes.lua used.
"""


def key_to_lua(key: str) -> str:
    """The Lua spelling of a `key_name` first argument."""
    key = key.removesuffix(" as c_int").removesuffix(".code()")
    if key.startswith("extra(KE_") and key.endswith(")"):
        return "K_" + key[len("extra(KE_") : -1]
    if key.startswith("Key::"):
        return "K_" + "_".join(w.upper() for w in re.findall(r"[A-Z][^A-Z]*", key[5:]))
    return key


def build() -> tuple[str, int]:
    source = TABLES.read_text()
    table = ROWS.search(source)
    if table is None:
        sys.exit(
            f"gen-keycodes-lua: no KEY_NAME_ROWS literal in {TABLES.relative_to(ROOT)}"
        )
    rows = ROW.findall(table.group(1))
    # Every line of the literal is a row, blanks and comments aside; anything
    # else means the table grew a shape this script does not understand, and a
    # silent partial table would be worse than a failure.
    lines = [
        ln
        for ln in table.group(1).splitlines()
        if ln.strip() and not ln.lstrip().startswith("//")
    ]
    if len(rows) != len(lines):
        sys.exit(
            f"gen-keycodes-lua: parsed {len(rows)} of {len(lines)} KEY_NAME_ROWS lines; "
            "the row shape changed"
        )
    out = [
        HEADER,
        "return {",
        "  --- @type [string, string][] List of [key, name] tuples.",
        "  names = {",
    ]
    for key, name in rows:
        out.append(f"    {{ [[{key_to_lua(key)}]], '{name}' }},")
    out += ["  },", "}", ""]
    return "\n".join(out), len(rows)


def main():
    content, count = build()
    if "--check" in sys.argv[1:]:
        committed = OUT.read_text() if OUT.exists() else ""
        if committed != content:
            sys.exit(
                f"gen-keycodes-lua: {OUT.relative_to(ROOT)} is stale; "
                "run `just refresh` and commit the result"
            )
        return
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)}: {count} names")


if __name__ == "__main__":
    main()
