//! Compiled-in highlight group default definitions.
//!
//! These tables mirror the `highlight_init_both`, `highlight_init_light`, and
//! `highlight_init_dark` static arrays from `highlight_group.c`. They are used
//! by `init_highlight` to set up the default highlight groups at startup and
//! whenever the background option changes.

use std::ffi::c_char;

/// Newtype wrapper to make an array of raw pointers safe to use as a `static`.
///
/// Neovim's C-side uses these tables read-only (iteration only). The pointers
/// point to static string literals embedded in the binary, so there is no
/// aliasing or mutation concern.
pub struct CStrTable<const N: usize>(pub [*const c_char; N]);

// SAFETY: The arrays hold pointers to `'static` C string literals. They are
// never mutated after initialization and are safe to share across threads.
unsafe impl<const N: usize> Sync for CStrTable<N> {}

/// Highlight group defaults that apply to both light and dark backgrounds.
///
/// Null-pointer-terminated array of C strings. C code iterates until NULL.
#[no_mangle]
pub static highlight_init_both: CStrTable<173> = CStrTable([
    c"Cursor            guifg=bg      guibg=fg".as_ptr(),
    c"CursorLineNr      gui=bold      cterm=bold".as_ptr(),
    c"PmenuMatch        gui=bold      cterm=bold".as_ptr(),
    c"PmenuMatchSel     gui=bold      cterm=bold".as_ptr(),
    c"PmenuSel          gui=reverse   cterm=reverse,underline blend=0".as_ptr(),
    c"RedrawDebugNormal gui=reverse   cterm=reverse".as_ptr(),
    c"TabLineSel        gui=bold      cterm=NONE".as_ptr(),
    c"TermCursor        gui=reverse   cterm=reverse".as_ptr(),
    c"Underlined        gui=underline cterm=underline".as_ptr(),
    c"lCursor           guifg=bg      guibg=fg".as_ptr(),
    // UI
    c"default link CursorIM         Cursor".as_ptr(),
    c"default link CursorLineFold   FoldColumn".as_ptr(),
    c"default link CursorLineSign   SignColumn".as_ptr(),
    c"default link DiffTextAdd      DiffText".as_ptr(),
    c"default link EndOfBuffer      NonText".as_ptr(),
    c"default link FloatBorder      NormalFloat".as_ptr(),
    c"default link FloatFooter      FloatTitle".as_ptr(),
    c"default link FloatTitle       Title".as_ptr(),
    c"default link FoldColumn       SignColumn".as_ptr(),
    c"default link IncSearch        CurSearch".as_ptr(),
    c"default link LineNrAbove      LineNr".as_ptr(),
    c"default link LineNrBelow      LineNr".as_ptr(),
    c"default link MsgSeparator     StatusLine".as_ptr(),
    c"default link MsgArea          NONE".as_ptr(),
    c"default link NormalNC         NONE".as_ptr(),
    c"default link PmenuExtra       Pmenu".as_ptr(),
    c"default link PmenuExtraSel    PmenuSel".as_ptr(),
    c"default link PmenuKind        Pmenu".as_ptr(),
    c"default link PmenuKindSel     PmenuSel".as_ptr(),
    c"default link PmenuSbar        Pmenu".as_ptr(),
    c"default link PmenuBorder        Pmenu".as_ptr(),
    c"default link PmenuShadowThrough FloatShadowThrough".as_ptr(),
    c"default link PreInsert        Added".as_ptr(),
    c"default link ComplMatchIns    NONE".as_ptr(),
    c"default link ComplHint        NonText".as_ptr(),
    c"default link ComplHintMore    MoreMsg".as_ptr(),
    c"default link Substitute       Search".as_ptr(),
    c"default link StatusLineTerm   StatusLine".as_ptr(),
    c"default link StatusLineTermNC StatusLineNC".as_ptr(),
    c"default link StderrMsg        ErrorMsg".as_ptr(),
    c"default link StdoutMsg        NONE".as_ptr(),
    c"default link TabLine          StatusLineNC".as_ptr(),
    c"default link TabLineFill      TabLine".as_ptr(),
    c"default link VertSplit        WinSeparator".as_ptr(),
    c"default link VisualNOS        Visual".as_ptr(),
    c"default link Whitespace       NonText".as_ptr(),
    c"default link WildMenu         PmenuSel".as_ptr(),
    c"default link WinSeparator     Normal".as_ptr(),
    // Syntax
    c"default link Character      Constant".as_ptr(),
    c"default link Number         Constant".as_ptr(),
    c"default link Boolean        Constant".as_ptr(),
    c"default link Float          Number".as_ptr(),
    c"default link Conditional    Statement".as_ptr(),
    c"default link Repeat         Statement".as_ptr(),
    c"default link Label          Statement".as_ptr(),
    c"default link Keyword        Statement".as_ptr(),
    c"default link Exception      Statement".as_ptr(),
    c"default link Include        PreProc".as_ptr(),
    c"default link Define         PreProc".as_ptr(),
    c"default link Macro          PreProc".as_ptr(),
    c"default link PreCondit      PreProc".as_ptr(),
    c"default link StorageClass   Type".as_ptr(),
    c"default link Structure      Type".as_ptr(),
    c"default link Typedef        Type".as_ptr(),
    c"default link Tag            Special".as_ptr(),
    c"default link SpecialChar    Special".as_ptr(),
    c"default link SpecialComment Special".as_ptr(),
    c"default link Debug          Special".as_ptr(),
    c"default link Ignore         Normal".as_ptr(),
    // Built-in LSP
    c"default link LspCodeLens                 NonText".as_ptr(),
    c"default link LspCodeLensSeparator        LspCodeLens".as_ptr(),
    c"default link LspInlayHint                NonText".as_ptr(),
    c"default link LspReferenceRead            LspReferenceText".as_ptr(),
    c"default link LspReferenceText            Visual".as_ptr(),
    c"default link LspReferenceWrite           LspReferenceText".as_ptr(),
    c"default link LspReferenceTarget          LspReferenceText".as_ptr(),
    c"default link LspSignatureActiveParameter Visual".as_ptr(),
    c"default link SnippetTabstop              Visual".as_ptr(),
    c"default link SnippetTabstopActive        SnippetTabstop".as_ptr(),
    // Diagnostic
    c"default link DiagnosticFloatingError    DiagnosticError".as_ptr(),
    c"default link DiagnosticFloatingWarn     DiagnosticWarn".as_ptr(),
    c"default link DiagnosticFloatingInfo     DiagnosticInfo".as_ptr(),
    c"default link DiagnosticFloatingHint     DiagnosticHint".as_ptr(),
    c"default link DiagnosticFloatingOk       DiagnosticOk".as_ptr(),
    c"default link DiagnosticVirtualTextError DiagnosticError".as_ptr(),
    c"default link DiagnosticVirtualTextWarn  DiagnosticWarn".as_ptr(),
    c"default link DiagnosticVirtualTextInfo  DiagnosticInfo".as_ptr(),
    c"default link DiagnosticVirtualTextHint  DiagnosticHint".as_ptr(),
    c"default link DiagnosticVirtualTextOk    DiagnosticOk".as_ptr(),
    c"default link DiagnosticVirtualLinesError DiagnosticError".as_ptr(),
    c"default link DiagnosticVirtualLinesWarn  DiagnosticWarn".as_ptr(),
    c"default link DiagnosticVirtualLinesInfo  DiagnosticInfo".as_ptr(),
    c"default link DiagnosticVirtualLinesHint  DiagnosticHint".as_ptr(),
    c"default link DiagnosticVirtualLinesOk    DiagnosticOk".as_ptr(),
    c"default link DiagnosticSignError        DiagnosticError".as_ptr(),
    c"default link DiagnosticSignWarn         DiagnosticWarn".as_ptr(),
    c"default link DiagnosticSignInfo         DiagnosticInfo".as_ptr(),
    c"default link DiagnosticSignHint         DiagnosticHint".as_ptr(),
    c"default link DiagnosticSignOk           DiagnosticOk".as_ptr(),
    c"default link DiagnosticUnnecessary      Comment".as_ptr(),
    // Treesitter standard groups
    c"default link @variable.builtin           Special".as_ptr(),
    c"default link @variable.parameter.builtin Special".as_ptr(),
    c"default link @constant         Constant".as_ptr(),
    c"default link @constant.builtin Special".as_ptr(),
    c"default link @module         Structure".as_ptr(),
    c"default link @module.builtin Special".as_ptr(),
    c"default link @label          Label".as_ptr(),
    c"default link @string             String".as_ptr(),
    c"default link @string.regexp      @string.special".as_ptr(),
    c"default link @string.escape      @string.special".as_ptr(),
    c"default link @string.special     SpecialChar".as_ptr(),
    c"default link @string.special.url Underlined".as_ptr(),
    c"default link @character         Character".as_ptr(),
    c"default link @character.special SpecialChar".as_ptr(),
    c"default link @boolean      Boolean".as_ptr(),
    c"default link @number       Number".as_ptr(),
    c"default link @number.float Float".as_ptr(),
    c"default link @type         Type".as_ptr(),
    c"default link @type.builtin Special".as_ptr(),
    c"default link @attribute         Macro".as_ptr(),
    c"default link @attribute.builtin Special".as_ptr(),
    c"default link @property          Identifier".as_ptr(),
    c"default link @function         Function".as_ptr(),
    c"default link @function.builtin Special".as_ptr(),
    c"default link @constructor Special".as_ptr(),
    c"default link @operator    Operator".as_ptr(),
    c"default link @keyword Keyword".as_ptr(),
    c"default link @punctuation         Delimiter".as_ptr(),
    c"default link @punctuation.special Special".as_ptr(),
    c"default link @comment Comment".as_ptr(),
    c"default link @comment.error   DiagnosticError".as_ptr(),
    c"default link @comment.warning DiagnosticWarn".as_ptr(),
    c"default link @comment.note    DiagnosticInfo".as_ptr(),
    c"default link @comment.todo    Todo".as_ptr(),
    c"@markup.strong        gui=bold          cterm=bold".as_ptr(),
    c"@markup.italic        gui=italic        cterm=italic".as_ptr(),
    c"@markup.strikethrough gui=strikethrough cterm=strikethrough".as_ptr(),
    c"@markup.underline     gui=underline     cterm=underline".as_ptr(),
    c"default link @markup         Special".as_ptr(),
    c"default link @markup.heading Title".as_ptr(),
    c"default link @markup.link    Underlined".as_ptr(),
    c"default link @diff.plus  Added".as_ptr(),
    c"default link @diff.minus Removed".as_ptr(),
    c"default link @diff.delta Changed".as_ptr(),
    c"default link @tag         Tag".as_ptr(),
    c"default link @tag.builtin Special".as_ptr(),
    // :help
    c"default @markup.heading.1.delimiter.vimdoc guibg=bg guifg=bg guisp=fg gui=underdouble,nocombine ctermbg=NONE ctermfg=NONE cterm=underdouble,nocombine".as_ptr(),
    c"default @markup.heading.2.delimiter.vimdoc guibg=bg guifg=bg guisp=fg gui=underline,nocombine ctermbg=NONE ctermfg=NONE cterm=underline,nocombine".as_ptr(),
    // LSP semantic tokens
    c"default link @lsp.type.class         @type".as_ptr(),
    c"default link @lsp.type.comment       @comment".as_ptr(),
    c"default link @lsp.type.decorator     @attribute".as_ptr(),
    c"default link @lsp.type.enum          @type".as_ptr(),
    c"default link @lsp.type.enumMember    @constant".as_ptr(),
    c"default link @lsp.type.event         @type".as_ptr(),
    c"default link @lsp.type.function      @function".as_ptr(),
    c"default link @lsp.type.interface     @type".as_ptr(),
    c"default link @lsp.type.keyword       @keyword".as_ptr(),
    c"default link @lsp.type.macro         @constant.macro".as_ptr(),
    c"default link @lsp.type.method        @function.method".as_ptr(),
    c"default link @lsp.type.modifier      @type.qualifier".as_ptr(),
    c"default link @lsp.type.namespace     @module".as_ptr(),
    c"default link @lsp.type.number        @number".as_ptr(),
    c"default link @lsp.type.operator      @operator".as_ptr(),
    c"default link @lsp.type.parameter     @variable.parameter".as_ptr(),
    c"default link @lsp.type.property      @property".as_ptr(),
    c"default link @lsp.type.regexp        @string.regexp".as_ptr(),
    c"default link @lsp.type.string        @string".as_ptr(),
    c"default link @lsp.type.struct        @type".as_ptr(),
    c"default link @lsp.type.type          @type".as_ptr(),
    c"default link @lsp.type.typeParameter @type.definition".as_ptr(),
    c"default link @lsp.type.variable      @variable".as_ptr(),
    c"default link @lsp.mod.deprecated DiagnosticDeprecated".as_ptr(),
    std::ptr::null(),
]);

/// Highlight group defaults for light backgrounds.
///
/// Null-pointer-terminated array of C strings.
#[no_mangle]
pub static highlight_init_light: CStrTable<73> = CStrTable([
    c"Normal guifg=NvimDarkGrey2 guibg=NvimLightGrey2 ctermfg=NONE ctermbg=NONE".as_ptr(),
    // UI
    c"Added                guifg=NvimDarkGreen                                  ctermfg=2".as_ptr(),
    c"Changed              guifg=NvimDarkCyan                                   ctermfg=6".as_ptr(),
    c"ColorColumn                               guibg=NvimLightGrey4            cterm=reverse".as_ptr(),
    c"Conceal              guifg=NvimLightGrey4".as_ptr(),
    c"CurSearch            guifg=NvimLightGrey1 guibg=NvimDarkYellow            ctermfg=15 ctermbg=3".as_ptr(),
    c"CursorColumn                              guibg=NvimLightGrey3".as_ptr(),
    c"CursorLine                                guibg=NvimLightGrey3".as_ptr(),
    c"DiffAdd              guifg=NvimDarkGrey1  guibg=NvimLightGreen            ctermfg=15 ctermbg=2".as_ptr(),
    c"DiffChange           guifg=NvimDarkGrey1  guibg=NvimLightGrey4".as_ptr(),
    c"DiffDelete           guifg=NvimDarkRed                          gui=bold  ctermfg=1 cterm=bold".as_ptr(),
    c"DiffText             guifg=NvimDarkGrey1  guibg=NvimLightCyan             ctermfg=15 ctermbg=6".as_ptr(),
    c"Directory            guifg=NvimDarkCyan                                   ctermfg=6".as_ptr(),
    c"ErrorMsg             guifg=NvimDarkRed                                    ctermfg=1".as_ptr(),
    c"FloatShadow                               guibg=NvimLightGrey4            ctermbg=0 blend=80".as_ptr(),
    c"FloatShadowThrough                        guibg=NvimLightGrey4            ctermbg=0 blend=100".as_ptr(),
    c"Folded               guifg=NvimDarkGrey4  guibg=NvimLightGrey1".as_ptr(),
    c"LineNr               guifg=NvimLightGrey4".as_ptr(),
    c"MatchParen                                guibg=NvimLightGrey4  gui=bold  cterm=bold,underline".as_ptr(),
    c"ModeMsg              guifg=NvimDarkGreen                                  ctermfg=2".as_ptr(),
    c"MoreMsg              guifg=NvimDarkCyan                                   ctermfg=6".as_ptr(),
    c"NonText              guifg=NvimLightGrey4".as_ptr(),
    c"NormalFloat                               guibg=NvimLightGrey1".as_ptr(),
    c"OkMsg                guifg=NvimDarkGreen                                  ctermfg=2".as_ptr(),
    c"Pmenu                                     guibg=NvimLightGrey3            cterm=reverse".as_ptr(),
    c"PmenuThumb                                guibg=NvimLightGrey4".as_ptr(),
    c"PmenuShadow                               guibg=NvimLightGrey4            ctermbg=0 blend=100".as_ptr(),
    c"Question             guifg=NvimDarkCyan                                   ctermfg=6".as_ptr(),
    c"QuickFixLine         guifg=NvimDarkCyan                                   ctermfg=6".as_ptr(),
    c"RedrawDebugClear                          guibg=NvimLightYellow           ctermfg=15 ctermbg=3".as_ptr(),
    c"RedrawDebugComposed                       guibg=NvimLightGreen            ctermfg=15 ctermbg=2".as_ptr(),
    c"RedrawDebugRecompose                      guibg=NvimLightRed              ctermfg=15 ctermbg=1".as_ptr(),
    c"Removed              guifg=NvimDarkRed                                    ctermfg=1".as_ptr(),
    c"Search               guifg=NvimDarkGrey1  guibg=NvimLightYellow           ctermfg=15 ctermbg=3".as_ptr(),
    c"SignColumn           guifg=NvimLightGrey4".as_ptr(),
    c"SpecialKey           guifg=NvimLightGrey4".as_ptr(),
    c"SpellBad             guisp=NvimDarkRed    gui=undercurl                   cterm=undercurl".as_ptr(),
    c"SpellCap             guisp=NvimDarkYellow gui=undercurl                   cterm=undercurl".as_ptr(),
    c"SpellLocal           guisp=NvimDarkGreen  gui=undercurl                   cterm=undercurl".as_ptr(),
    c"SpellRare            guisp=NvimDarkCyan   gui=undercurl                   cterm=undercurl".as_ptr(),
    c"StatusLine           guifg=NvimDarkGrey2  guibg=NvimLightGrey4            cterm=reverse".as_ptr(),
    c"StatusLineNC         guifg=NvimDarkGrey3  guibg=NvimLightGrey3            cterm=bold,underline".as_ptr(),
    c"Title                guifg=NvimDarkGrey2                        gui=bold  cterm=bold".as_ptr(),
    c"Visual                                    guibg=NvimLightGrey4            ctermfg=15 ctermbg=0".as_ptr(),
    c"WarningMsg           guifg=NvimDarkYellow                                 ctermfg=3".as_ptr(),
    c"WinBar               guifg=NvimDarkGrey4  guibg=NvimLightGrey1  gui=bold  cterm=bold".as_ptr(),
    c"WinBarNC             guifg=NvimDarkGrey4  guibg=NvimLightGrey1            cterm=bold".as_ptr(),
    // Syntax
    c"Constant   guifg=NvimDarkGrey2".as_ptr(),
    c"Operator   guifg=NvimDarkGrey2".as_ptr(),
    c"PreProc    guifg=NvimDarkGrey2".as_ptr(),
    c"Type       guifg=NvimDarkGrey2".as_ptr(),
    c"Delimiter  guifg=NvimDarkGrey2".as_ptr(),
    c"Comment    guifg=NvimDarkGrey4".as_ptr(),
    c"String     guifg=NvimDarkGreen                    ctermfg=2".as_ptr(),
    c"Identifier guifg=NvimDarkBlue                     ctermfg=4".as_ptr(),
    c"Function   guifg=NvimDarkCyan                     ctermfg=6".as_ptr(),
    c"Statement  guifg=NvimDarkGrey2 gui=bold           cterm=bold".as_ptr(),
    c"Special    guifg=NvimDarkCyan                     ctermfg=6".as_ptr(),
    c"Error      guifg=NvimDarkGrey1 guibg=NvimLightRed ctermfg=15 ctermbg=1".as_ptr(),
    c"Todo       guifg=NvimDarkGrey2 gui=bold           cterm=bold".as_ptr(),
    // Diagnostic
    c"DiagnosticError          guifg=NvimDarkRed                      ctermfg=1".as_ptr(),
    c"DiagnosticWarn           guifg=NvimDarkYellow                   ctermfg=3".as_ptr(),
    c"DiagnosticInfo           guifg=NvimDarkCyan                     ctermfg=6".as_ptr(),
    c"DiagnosticHint           guifg=NvimDarkBlue                     ctermfg=4".as_ptr(),
    c"DiagnosticOk             guifg=NvimDarkGreen                    ctermfg=2".as_ptr(),
    c"DiagnosticUnderlineError guisp=NvimDarkRed    gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineWarn  guisp=NvimDarkYellow gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineInfo  guisp=NvimDarkCyan   gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineHint  guisp=NvimDarkBlue   gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineOk    guisp=NvimDarkGreen  gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticDeprecated     guisp=NvimDarkRed    gui=strikethrough cterm=strikethrough".as_ptr(),
    // Treesitter standard groups
    c"@variable guifg=NvimDarkGrey2".as_ptr(),
    std::ptr::null(),
]);

/// Highlight group defaults for dark backgrounds.
///
/// Null-pointer-terminated array of C strings.
#[no_mangle]
pub static highlight_init_dark: CStrTable<73> = CStrTable([
    c"Normal guifg=NvimLightGrey2 guibg=NvimDarkGrey2 ctermfg=NONE ctermbg=NONE".as_ptr(),
    // UI
    c"Added                guifg=NvimLightGreen                                ctermfg=10".as_ptr(),
    c"Changed              guifg=NvimLightCyan                                 ctermfg=14".as_ptr(),
    c"ColorColumn                                guibg=NvimDarkGrey4           cterm=reverse".as_ptr(),
    c"Conceal              guifg=NvimDarkGrey4".as_ptr(),
    c"CurSearch            guifg=NvimDarkGrey1   guibg=NvimLightYellow         ctermfg=0 ctermbg=11".as_ptr(),
    c"CursorColumn                               guibg=NvimDarkGrey3".as_ptr(),
    c"CursorLine                                 guibg=NvimDarkGrey3".as_ptr(),
    c"DiffAdd              guifg=NvimLightGrey1  guibg=NvimDarkGreen           ctermfg=0 ctermbg=10".as_ptr(),
    c"DiffChange           guifg=NvimLightGrey1  guibg=NvimDarkGrey4".as_ptr(),
    c"DiffDelete           guifg=NvimLightRed                         gui=bold ctermfg=9 cterm=bold".as_ptr(),
    c"DiffText             guifg=NvimLightGrey1  guibg=NvimDarkCyan            ctermfg=0 ctermbg=14".as_ptr(),
    c"Directory            guifg=NvimLightCyan                                 ctermfg=14".as_ptr(),
    c"ErrorMsg             guifg=NvimLightRed                                  ctermfg=9".as_ptr(),
    c"FloatShadow                                guibg=NvimDarkGrey4           ctermbg=0 blend=80".as_ptr(),
    c"FloatShadowThrough                         guibg=NvimDarkGrey4           ctermbg=0 blend=100".as_ptr(),
    c"Folded               guifg=NvimLightGrey4  guibg=NvimDarkGrey1".as_ptr(),
    c"LineNr               guifg=NvimDarkGrey4".as_ptr(),
    c"MatchParen                                 guibg=NvimDarkGrey4  gui=bold cterm=bold,underline".as_ptr(),
    c"ModeMsg              guifg=NvimLightGreen                                ctermfg=10".as_ptr(),
    c"MoreMsg              guifg=NvimLightCyan                                 ctermfg=14".as_ptr(),
    c"NonText              guifg=NvimDarkGrey4".as_ptr(),
    c"NormalFloat                                guibg=NvimDarkGrey1".as_ptr(),
    c"OkMsg                guifg=NvimLightGreen                                ctermfg=10".as_ptr(),
    c"Pmenu                                      guibg=NvimDarkGrey3           cterm=reverse".as_ptr(),
    c"PmenuThumb                                 guibg=NvimDarkGrey4".as_ptr(),
    c"PmenuShadow                                guibg=NvimDarkGrey4           ctermbg=0 blend=100".as_ptr(),
    c"Question             guifg=NvimLightCyan                                 ctermfg=14".as_ptr(),
    c"QuickFixLine         guifg=NvimLightCyan                                 ctermfg=14".as_ptr(),
    c"RedrawDebugClear                           guibg=NvimDarkYellow          ctermfg=0 ctermbg=11".as_ptr(),
    c"RedrawDebugComposed                        guibg=NvimDarkGreen           ctermfg=0 ctermbg=10".as_ptr(),
    c"RedrawDebugRecompose                       guibg=NvimDarkRed             ctermfg=0 ctermbg=9".as_ptr(),
    c"Removed              guifg=NvimLightRed                                  ctermfg=9".as_ptr(),
    c"Search               guifg=NvimLightGrey1  guibg=NvimDarkYellow          ctermfg=0 ctermbg=11".as_ptr(),
    c"SignColumn           guifg=NvimDarkGrey4".as_ptr(),
    c"SpecialKey           guifg=NvimDarkGrey4".as_ptr(),
    c"SpellBad             guisp=NvimLightRed    gui=undercurl                 cterm=undercurl".as_ptr(),
    c"SpellCap             guisp=NvimLightYellow gui=undercurl                 cterm=undercurl".as_ptr(),
    c"SpellLocal           guisp=NvimLightGreen  gui=undercurl                 cterm=undercurl".as_ptr(),
    c"SpellRare            guisp=NvimLightCyan   gui=undercurl                 cterm=undercurl".as_ptr(),
    c"StatusLine           guifg=NvimLightGrey2  guibg=NvimDarkGrey4           cterm=reverse".as_ptr(),
    c"StatusLineNC         guifg=NvimLightGrey3  guibg=NvimDarkGrey3           cterm=bold,underline".as_ptr(),
    c"Title                guifg=NvimLightGrey2                       gui=bold cterm=bold".as_ptr(),
    c"Visual                                     guibg=NvimDarkGrey4           ctermfg=0 ctermbg=15".as_ptr(),
    c"WarningMsg           guifg=NvimLightYellow                               ctermfg=11".as_ptr(),
    c"WinBar               guifg=NvimLightGrey4  guibg=NvimDarkGrey1  gui=bold cterm=bold".as_ptr(),
    c"WinBarNC             guifg=NvimLightGrey4  guibg=NvimDarkGrey1           cterm=bold".as_ptr(),
    // Syntax
    c"Constant   guifg=NvimLightGrey2".as_ptr(),
    c"Operator   guifg=NvimLightGrey2".as_ptr(),
    c"PreProc    guifg=NvimLightGrey2".as_ptr(),
    c"Type       guifg=NvimLightGrey2".as_ptr(),
    c"Delimiter  guifg=NvimLightGrey2".as_ptr(),
    c"Comment    guifg=NvimLightGrey4".as_ptr(),
    c"String     guifg=NvimLightGreen                   ctermfg=10".as_ptr(),
    c"Identifier guifg=NvimLightBlue                    ctermfg=12".as_ptr(),
    c"Function   guifg=NvimLightCyan                    ctermfg=14".as_ptr(),
    c"Statement  guifg=NvimLightGrey2 gui=bold          cterm=bold".as_ptr(),
    c"Special    guifg=NvimLightCyan                    ctermfg=14".as_ptr(),
    c"Error      guifg=NvimLightGrey1 guibg=NvimDarkRed ctermfg=0 ctermbg=9".as_ptr(),
    c"Todo       guifg=NvimLightGrey2 gui=bold          cterm=bold".as_ptr(),
    // Diagnostic
    c"DiagnosticError          guifg=NvimLightRed                      ctermfg=9".as_ptr(),
    c"DiagnosticWarn           guifg=NvimLightYellow                   ctermfg=11".as_ptr(),
    c"DiagnosticInfo           guifg=NvimLightCyan                     ctermfg=14".as_ptr(),
    c"DiagnosticHint           guifg=NvimLightBlue                     ctermfg=12".as_ptr(),
    c"DiagnosticOk             guifg=NvimLightGreen                    ctermfg=10".as_ptr(),
    c"DiagnosticUnderlineError guisp=NvimLightRed    gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineWarn  guisp=NvimLightYellow gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineInfo  guisp=NvimLightCyan   gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineHint  guisp=NvimLightBlue   gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticUnderlineOk    guisp=NvimLightGreen  gui=underline     cterm=underline".as_ptr(),
    c"DiagnosticDeprecated     guisp=NvimLightRed    gui=strikethrough cterm=strikethrough".as_ptr(),
    // Treesitter standard groups
    c"@variable guifg=NvimLightGrey2".as_ptr(),
    std::ptr::null(),
]);
