//! Dispatch wrappers for `crate::src::nvim::api::buffer`.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

pub unsafe extern "C" fn handle_nvim_buf_delete(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_buf_delete",
            c"RPC: ch %lu: invoke nvim_buf_delete",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_handle(item, kObjectTypeBuffer) else {
            wrong_type(error, 1, c"nvim_buf_delete", c"Buffer");
            return NIL;
        };
        let item = *args.items.add(1);
        let mut arg_2: KeyDict_buf_delete = core::mem::zeroed();
        if item.type_0 == kObjectTypeDict {
            if !api_dict_to_keydict(
                (&raw mut arg_2).cast(),
                Some(KeyDict_buf_delete_get_field),
                item.data.dict,
                error,
            ) {
                return NIL;
            }
        } else if !is_empty_array(item) {
            wrong_type(error, 2, c"nvim_buf_delete", c"Dict(buf_delete) *");
            return NIL;
        }
        if text_locked() {
            api_set_error(
                error,
                kErrorTypeException,
                c"%s".as_ptr(),
                get_text_locked_msg(),
            );
            return NIL;
        }
        nvim_buf_delete(arg_1, &raw mut arg_2, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim_buf_get_lines(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_buf_get_lines",
            c"RPC: ch %lu: invoke nvim_buf_get_lines",
            line!() as c_int,
            channel_id,
        );
        if args.size != 4 as size_t {
            wrong_arity(error, 4, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_handle(item, kObjectTypeBuffer) else {
            wrong_type(error, 1, c"nvim_buf_get_lines", c"Buffer");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_integer(item) else {
            wrong_type(error, 2, c"nvim_buf_get_lines", c"Integer");
            return NIL;
        };
        let item = *args.items.add(2);
        let Some(arg_3) = as_integer(item) else {
            wrong_type(error, 3, c"nvim_buf_get_lines", c"Integer");
            return NIL;
        };
        let item = *args.items.add(3);
        let Some(arg_4) = as_boolean(item) else {
            wrong_type(error, 4, c"nvim_buf_get_lines", c"Boolean");
            return NIL;
        };
        let rv = nvim_buf_get_lines(
            channel_id,
            arg_1,
            arg_2,
            arg_3,
            arg_4,
            arena,
            core::ptr::null_mut(),
            error,
        );
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_buf_get_name(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_buf_get_name",
            c"RPC: ch %lu: invoke nvim_buf_get_name",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_handle(item, kObjectTypeBuffer) else {
            wrong_type(error, 1, c"nvim_buf_get_name", c"Buffer");
            return NIL;
        };
        let rv = nvim_buf_get_name(arg_1, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeString, object_data { string: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_buf_is_valid(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_buf_is_valid",
            c"RPC: ch %lu: invoke nvim_buf_is_valid",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_handle(item, kObjectTypeBuffer) else {
            wrong_type(error, 1, c"nvim_buf_is_valid", c"Buffer");
            return NIL;
        };
        let rv = nvim_buf_is_valid(arg_1);
        obj(kObjectTypeBoolean, object_data { boolean: rv })
    }
}
