//! Dispatch wrappers for `crate::src::nvim::api::vim`.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

pub unsafe extern "C" fn handle_nvim__id(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id",
            c"RPC: ch %lu: invoke nvim__id",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let arg_1 = *args.items.add(0);
        nvim__id(arg_1, arena)
    }
}

pub unsafe extern "C" fn handle_nvim__id_array(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id_array",
            c"RPC: ch %lu: invoke nvim__id_array",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_array(item) else {
            wrong_type(error, 1, c"nvim__id_array", c"Array");
            return NIL;
        };
        let rv = nvim__id_array(arg_1, arena);
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__id_dict(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id_dict",
            c"RPC: ch %lu: invoke nvim__id_dict",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_dict(item) else {
            wrong_type(error, 1, c"nvim__id_dict", c"Dict");
            return NIL;
        };
        let rv = nvim__id_dict(arg_1, arena);
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__id_float(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id_float",
            c"RPC: ch %lu: invoke nvim__id_float",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_float(item) else {
            wrong_type(error, 1, c"nvim__id_float", c"Float");
            return NIL;
        };
        let rv = nvim__id_float(arg_1);
        obj(kObjectTypeFloat, object_data { floating: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_get_api_info(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_get_api_info",
            c"RPC: ch %lu: invoke nvim_get_api_info",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim_get_api_info(channel_id, arena);
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_get_current_buf(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_get_current_buf",
            c"RPC: ch %lu: invoke nvim_get_current_buf",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim_get_current_buf();
        obj(
            kObjectTypeBuffer,
            object_data {
                integer: rv as Integer,
            },
        )
    }
}

pub unsafe extern "C" fn handle_nvim_get_mode(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_get_mode",
            c"RPC: ch %lu: invoke nvim_get_mode",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim_get_mode(arena);
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_set_current_line(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_set_current_line",
            c"RPC: ch %lu: invoke nvim_set_current_line",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_set_current_line", c"String");
            return NIL;
        };
        if textlock.get() != 0 || expr_map_locked() {
            api_set_error(
                error,
                kErrorTypeException,
                c"%s".as_ptr(),
                &raw const e_textlock,
            );
            return NIL;
        }
        nvim_set_current_line(arg_1, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}
