//! Dispatch wrappers for `crate::src::nvim::api::vim`, part 1 of 3.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

pub unsafe extern "C" fn handle_nvim__chan_set_detach(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__chan_set_detach",
            c"RPC: ch %lu: invoke nvim__chan_set_detach",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_boolean(item) else {
            wrong_type(error, 1, c"nvim__chan_set_detach", c"Boolean");
            return NIL;
        };
        nvim__chan_set_detach(channel_id, arg_1, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim__complete_set(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__complete_set",
            c"RPC: ch %lu: invoke nvim__complete_set",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_integer(item) else {
            wrong_type(error, 1, c"nvim__complete_set", c"Integer");
            return NIL;
        };
        let item = *args.items.add(1);
        let mut arg_2: KeyDict_complete_set = core::mem::zeroed();
        if item.type_0 == kObjectTypeDict {
            if !api_dict_to_keydict(
                (&raw mut arg_2).cast(),
                Some(KeyDict_complete_set_get_field),
                item.data.dict,
                error,
            ) {
                return NIL;
            }
        } else if !is_empty_array(item) {
            wrong_type(error, 2, c"nvim__complete_set", c"Dict(complete_set) *");
            return NIL;
        }
        let rv = nvim__complete_set(arg_1, &raw mut arg_2, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__exec_lua_fast(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__exec_lua_fast",
            c"RPC: ch %lu: invoke nvim__exec_lua_fast",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim__exec_lua_fast", c"String");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_array(item) else {
            wrong_type(error, 2, c"nvim__exec_lua_fast", c"Array");
            return NIL;
        };
        let rv = nvim__exec_lua_fast(arg_1, arg_2, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        rv
    }
}

pub unsafe extern "C" fn handle_nvim__get_lib_dir(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__get_lib_dir",
            c"RPC: ch %lu: invoke nvim__get_lib_dir",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim__get_lib_dir();
        obj(kObjectTypeString, object_data { string: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__get_runtime(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__get_runtime",
            c"RPC: ch %lu: invoke nvim__get_runtime",
            line!() as c_int,
            channel_id,
        );
        if args.size != 3 as size_t {
            wrong_arity(error, 3, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_array(item) else {
            wrong_type(error, 1, c"nvim__get_runtime", c"ArrayOf(String)");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_boolean(item) else {
            wrong_type(error, 2, c"nvim__get_runtime", c"Boolean");
            return NIL;
        };
        let item = *args.items.add(2);
        let mut arg_3: KeyDict_runtime = core::mem::zeroed();
        if item.type_0 == kObjectTypeDict {
            if !api_dict_to_keydict(
                (&raw mut arg_3).cast(),
                Some(KeyDict_runtime_get_field),
                item.data.dict,
                error,
            ) {
                return NIL;
            }
        } else if !is_empty_array(item) {
            wrong_type(error, 3, c"nvim__get_runtime", c"Dict(runtime) *");
            return NIL;
        }
        let rv = nvim__get_runtime(arg_1, arg_2, &raw mut arg_3, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__id(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id",
            c"RPC: ch %lu: invoke nvim__id",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let arg_1 = *args.items.add(0);
        nvim__id(arg_1, arena)
    }
}

pub unsafe extern "C" fn handle_nvim__id_array(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id_array",
            c"RPC: ch %lu: invoke nvim__id_array",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_array(item) else {
            wrong_type(error, 1, c"nvim__id_array", c"Array");
            return NIL;
        };
        let rv = nvim__id_array(arg_1, arena);
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__id_dict(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id_dict",
            c"RPC: ch %lu: invoke nvim__id_dict",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_dict(item) else {
            wrong_type(error, 1, c"nvim__id_dict", c"Dict");
            return NIL;
        };
        let rv = nvim__id_dict(arg_1, arena);
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__id_float(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__id_float",
            c"RPC: ch %lu: invoke nvim__id_float",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_float(item) else {
            wrong_type(error, 1, c"nvim__id_float", c"Float");
            return NIL;
        };
        let rv = nvim__id_float(arg_1);
        obj(kObjectTypeFloat, object_data { floating: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__inspect_cell(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__inspect_cell",
            c"RPC: ch %lu: invoke nvim__inspect_cell",
            line!() as c_int,
            channel_id,
        );
        if args.size != 3 as size_t {
            wrong_arity(error, 3, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_integer(item) else {
            wrong_type(error, 1, c"nvim__inspect_cell", c"Integer");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_integer(item) else {
            wrong_type(error, 2, c"nvim__inspect_cell", c"Integer");
            return NIL;
        };
        let item = *args.items.add(2);
        let Some(arg_3) = as_integer(item) else {
            wrong_type(error, 3, c"nvim__inspect_cell", c"Integer");
            return NIL;
        };
        let rv = nvim__inspect_cell(arg_1, arg_2, arg_3, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__invalidate_glyph_cache(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__invalidate_glyph_cache",
            c"RPC: ch %lu: invoke nvim__invalidate_glyph_cache",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        nvim__invalidate_glyph_cache();
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim__redraw(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__redraw",
            c"RPC: ch %lu: invoke nvim__redraw",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let mut arg_1: KeyDict_redraw = core::mem::zeroed();
        if item.type_0 == kObjectTypeDict {
            if !api_dict_to_keydict(
                (&raw mut arg_1).cast(),
                Some(KeyDict_redraw_get_field),
                item.data.dict,
                error,
            ) {
                return NIL;
            }
        } else if !is_empty_array(item) {
            wrong_type(error, 1, c"nvim__redraw", c"Dict(redraw) *");
            return NIL;
        }
        nvim__redraw(&raw mut arg_1, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim__runtime_inspect(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__runtime_inspect",
            c"RPC: ch %lu: invoke nvim__runtime_inspect",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim__runtime_inspect(arena);
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__screenshot(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__screenshot",
            c"RPC: ch %lu: invoke nvim__screenshot",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim__screenshot", c"String");
            return NIL;
        };
        nvim__screenshot(arg_1);
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim__stats(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__stats",
            c"RPC: ch %lu: invoke nvim__stats",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim__stats(arena);
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}

pub unsafe extern "C" fn handle_nvim__unpack(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim__unpack",
            c"RPC: ch %lu: invoke nvim__unpack",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim__unpack", c"String");
            return NIL;
        };
        let rv = nvim__unpack(arg_1, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        rv
    }
}

pub unsafe extern "C" fn handle_nvim_chan_send(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_chan_send",
            c"RPC: ch %lu: invoke nvim_chan_send",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_integer(item) else {
            wrong_type(error, 1, c"nvim_chan_send", c"Integer");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_string(item) else {
            wrong_type(error, 2, c"nvim_chan_send", c"String");
            return NIL;
        };
        nvim_chan_send(arg_1, arg_2, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim_create_buf(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_create_buf",
            c"RPC: ch %lu: invoke nvim_create_buf",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_boolean(item) else {
            wrong_type(error, 1, c"nvim_create_buf", c"Boolean");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_boolean(item) else {
            wrong_type(error, 2, c"nvim_create_buf", c"Boolean");
            return NIL;
        };
        let rv = nvim_create_buf(arg_1, arg_2, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(
            kObjectTypeBuffer,
            object_data {
                integer: rv as Integer,
            },
        )
    }
}

pub unsafe extern "C" fn handle_nvim_del_current_line(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_del_current_line",
            c"RPC: ch %lu: invoke nvim_del_current_line",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        if textlock.get() != 0 || expr_map_locked() {
            api_set_error(
                error,
                kErrorTypeException,
                c"%s".as_ptr(),
                &raw const e_textlock,
            );
            return NIL;
        }
        nvim_del_current_line(arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim_del_keymap(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_del_keymap",
            c"RPC: ch %lu: invoke nvim_del_keymap",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_del_keymap", c"String");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_string(item) else {
            wrong_type(error, 2, c"nvim_del_keymap", c"String");
            return NIL;
        };
        nvim_del_keymap(channel_id, arg_1, arg_2, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim_del_mark(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_del_mark",
            c"RPC: ch %lu: invoke nvim_del_mark",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_del_mark", c"String");
            return NIL;
        };
        let rv = nvim_del_mark(arg_1, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeBoolean, object_data { boolean: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_del_var(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_del_var",
            c"RPC: ch %lu: invoke nvim_del_var",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_del_var", c"String");
            return NIL;
        };
        nvim_del_var(arg_1, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim_echo(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_echo",
            c"RPC: ch %lu: invoke nvim_echo",
            line!() as c_int,
            channel_id,
        );
        if args.size != 3 as size_t {
            wrong_arity(error, 3, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_array(item) else {
            wrong_type(
                error,
                1,
                c"nvim_echo",
                c"ArrayOf(Tuple(String, *HLGroupID))",
            );
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_boolean(item) else {
            wrong_type(error, 2, c"nvim_echo", c"Boolean");
            return NIL;
        };
        let item = *args.items.add(2);
        let mut arg_3: KeyDict_echo_opts = core::mem::zeroed();
        if item.type_0 == kObjectTypeDict {
            if !api_dict_to_keydict(
                (&raw mut arg_3).cast(),
                Some(KeyDict_echo_opts_get_field),
                item.data.dict,
                error,
            ) {
                return NIL;
            }
        } else if !is_empty_array(item) {
            wrong_type(error, 3, c"nvim_echo", c"Dict(echo_opts) *");
            return NIL;
        }
        let rv = nvim_echo(arg_1, arg_2, &raw mut arg_3, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        rv
    }
}

pub unsafe extern "C" fn handle_nvim_eval_statusline(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_eval_statusline",
            c"RPC: ch %lu: invoke nvim_eval_statusline",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_eval_statusline", c"String");
            return NIL;
        };
        let item = *args.items.add(1);
        let mut arg_2: KeyDict_eval_statusline = core::mem::zeroed();
        if item.type_0 == kObjectTypeDict {
            if !api_dict_to_keydict(
                (&raw mut arg_2).cast(),
                Some(KeyDict_eval_statusline_get_field),
                item.data.dict,
                error,
            ) {
                return NIL;
            }
        } else if !is_empty_array(item) {
            wrong_type(
                error,
                2,
                c"nvim_eval_statusline",
                c"Dict(eval_statusline) *",
            );
            return NIL;
        }
        let rv = nvim_eval_statusline(arg_1, &raw mut arg_2, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_exec_lua(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_exec_lua",
            c"RPC: ch %lu: invoke nvim_exec_lua",
            line!() as c_int,
            channel_id,
        );
        if args.size != 2 as size_t {
            wrong_arity(error, 2, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_exec_lua", c"String");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_array(item) else {
            wrong_type(error, 2, c"nvim_exec_lua", c"Array");
            return NIL;
        };
        let rv = nvim_exec_lua(arg_1, arg_2, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        rv
    }
}

pub unsafe extern "C" fn handle_nvim_feedkeys(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_feedkeys",
            c"RPC: ch %lu: invoke nvim_feedkeys",
            line!() as c_int,
            channel_id,
        );
        if args.size != 3 as size_t {
            wrong_arity(error, 3, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_feedkeys", c"String");
            return NIL;
        };
        let item = *args.items.add(1);
        let Some(arg_2) = as_string(item) else {
            wrong_type(error, 2, c"nvim_feedkeys", c"String");
            return NIL;
        };
        let item = *args.items.add(2);
        let Some(arg_3) = as_boolean(item) else {
            wrong_type(error, 3, c"nvim_feedkeys", c"Boolean");
            return NIL;
        };
        nvim_feedkeys(arg_1, arg_2, arg_3);
        NIL
    }
}

pub unsafe extern "C" fn handle_nvim_get_api_info(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_get_api_info",
            c"RPC: ch %lu: invoke nvim_get_api_info",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim_get_api_info(channel_id, arena);
        obj(kObjectTypeArray, object_data { array: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_get_chan_info(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_get_chan_info",
            c"RPC: ch %lu: invoke nvim_get_chan_info",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_integer(item) else {
            wrong_type(error, 1, c"nvim_get_chan_info", c"Integer");
            return NIL;
        };
        let rv = nvim_get_chan_info(channel_id, arg_1, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_get_color_by_name(
    channel_id: uint64_t,
    args: Array,
    _arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_get_color_by_name",
            c"RPC: ch %lu: invoke nvim_get_color_by_name",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_string(item) else {
            wrong_type(error, 1, c"nvim_get_color_by_name", c"String");
            return NIL;
        };
        let rv = nvim_get_color_by_name(arg_1);
        obj(kObjectTypeInteger, object_data { integer: rv })
    }
}

pub unsafe extern "C" fn handle_nvim_get_color_map(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_get_color_map",
            c"RPC: ch %lu: invoke nvim_get_color_map",
            line!() as c_int,
            channel_id,
        );
        if args.size != 0 as size_t {
            wrong_arity(error, 0, args.size);
            return NIL;
        }
        let rv = nvim_get_color_map(arena);
        obj(kObjectTypeDict, object_data { dict: rv })
    }
}
