//! Dispatch wrappers for `crate::src::nvim::api::win_config`.
//!
//! GENERATED by tools/apigen; see the parent module. Do not edit;
//! run `just apigen`.

#![deny(unsafe_op_in_unsafe_fn)]

use super::*;

pub unsafe extern "C" fn handle_nvim_win_get_config(
    channel_id: uint64_t,
    args: Array,
    arena: *mut Arena,
    error: *mut Error,
) -> Object {
    unsafe {
        log_invoke(
            c"handle_nvim_win_get_config",
            c"RPC: ch %lu: invoke nvim_win_get_config",
            line!() as c_int,
            channel_id,
        );
        if args.size != 1 as size_t {
            wrong_arity(error, 1, args.size);
            return NIL;
        }
        let item = *args.items.add(0);
        let Some(arg_1) = as_handle(item, kObjectTypeWindow) else {
            wrong_type(error, 1, c"nvim_win_get_config", c"Window");
            return NIL;
        };
        let mut rv = nvim_win_get_config(arg_1, arena, error);
        if (*error).type_0 != kErrorTypeNone {
            return NIL;
        }
        obj(
            kObjectTypeDict,
            object_data {
                dict: api_keydict_to_dict(
                    (&raw mut rv).cast(),
                    win_config_table.ptr().cast(),
                    25 as size_t,
                    arena,
                ),
            },
        )
    }
}
